
  CREATE OR REPLACE VIEW VW_VALUE_DOM_BASIC AS
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN,  ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, 
		      ADMIN_ITEM.CURRNT_VER_IND, VALUE_DOM.DTTYPE_ID, VALUE_DOM.VAL_DOM_MAX_CHAR, VALUE_DOM.CONC_DOM_VER_NR, VALUE_DOM.CONC_DOM_ITEM_ID, 
VALUE_DOM.NON_ENUM_VAL_DOM_DESC, VALUE_DOM.UOM_ID, VALUE_DOM.VAL_DOM_TYP_ID, VALUE_DOM.VAL_DOM_MIN_CHAR, VALUE_DOM.VAL_DOM_FMT_ID, 
VALUE_DOM.CHAR_SET_ID, VALUE_DOM.CREAT_DT, VALUE_DOM.CREAT_USR_ID, VALUE_DOM.LST_UPD_USR_ID, 
VALUE_DOM.FLD_DELETE, VALUE_DOM.LST_DEL_DT, VALUE_DOM.S2P_TRN_DT, VALUE_DOM.LST_UPD_DT , 
	  value_dom.rep_cls_item_id, value_dom.rep_cls_ver_nr,
	  value_dom.NCI_STD_DTTYPE_ID, DECODE(value_dom.val_dom_typ_id, 17, 'Enumerated', 18, 'Non-enumerated', 16, 'Enumerated by Reference') VAL_DOM_TYPE
FROM ADMIN_ITEM, VALUE_DOM
       WHERE ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 3
AND ADMIN_ITEM.ITEM_ID = VALUE_DOM.ITEM_ID
AND ADMIN_ITEM.VER_NR=VALUE_DOM.VER_NR ;


  CREATE TABLE NCI_DS_BTCH_HDR 
   (	
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	"CREATED_DT" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LST_TRIGGER_DT" DATE DEFAULT sysdate, 
	"NUM_CDE_MTCH" NUMBER(*,0), 
	"NUM_PV" NUMBER(*,0), 
	"BTCH_NM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BTCH_USR_NM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CMNTS_DESC_TXT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MTCH_TYP_NM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'CDE', 
	"DT_LAST_MODIFIED" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"DT_SORT" TIMESTAMP (9) DEFAULT sysdate, 
	"LST_RUN_TYP" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"LST_RUN_DT" TIMESTAMP (6), 
	 PRIMARY KEY (BTCH_NM, BTCH_USR_NM)
   );


  CREATE OR REPLACE VIEW VW_NCI_DS_RSLT_BTCH AS
  select r.HDR_ID,h.btch_usr_nm, h.btch_nm, r.ITEM_ID,r.VER_NR,r.RULE_ID,r.SCORE,r.RULE_DESC,r.USR_CMNTS,r.NUM_PV_IN_SRC,r.NUM_PV_IN_CDE,r.NUM_PV_MTCH,r.NM_MTCH_PRCNT,
  r.NUM_PV_MTCH_FUZZY,r.CREAT_DT,r.CREAT_USR_ID,r.LST_UPD_USR_ID,r.FLD_DELETE,r.LST_DEL_DT,r.S2P_TRN_DT,r.LST_UPD_DT,r.MTCH_DESC_TXT,
  r.MTCH_TYP,r.CDE_PREF_IND,r.SRC_MTCH_ENGN from nci_ds_rslt r, nci_ds_hdr h where r.hdr_id = h.hdr_id
  union
  select h.hdr_id, h.btch_usr_nm, h.btch_nm,17175416, 1, null, null, null, null, null, null, null, null, 
  null, h.creat_dt,h.creat_usr_id,LST_UPD_USR_ID,FLD_DELETE,LST_DEL_DT,S2P_TRN_DT,LST_UPD_DT,null,
  'CDE', null, null from nci_ds_hdr h where h.hdr_id not in (select hdr_id from nci_ds_rslt) and MTCH_TYP_NM = 'CDE';



