
  CREATE TABLE "ONEDATA_WA"."NCI_DLOAD_CDE_MDL_IMP_TMPLT" 
   (	"HDR_ID" NUMBER, 
	"LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"VER_NR" NUMBER(4,2), 
	"CNTXT_NM_DN" VARCHAR2(175 BYTE) COLLATE "USING_NLS_COMP", 
	"NM_TYP_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ONEDATA_RA"."NCI_DLOAD_CDE_MDL_IMP_TMPLT" 
   (	"HDR_ID" NUMBER, 
	"LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"VER_NR" NUMBER(4,2), 
	"CNTXT_NM_DN" VARCHAR2(175 BYTE) COLLATE "USING_NLS_COMP", 
	"NM_TYP_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

Insert into ONEDATA_WA.OBJ_KEY (OBJ_KEY_ID,OBJ_KEY_DESC,OBJ_TYP_ID,OBJ_KEY_CD,OBJ_KEY_DEF,CREAT_DT,CREAT_USR_ID,LST_UPD_USR_ID,FLD_DELETE,LST_DEL_DT,S2P_TRN_DT,LST_UPD_DT,OBJ_KEY_CMNTS,NCI_CD,DISP_ORD,MIN_CNT,MAX_CNT) values (249,'Export into Model Import Template',31,null,'Export into Model Import Template',to_date('02-FEB-26','DD-MON-RR'),'ONEDATA_WA','ONEDATA_WA',0,to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),null,'Export into Model Import Template',null,null,null);
Insert into ONEDATA_RA.OBJ_KEY (OBJ_KEY_ID,OBJ_KEY_DESC,OBJ_TYP_ID,OBJ_KEY_CD,OBJ_KEY_DEF,CREAT_DT,CREAT_USR_ID,LST_UPD_USR_ID,FLD_DELETE,LST_DEL_DT,S2P_TRN_DT,LST_UPD_DT,OBJ_KEY_CMNTS,NCI_CD,DISP_ORD,MIN_CNT,MAX_CNT) values (249,'Export into Model Import Template',31,null,'Export into Model Import Template',to_date('02-FEB-26','DD-MON-RR'),'ONEDATA_WA','ONEDATA_WA',0,to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),null,'Export into Model Import Template',null,null,null);

