
  CREATE TABLE "ONEDATA_WA"."NCI_DLOAD_CDE_MDL_IMP_TMPLT" 
   (	"HDR_ID" NUMBER, 
	"LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"VER_NR" NUMBER(4,2), 
	"CNTXT_NM_DN" VARCHAR2(175 BYTE) COLLATE "USING_NLS_COMP", 
	"NM_TYP_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ONEDATA_RA"."NCI_DLOAD_CDE_MDL_IMP_TMPLT" 
   (	"HDR_ID" NUMBER, 
	"LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"VER_NR" NUMBER(4,2), 
	"CNTXT_NM_DN" VARCHAR2(175 BYTE) COLLATE "USING_NLS_COMP", 
	"NM_TYP_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

Insert into ONEDATA_WA.OBJ_KEY (OBJ_KEY_ID,OBJ_KEY_DESC,OBJ_TYP_ID,OBJ_KEY_CD,OBJ_KEY_DEF,CREAT_DT,CREAT_USR_ID,LST_UPD_USR_ID,FLD_DELETE,LST_DEL_DT,S2P_TRN_DT,LST_UPD_DT,OBJ_KEY_CMNTS,NCI_CD,DISP_ORD,MIN_CNT,MAX_CNT) values (249,'Export into Model Import Template',31,null,'Export into Model Import Template',to_date('02-FEB-26','DD-MON-RR'),'ONEDATA_WA','ONEDATA_WA',0,to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),null,'Export into Model Import Template',null,null,null);
Insert into ONEDATA_RA.OBJ_KEY (OBJ_KEY_ID,OBJ_KEY_DESC,OBJ_TYP_ID,OBJ_KEY_CD,OBJ_KEY_DEF,CREAT_DT,CREAT_USR_ID,LST_UPD_USR_ID,FLD_DELETE,LST_DEL_DT,S2P_TRN_DT,LST_UPD_DT,OBJ_KEY_CMNTS,NCI_CD,DISP_ORD,MIN_CNT,MAX_CNT) values (249,'Export into Model Import Template',31,null,'Export into Model Import Template',to_date('02-FEB-26','DD-MON-RR'),'ONEDATA_WA','ONEDATA_WA',0,to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),to_date('02-FEB-26','DD-MON-RR'),null,'Export into Model Import Template',null,null,null);

--jira 9246
CREATE OR REPLACE FORCE EDITIONABLE VIEW VW_VALUE_DOM ("ITEM_ID", "VER_NR", "ITEM_NM", "ITEM_LONG_NM", "ITEM_DESC", "CNTXT_NM_DN", "REGSTR_STUS_NM_DN", "ADMIN_STUS_NM_DN", "CURRNT_VER_IND", "DTTYPE_ID", "VAL_DOM_MAX_CHAR", "CONC_DOM_VER_NR", "CONC_DOM_ITEM_ID", "NON_ENUM_VAL_DOM_DESC", "UOM_ID", "VAL_DOM_TYP_ID", "VAL_DOM_MIN_CHAR", "VAL_DOM_FMT_ID", "CHAR_SET_ID", "CREAT_DT", "CREAT_USR_ID", "LST_UPD_USR_ID", "FLD_DELETE", "LST_DEL_DT", "S2P_TRN_DT", "LST_UPD_DT", "REP_TERM_ITEM_NM", "SUBSET_DESC", "PRNT_SUBSET_ITEM_ID", "PRNT_SUBSET_VER_NR", "NCI_STD_DTTYPE_ID", "TERM_NAME", "USE_NAME", "TERM_USE_NAME", "VAL_DOM_TYP_NM", "CNCPT_CONCAT") AS 
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN,  ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, 
		      ADMIN_ITEM.CURRNT_VER_IND, VALUE_DOM.DTTYPE_ID, VALUE_DOM.VAL_DOM_MAX_CHAR, VALUE_DOM.CONC_DOM_VER_NR, VALUE_DOM.CONC_DOM_ITEM_ID, 
VALUE_DOM.NON_ENUM_VAL_DOM_DESC, VALUE_DOM.UOM_ID, VALUE_DOM.VAL_DOM_TYP_ID, VALUE_DOM.VAL_DOM_MIN_CHAR, VALUE_DOM.VAL_DOM_FMT_ID, 
VALUE_DOM.CHAR_SET_ID, VALUE_DOM.CREAT_DT, VALUE_DOM.CREAT_USR_ID, VALUE_DOM.LST_UPD_USR_ID, 
VALUE_DOM.FLD_DELETE, VALUE_DOM.LST_DEL_DT, VALUE_DOM.S2P_TRN_DT, VALUE_DOM.LST_UPD_DT , RC.ITEM_NM  REP_TERM_ITEM_NM,
	  value_dom.subset_desc, value_dom.PRNT_SUBSET_ITEM_ID, value_dom.PRNT_SUBSET_VER_NR,
	  value_dom.NCI_STD_DTTYPE_ID, term.term_name, term.use_name, term.term_use_name, DECODE(value_dom.val_dom_typ_id, 17, 'Enumerated', 18, 'Non-enumerated', 16, 'Enumerated by Reference'),
      prt.CNCPT_CONCAT
FROM ADMIN_ITEM, VALUE_DOM, VW_REP_CLS RC, vw_val_dom_ref_term term, VW_NCI_REP_TERM prt
       WHERE ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 3
AND ADMIN_ITEM.ITEM_ID = VALUE_DOM.ITEM_ID
AND ADMIN_ITEM.VER_NR=VALUE_DOM.VER_NR and
VALUE_DOM.REP_CLS_ITEM_ID = RC.ITEM_ID (+) and 
VALUE_DOM.REP_CLS_VER_NR = RC.VER_NR (+)
and
VALUE_DOM.ITEM_ID = TERM.ITEM_ID (+) and 
VALUE_DOM.VER_NR = TERM.VER_NR (+)
and 
VALUE_DOM.REP_CLS_ITEM_ID = prt.ITEM_ID (+) AND
VALUE_DOM.REP_CLS_VER_NR = prt.VER_NR (+);
