 CREATE SEQUENCE OD_SEQ_NCI_JOB_LOG
          INCREMENT BY 1
          START WITH 1000;
          
drop sequence od_seq_lang;

 CREATE SEQUENCE od_seq_lang
          INCREMENT BY 1
          START WITH 2000;

CREATE OR REPLACE TRIGGER OD_TR_REF_DOC  BEFORE INSERT  on REF_DOC  for each row
                  BEGIN    IF (:NEW.REF_DOC_ID<= 0  or :NEW.REF_DOC_ID is null)  THEN 
                  select od_seq_REF_DOC.nextval
            into :new.REF_DOC_ID  from  dual ;   END IF; 
  
             IF (:new.nci_idseq is null)  THEN 
                  :new.nci_idseq := nci_11179.cmr_guid();  END IF; 
                  END ;          
/



CREATE MATERIALIZED VIEW LOG ON ADMIN_ITEM WITH PRIMARY KEY;



drop materialized view vw_clsfctn_schm;

create materialized view  VW_CLSFCTN_SCHM
  BUILD IMMEDIATE
  REFRESH FORCE
  ON COMMIT AS  
SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN, ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, ADMIN_ITEM.CREAT_DT, 
ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, 
ADMIN_ITEM.LST_UPD_DT, CS.CLSFCTN_SCHM_TYP_ID, ADMIN_ITEM.NCI_IDSEQ, ADMIN_ITEM.CNTXT_ITEM_ID, ADMIN_ITEM.CNTXT_VER_NR
FROM ADMIN_ITEM, CLSFCTN_SCHM CS
       WHERE ADMIN_ITEM_TYP_ID = 9 and ADMIN_ITEM.ITEM_ID = CS.ITEM_ID and ADMIN_ITEM.VER_NR = CS.VER_NR; 


