 CREATE or REPLACE VIEW VW_OD_CADSR_TAB_COLUM_DEF_SIZE as
 
 select*from(
 SELECT  'Administered Items' DB_OBJECTS,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE 
 FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in 
 ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID','ITEM_NM_CURATED','ITEM_NM_ID_VER','LEGCY_CD','LST_UPD_USR_ID_X','ABAC_ATTR','ALT_KEY','BTCH_NR','CNTXT_NM_DN','CURRNT_VER_IND','UNRSLVD_ISSUE')
and DATA_TYPE <>'DATE' and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0 and table_name ='ADMIN_ITEM'
UNION
 SELECT  'DE' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DE'
UNION
SELECT  'DE Concept' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DE_CONC'
UNION
 SELECT 'Format' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name ='FMT'
 UNION
 SELECT  'Data type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DATA_TYP'
UNION
SELECT 'Registration Status' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='STUS_MSTR'
UNION
SELECT 'Workflow Status' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='STUS_MSTR'
UNION
SELECT 'UOM' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='UOM'
UNION
SELECT 'Conceptual Domain' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CONC_DOM'
UNION
SELECT 'Object Class' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_CLS'
 UNION
 SELECT 'Property' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='PROP'  
UNION
SELECT 'Value Domain' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='VALUE_DOM' 
UNION
SELECT 'Concept' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CNCPT'  
UNION
SELECT 'CSI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_CLSFCTN_SCHM_ITEM'  
UNION
SELECT 'Classification Scheme' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CLSFCTN_SCHM' 
UNION 
SELECT 'Representation Class' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='REP_CLS' 
UNION
SELECT 'Value Meaning' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_VAL_MEAN' 
UNION
SELECT 'Protocol' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_PROTCL'  
UNION
SELECT 'OC Recs' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_OC_RECS'
UNION
SELECT 'Context' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CNTXT' 
UNION
SELECT 'CD-VM' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CONC_DOM_VAL_MEAN' 
UNION
SELECT 'PV' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='PERM_VAL' 
UNION
SELECT 'Designations' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='ALT_NMS' 
UNION
SELECT 'Definitions' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='ALT_DEF' 
UNION
SELECT 'Reference Documents' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='REF' 
UNION
SELECT 'Trigger Actions'MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_FORM_TA' 
UNION
SELECT 'Trigger Actions Protocol/CSI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_FORM_TA_REL' 
UNION
SELECT 'Organization' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ORG' 
UNION
SELECT 'Person',OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_PRSN' 
UNION
SELECT 'Addresses' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ENTTY_ADDR'  
UNION
SELECT 'Communications' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ENTTY_COMM' 
UNION
SELECT 'COMPLEX DE Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ADMIN_ITEM_REL'
UNION
SELECT 'Address Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Communication Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Definition Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Derivation Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Designation Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Document Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Form Category' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Origin' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Program Area' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Protocol Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'CSI Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Classification Scheme Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='OBJ_KEY'
UNION
SELECT 'Status-Admin Type Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_AI_TYP_VALID_STUS' 
UNION
SELECT 'Concept - AI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='CNCPT_ADMIN_ITEM'
UNION
SELECT 'Form,Form HDR Instruction,From Footer Instruction'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_FORM' 
UNION
SELECT 'Module, Module Instruction' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ADMIN_ITEM_REL' 
UNION
SELECT 'COMPLEX DE Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ADMIN_ITEM_REL' 
UNION
SELECT 'CS CSI DE Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ADMIN_ITEM_REL' 
UNION
SELECT 'Question, Question Instruction' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_ADMIN_ITEM_REL_ALT_KEY' 
UNION
SELECT 'Question VV, VV Instruction' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_QUEST_VALID_VALUE' 
UNION
SELECT 'CS CSI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='NCI_CLSFCTN_SCHM_ITEM CSI'
UNION
SELECT 'Language' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where  owner='ONEDATA_WA' and column_name not in ('CREAT_DT','LST_DEL_DT','ITEM_ID','LST_UPD_USR_ID','LST_UPD_DT','S2P_TRN_DT','FLD_DELETE','CREAT_USR_ID') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'VER_NR')=0 and INSTR(column_name ,'_ID')=0  and table_name='LANG'
UNION
 SELECT  'Administered Items' Tables_Used,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_Name ='ADMINISTERED_COMPONENTS'
UNION
SELECT  'DE' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_Name ='DATA_ELEMENTS'
union 
SELECT  'DE Concept' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner= 'SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name='DATA_ELEMENT_CONCEPTS'
UNION
SELECT 'Format' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name='FORMATS_LOV'
UNION
SELECT  'Data type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DATATYPES_LOV'
UNION
SELECT 'Registration Status' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name = 'REG_STATUS_LOV'
UNION
SELECT  'Workflow Status' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='AC_STATUS_LOV'
UNION
SELECT 'UOM' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='UNIT_OF_MEASURES_LOV'
UNION
SELECT 'Conceptual Domain'MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CONCEPTUAL_DOMAINS' 
UNION 
 

UNION
SELECT 'Property' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='PROPERTIES_EXT' 
UNION
SELECT 'Value Domain' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='VALUE_DOMAINS' 
UNION
SELECT 'Concept' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CONCEPTS_EXT'  
UNION
SELECT 'CSI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CS_ITEMS' 
UNION
SELECT 'Classification Scheme'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CLASSIFICATION_SCHEMES' 
UNION
SELECT 'Representation Class' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='REPRESENTATIONS_EXT' 
UNION
SELECT 'Value Meaning' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='VALUE_MEANINGS' 
UNION
SELECT 'Protocol' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='PROTOCOLS_EXT' 
UNION
SELECT 'OC Recs' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='OC_RECS_EXT' 
UNION
SELECT 'Context' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CONTEXTS' 
UNION
SELECT 'CD-VM' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CD_VMS' 
UNION
SELECT 'PV' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='VD_PVS'
UNION
SELECT 'Designations' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DESIGNATIONS' 
UNION
SELECT 'Definitions' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DEFINITIONS' 
UNION
SELECT 'Reference Documents' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='REFERENCE_DOCUMENTS' 
UNION
SELECT 'Trigger Actions'MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='TRIGGERED_ACTIONS_EXT' 
UNION
SELECT 'Trigger Actions Protocol/CSI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='TA_PROTO_CSI_EXT' 
UNION
SELECT 'Organization'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='ORGANIZATIONS' 
UNION
SELECT 'Person',OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='PERSONS' 
UNION
SELECT 'Addresses' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CONTACT_ADDRESSES' 
UNION
SELECT 'Communications' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CONTACT_COMMS' 
UNION
SELECT 'COMPLEX DE Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='COMPLEX_DE_RELATIONSHIPS'
UNION
SELECT 'Program Area' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='PROGRAM_AREAS_LOV' 
UNION
SELECT 'Designation Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DESIGNATION_TYPES_LOV'
UNION
SELECT 'Address Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='ADDR_TYPES_LOV'
UNION
SELECT 'Communication Type'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='COMM_TYPES_LOV'
UNION
SELECT 'Status-Admin Type Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='ASL_ACTL_EXT'
UNION
SELECT 'Derivation Type',OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='COMPLEX_REP_TYPE_LOV'
UNION
SELECT 'Document Type'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DOCUMENT_TYPES_LOV'
UNION
SELECT 'Classification Scheme Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CS_TYPES_LOV'
UNION
SELECT 'CSI Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CSI_TYPES_LOV'
UNION
SELECT 'Definition Type' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='DEFINITION_TYPES_LOV_EXT'
UNION
SELECT 'Origin' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='SOURCES_EXT'
UNION
SELECT 'Protocol Type'MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name='PROTOCOLS_EXT'
UNION
SELECT 'Form Category' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='QC_DISPLAY_LOV_EXT'
UNION
SELECT 'Concept - AI' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT,SBR' and table_name  in('COMPONENT_CONCEPTS_EXT','SBR.CONCEPTS_EXT CON ')
UNION
SELECT 'Form Elements'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBREXT' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE' and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='QUEST_CONTENTS_EXT'
UNION
SELECT 'CS CSI'  MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='CS_CSI'
UNION
SELECT 'CS CSI DE Relationship' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='AC_CSI'
UNION
SELECT 'Language' MP,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,  DATA_PRECISION||','||DATA_SCALE PRECISION_SCALE FROM all_tab_columns  where owner='SBR' and column_name not in ('DATE_CREATED','DATE_MODIFIED','DELETED_IND','CREATED_BY','MODIFIED_BY','VERSION') and DATA_TYPE <>'DATE'and INSTR(column_name ,'_IDSEQ')=0 and INSTR(column_name ,'_ID')=0  and table_name ='LANGUAGES_LOV'

)   order by  1,3,5,4;