CREATE OR REPLACE PROCEDURE ONEDATA_WA.SP_OD_CADSR_TAB_28_INSERT as
/*insert XML*/
P_file number;
l_file_name      VARCHAR2(100);
l_file_path      VARCHAR2(200);
l_result         CLOB:=null;
l_xmldoc          CLOB:=null;
errmsg VARCHAR2(500):='Non';

CURSOR c_od IS
select *
FROM VW_OD_CADSR_TAB_COLUM_DEF_SIZE
WHERE OWNER ='ONEDATA_WA';

BEGIN


delete from OD_CADSR_TAB_28_INSERT;
commit;
INSERT into OD_CADSR_TAB_28_INSERT (DB_OBJECT,
  OD_OWNER ,
  OD_TABLE_NAME ,
  OD_COLUMN_NAME ,
  OD_DATA_TYPE ,
  OD_DATA_LENGTH) 
select DB_OBJECTS,OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH FROM VW_OD_CADSR_TAB_COLUM_DEF_SIZE WHERE OWNER ='ONEDATA_WA';
commit; 
delete from OD_CADSR_TAB_28_INSERT where  OD_COLUMN_NAME like '%_ID' or OD_COLUMN_NAME  like '%VER_NR';
commit; 
MERGE INTO OD_CADSR_TAB_28_INSERT t1
USING
(
-- For more complicated queries you can use WITH clause here
SELECT DISTINCT TABLE_NAME,OWNER, DB_OBJECTS FROM VW_OD_CADSR_TAB_COLUM_DEF_SIZE  where OWNER IN ('SBR','SBREXT')
)t2
ON(t1.DB_OBJECT = t2.DB_OBJECTS)
WHEN MATCHED THEN UPDATE SET
t1.CADSR_TABLE_NAME=t2.TABLE_NAME,
t1.CADSR_OWNER=t2.OWNER;
commit;
 
update OD_CADSR_TAB_28_INSERT set  CADSR_TABLE_NAME='QUEST_CONTENTS_EXT',
CADSR_OWNER='SBREXT' where instr(DB_OBJECT,'Form,Form')>0 or instr(DB_OBJECT,'Module')>0 
or instr(DB_OBJECT,'Question')>0  ;          
commit;
                       
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='N/A',CADSR_COLUMN_NAME='NA'
where OD_TABLE_NAME='ADMIN_ITEM' and 
OD_COLUMN_NAME 
in  ( 'ADMIN_STUS_ID','REGSTR_STUS_ID','SUBMT_CNTCT_ID','SUBMT_ORG_ID','STEWRD_CNTCT_ID','STEWRD_ORG_ID','ADMIN_NOTES');
commit;   
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_COLUMN_NAME='DEFINITION_SOURCE',CADSR_TABLE_NAME='VALUE_MEANINGS',CADSR_OWNER='SBR'
where OD_TABLE_NAME='ADMIN_ITEM' and OD_COLUMN_NAME ='DEF_SRC';
commit;             
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='AC_REGISTRATIONS', CADSR_OWNER='SBR',CADSR_COLUMN_NAME='REGISTRAITION_STATUS'
where OD_TABLE_NAME='ADMIN_ITEM' and OD_COLUMN_NAME ='REGSTR_STUS_NM_DN';
commit;  
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='SOURCES_EXT', CADSR_OWNER='SBR',CADSR_COLUMN_NAME='SRC_NAME'
where OD_TABLE_NAME='ADMIN_ITEM' and OD_COLUMN_NAME ='ORIGIN_ID_DN';
commit;  



UPDATE OD_CADSR_TAB_28_INSERT set CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='ADMIN_STUS_NM_DN'
      THEN 'ASL'
      WHEN OD_COLUMN_NAME='ITEM_DESC'     
      THEN 'PREFERRED_DEFINITION'
      WHEN OD_COLUMN_NAME='ITEM_LONG_NM'
      THEN 'PREFERRED_NAME'
      WHEN OD_COLUMN_NAME='ITEM_NM'
      THEN 'LONG_NAME'
--      WHEN OD_COLUMN_NAME='DEF_SRC'
--      THEN 'DEFINITION_SOURCE'
      WHEN OD_COLUMN_NAME='CHNG_DESC_TXT'
      THEN 'CHANGE_NOTE'
      WHEN OD_COLUMN_NAME='ORIGIN'
      THEN 'ORIGIN'
      ELSE
      CADSR_COLUMN_NAME
      END
where OD_TABLE_NAME='ADMIN_ITEM';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='AC_STATUS_LOV',
CADSR_COLUMN_NAME
= CASE WHEN OD_COLUMN_NAME in('NCI_STUS','STUS_NM')
      THEN 'ASL_NAME'
      WHEN OD_COLUMN_NAME='STUS_DESC'
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='NCI_CMNTS'
      THEN 'COMMENTS'
      WHEN OD_COLUMN_NAME='NCI_DISP_ORDR'
      THEN 'DISPLAY_ORDER'
      ELSE
     'NA'
      END
where DB_OBJECT='Workflow Status';
commit;
--select*from STUS_MSTR
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='REG_STATUS_LOV',
CADSR_COLUMN_NAME
= CASE WHEN OD_COLUMN_NAME in('NCI_STUS','STUS_NM')
      THEN 'REGISTRATION_STATUS'
      WHEN OD_COLUMN_NAME='STUS_DESC'
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='NCI_CMNTS'
      THEN 'COMMENTS'
      WHEN OD_COLUMN_NAME='NCI_DISP_ORDR'
      THEN 'DISPLAY_ORDER'
      ELSE
     'NA'
      END
where DB_OBJECT='Registration Status';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='REG_STATUS_LOV',
CADSR_COLUMN_NAME
= CASE WHEN OD_COLUMN_NAME ='RAI'
      THEN 'RAI'
      WHEN OD_COLUMN_NAME='ORG_NM'
      THEN 'NAME'
      WHEN OD_COLUMN_NAME='RA_IND'
      THEN 'RA_IND'
      WHEN OD_COLUMN_NAME='MAIL_ADDR'
      THEN 'MAIL_ADDRESS'
      ELSE
     'NA'
      END
where DB_OBJECT='Organization';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='ADDR_TYPES_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'ALT_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Address Type';
commit; 

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CSI_TYPES_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'CSITL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='CSI Type';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CS_TYPES_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'CSTL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Classification Scheme Type';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='COMM_TYPES_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'ALT_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Communication Type';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='DEFINITION_TYPES_LOV_EXT',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'DEFL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Definition Type';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='DESIGNATION_TYPES_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'DETL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Designation Type';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='COMPLEX_REP_TYPE_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME in('OBJ_KEY_DESC','NCI_CD')
      THEN 'CRTL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Derivation Type';
commit;


UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='SOURCES_EXT',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME in('OBJ_KEY_DESC','NCI_CD')
      THEN 'SRC_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'        
      ELSE
     'NA'
      END
where DB_OBJECT='Origin';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='PROGRAM_AREAS_LOV',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME in('OBJ_KEY_DESC','NCI_CD')
      THEN 'PAL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Program Area';
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='PROTOCOLS_EXT',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME in('OBJ_KEY_DESC','NCI_CD')
      THEN 'TYPE'         
      ELSE
     'NA'
      END
where DB_OBJECT='Protocol Type';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CONTACT_ADDRESSES',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='RNK_ORD'
      THEN 'RANK_ORDER'
       WHEN OD_COLUMN_NAME ='CNTRY'
      THEN 'COUNTRY'
       WHEN OD_COLUMN_NAME ='POSTAL_CD'
      THEN 'POSTAL_CODE'
     ELSE
      OD_COLUMN_NAME
      END
where DB_OBJECT='Addresses';
commit; 

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='COMPLEX_DE_RELATIONSHIPS',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='DISP_ORD'
      THEN 'DISPLAY_ORDER'
      ELSE
      'N/A'
      END
where DB_OBJECT='COMPLEX DE Relationship';
commit; 
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CS_ITEMS',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='DESCRIPTION'
      THEN 'CSI_DESC_TXT'
      WHEN OD_COLUMN_NAME ='COMMENTS'
      THEN 'CSI_DESC_TXT'
      WHEN OD_COLUMN_NAME ='DELETED_IND'
      THEN 'CSI_DESC_TXT'
      ELSE
      'N/A'
      END
where DB_OBJECT='CSI';
commit; 

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CLASSIFICATION_SCHEMES',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='NCI_LABEL_TYP_FLG'
      THEN 'LABEL_TYPE_FLAG'
      ELSE
      'N/A'
      END
where DB_OBJECT='Classification Scheme';
commit; 

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CONTACT_COMMS',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='CYB_ADDR'
      THEN 'CYBER_ADDRESSG'
       WHEN OD_COLUMN_NAME ='RNK_ORD'
      THEN 'RANK_ORDER'
      ELSE
      'N/A'
      END
where DB_OBJECT='Communications';
commit; 
 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CONCEPTUAL_DOMAINS',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='DIMNSNLTY'
      THEN 'DIMENSIONALITY'
            ELSE
      'N/A'
      END
where DB_OBJECT='Conceptual Domain';
commit;      
 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CONCEPTS_EXT', CADSR_COLUMN_NAME='N/A' where DB_OBJECT='Concept';
 commit;
 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='CONTEXTS', CADSR_COLUMN_NAME='N/A' where DB_OBJECT='Context';
commit;

 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='REFERENCE_DOCUMENTS',CADSR_COLUMN_NAME='DOC_TEXT'
where OD_COLUMN_NAME ='PREF_QUEST_TXT' and DB_OBJECT='DE';
commit;
 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='COMPLEX_DATA_ELEMENTS',
CADSR_COLUMN_NAME= CASE
 WHEN OD_COLUMN_NAME ='CONCAT_CHAR'
THEN  'CONCAT_CHAR'
WHEN OD_COLUMN_NAME ='DERV_MTHD'
THEN 'METHODS'
WHEN OD_COLUMN_NAME ='DERV_RUL'
THEN 'RULE'
ELSE
'N/A'
END
where DB_OBJECT='DE' and CADSR_COLUMN_NAME is NULL;
commit;

 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='DOCUMENT_TYPES_LOV',
CADSR_COLUMN_NAME= CASE
   WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'DCTL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='OBJ_KEY_CMNTS'
      THEN 'COMMENTS'     
      ELSE
     'NA'
      END
where DB_OBJECT='Document Type' and CADSR_COLUMN_NAME is NULL;
commit;

 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='QC_DISPLAY_LOV_EXT',
CADSR_COLUMN_NAME= CASE
   WHEN OD_COLUMN_NAME ='OBJ_KEY_DESC'
      THEN 'QCDL_NAME'
      WHEN OD_COLUMN_NAME='OBJ_KEY_DEF'     
      THEN 'DESCRIPTION'
      WHEN OD_COLUMN_NAME='DISP_ORD
'
      THEN 'DISPLAY_ORDER'     
      ELSE
     'NA'
      END
where DB_OBJECT='Form Category' and CADSR_COLUMN_NAME is NULL;
commit;


UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='DATA_ELEMENT_CONCEPTS',
CADSR_COLUMN_NAME
= CASE
      WHEN OD_COLUMN_NAME ='OBJ_CLS_QUAL'
      THEN 'OBJ_CLASS_QUALIFIER'
      WHEN OD_COLUMN_NAME ='PROP_QUAL'
      THEN 'PROPERTY_QUALIFIER'
            ELSE
      'N/A'
      END
where OD_TABLE_NAME='DE_CONC';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='DATATYPES_LOV',
CADSR_COLUMN_NAME
= CASE
WHEN OD_COLUMN_NAME ='DTTYPE_ANNTTN'  
THEN 'ANNOTATION'
WHEN OD_COLUMN_NAME ='DTTYPE_SCHM_REF' 
THEN 'SCHEME_REFERENCE'
 WHEN OD_COLUMN_NAME ='DTTYPE_DESC'
 THEN 'DESCRIPTION'
 WHEN OD_COLUMN_NAME ='DTTYPE_NM'
THEN 'DTL_NAME'
 WHEN OD_COLUMN_NAME ='NCI_CD'
 THEN 'DTL_NAME'
 WHEN OD_COLUMN_NAME ='NCI_DTTYPE_CMNTS'
 THEN 'COMMENTS'
 WHEN OD_COLUMN_NAME ='NCI_DTTYPE_MAP'
      THEN 'DTL_NAME'
            ELSE
      'N/A'
      END
where OD_TABLE_NAME='DATA_TYP';
commit;
UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='QUEST_CONTENTS_EXT',
CADSR_COLUMN_NAME= 'PREFERRED_DEFINITION'
where OD_TABLE_NAME='NCI_FORM' and OD_COLUMN_NAME in ('FTR_INSTR','HDR_INSTR');
commit;

 UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='QUEST_CONTENTS_EXT',
CADSR_COLUMN_NAME= CASE
      WHEN OD_COLUMN_NAME='DISP_ORD'     
      THEN 'DISPLAY_ORDER'   
      WHEN OD_COLUMN_NAME='INSTR'
      THEN 'PREFERRED_DEFINITION'   
      WHEN OD_COLUMN_NAME='REP_NO'  
      THEN'REPEAT_NO'  
      ELSE
     'NA'
      END
where DB_OBJECT='Module, Module Instruction' and CADSR_COLUMN_NAME is NULL;
commit;


UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='QUEST_CONTENTS_EXT',
CADSR_COLUMN_NAME= CASE
   
      WHEN OD_COLUMN_NAME='DISP_ORD'     
      THEN 'DISPLAY_ORDER'   
      WHEN OD_COLUMN_NAME='INSTR'
      THEN 'PREFERRED_DEFINITION'   
      WHEN OD_COLUMN_NAME='REP_NO'  
      THEN'REPEAT_NO'  
      WHEN OD_COLUMN_NAME='DEFLT_VAL'
      THEN 'DEFAULT_VALUE'
      WHEN OD_COLUMN_NAME='ITEM_LONG_NM'
      THEN 'LONG_NAME'
      WHEN OD_COLUMN_NAME in('PREF_NM_MIGRATED','ITEM_NM')
      THEN 'PREFERRED_NAME' 
      ELSE
     'NA'
      END
where DB_OBJECT='Question, Question Instruction' and CADSR_COLUMN_NAME is NULL;
commit;


-- 	ONEDATA_WA	NCI_ADMIN_ITEM_REL_ALT_KEY	REQ_IND

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='VALID_VALUES_ATT_EXT',CADSR_OWNER='SBREXT',
CADSR_COLUMN_NAME= CASE     
 WHEN OD_COLUMN_NAME='DESC_TXT'
 THEN'DESCRIPTION_TEXT'
 WHEN OD_COLUMN_NAME='MEAN_TXT'
 THEN 'MEANING_TEXT'
      END
where OD_TABLE_NAME ='NCI_QUEST_VALID_VALUE' and OD_COLUMN_NAME in('DESC_TXT','MEAN_TXT');
commit;

UPDATE OD_CADSR_TAB_28_INSERT set CADSR_TABLE_NAME='QUEST_CONTENTS_EXT',
CADSR_COLUMN_NAME= CASE
WHEN OD_COLUMN_NAME='DISP_ORD'     
THEN 'DISPLAY_ORDER'   
WHEN OD_COLUMN_NAME='INSTR'
THEN 'PREFERRED_DEFINITION' 
WHEN OD_COLUMN_NAME='VALUE'
THEN 'LONG_NAME'
WHEN OD_COLUMN_NAME='VM_DEF'
THEN 'PREFERRED_DEFINITION'
WHEN OD_COLUMN_NAME='VM_NM'
THEN 'PREFERRED_NAME'
WHEN OD_COLUMN_NAME='REP_NO'  
THEN'REPEAT_NO'  
WHEN OD_COLUMN_NAME='DISP_ORD'     
THEN 'DISPLAY_ORDER'      
ELSE
'NA'
END
where OD_TABLE_NAME ='NCI_QUEST_VALID_VALUE' and CADSR_COLUMN_NAME is NULL;
commit;



--select*from OD_CADSR_TAB_28_INSERT where OD_TABLE_NAME='ADMIN_ITEM';
--desc sbr.ADMINISTERED_COMPONENTS;
--select*from CONTACT_ADDRESSES
--
--desc ORIGIN
       
--FOR c_rec IN c_od LOOP -- for all data elements which match
--
-- IF c_rec.DB_OBJECTS='Administered Items' THEN
-- UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='ADMINISTERED_COMPONENTS', CADSR_OWNER='SBR';
-- commit;
-- elsif c_rec.DB_OBJECTS='DE' THEN
--  UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='DATA_ELEMENTS', CADSR_OWNER='SBR';
-- commit;
--  elsif c_rec.DB_OBJECTS='DE Concept' THEN
--  UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='DATA_ELEMENT_CONCEPTS', CADSR_OWNER='SBR';
-- commit;
--  elsif c_rec.DB_OBJECTS='Conceptual Domain' THEN
--  UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='CONCEPTUAL_DOMAINS', CADSR_OWNER='SBR';
-- commit;
--  elsif c_rec.DB_OBJECTS='DE Concept' THEN
--  UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='DATA_ELEMENT_CONCEPTS', CADSR_OWNER='SBR';
-- commit;
--  elsif c_rec.DB_OBJECTS='DE Concept' THEN
--  UPDATE OD_CADSR_TAB_28_INSERT
-- set CADSR_TABLE_NAME='DATA_ELEMENT_CONCEPTS', CADSR_OWNER='SBR';
-- commit;
--    END IF;
-- END LOOP;
-- commit;
 EXCEPTION
    WHEN OTHERS THEN
   errmsg := SQLERRM;
         dbms_output.put_line('errmsg  - '||errmsg);
        insert into CDE_19_REPORTS_ERR_LOG VALUES (l_file_name,  errmsg, sysdate);
 commit;

END ;
/
