create or replace TRIGGER TR_NCI_DLOAD_HDR_TS
  BEFORE  UPDATE  OF DLOAD_TYP_ID,DLOAD_FMT_ID,DLOAD_HDR_NM,EMAIL_ADDR,CMNT_TXT
  on NCI_DLOAD_HDR
  for each row
BEGIN
if (
  :new.LST_UPD_DT := SYSDATE;
END;
/

