alter table nci_mec_map add (CTL_VAL_MSG varchar2(4000));

alter table nci_stg_mec_val_map add (UPD_TYP char(1));

alter table obj_key add (min_cnt integer, max_cnt integer);

--jira 3936
CREATE TABLE NCI_DLOAD_MDL_MAP_DTL_NEW
   (	"HDR_ID" NUMBER NOT NULL ENABLE, 
	"FMT_NM" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_ID" NUMBER, 
	"VER_NR" NUMBER(4,2), 
	"DT_LAST_MODIFIED" DATE, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RETAIN_IND" NUMBER(1,0) DEFAULT 0, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	"MM_ID_VER" VARCHAR2(81 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("HDR_ID", "MM_ID_VER")
     );

  CREATE TABLE NCI_DLOAD_MDL_MAP_SEL
   (	"HDR_ID" NUMBER NOT NULL ENABLE, 
	"FMT_NM" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"VER_NR" NUMBER(4,2) DEFAULT 1 NOT NULL ENABLE, 
	"ITEM_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NM_CURATED" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"MDL_MAP_SEL" NUMBER(1,0) DEFAULT 0, 
	"DT_LAST_MODIFIED" DATE, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RETAIN_IND" NUMBER(1,0) DEFAULT 0, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID", "ITEM_ID", "VER_NR")
);
CREATE TABLE NCI_DLOAD_MDL_MAP_SPEC
   (	"HDR_ID" NUMBER NOT NULL ENABLE, 
	"FMT_NM" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"DT_LAST_MODIFIED" DATE, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RETAIN_IND" NUMBER(1,0) DEFAULT 0, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("HDR_ID")
);


  CREATE OR REPLACE FORCE EDITIONABLE VIEW VW_MDL_MAP_LIST_DLOAD_NEW ("MM_ID", "MM_VER_NR", "MM_NM", "MM_CURATED_NM", "MM_ID_VER", "CREAT_DT", "CREAT_USR_ID", "LST_UPD_DT", "LST_UPD_USR_ID", "FLD_DELETE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select  m.ITEM_ID "MM_ID",
         m.ver_nr "MM_VER_NR",
	m.ITEM_NM "MM_NM",
 m.ITEM_NM_CURATED "MM_CURATED_NM",
 m.ITEM_ID || 'v' || m.ver_nr "MM_ID_VER",
	   m.creat_dt "CREAT_DT",
	  m.creat_usr_id "CREAT_USR_ID",	  
	  m.lst_upd_dt "LST_UPD_DT",
	  m.lst_upd_usr_id "LST_UPD_USR_ID",
      0 "FLD_DELETE"
     from admin_item s,  admin_item t, nci_mdl_map mm,
admin_item m, nci_org org, nci_prsn p
	where m.item_id = mm.item_id and m.ver_nr = mm.ver_nr and mm.SRC_MDL_ITEM_ID= s.item_id and mm.TGT_MDL_ITEM_ID= t.item_id 
and mm.SRC_MDL_VER_NR = s.ver_nr and mm.TGT_MDL_VER_NR = t.ver_nr 
 and mm.PROV_ORG_ID = org.entty_id (+)
and mm.prov_cntct_id  = p.entty_ID (+);

--jira 4011
alter table nci_ds_hdr add SYS_MSG varchar2(2000);

--jira 4025
drop materialized view mvw_val_mean;

CREATE OR REPLACE VIEW MVW_VAL_MEAN ("DATA_ID_STR", "ITEM_ID", "VER_NR", "CLSFCTN_SCHM_ID", "ITEM_DESC", "CNTXT_ITEM_ID", "CNTXT_VER_NR", "ITEM_LONG_NM", "ITEM_NM", "ADMIN_NOTES", "CHNG_DESC_TXT", "CREATION_DT", "EFF_DT", "ORIGIN", "UNRSLVD_ISSUE", "UNTL_DT", "CLSFCTN_SCHM_VER_NR", "ADMIN_ITEM_TYP_ID", "CURRNT_VER_IND", "ADMIN_STUS_ID", "REGSTR_STUS_ID", "REGISTRR_CNTCT_ID", "SUBMT_CNTCT_ID", "STEWRD_CNTCT_ID", "SUBMT_ORG_ID", "STEWRD_ORG_ID", "CREAT_DT", "CREAT_USR_ID", "LST_UPD_USR_ID", "FLD_DELETE", "LST_DEL_DT", "S2P_TRN_DT", "LST_UPD_DT", "LEGCY_CD", "CASE_FILE_ID", "REGSTR_AUTH_ID", "BTCH_NR", "ALT_KEY", "ABAC_ATTR", "NCI_IDSEQ", "ADMIN_STUS_NM_DN", "CNTXT_NM_DN", "REGSTR_STUS_NM_DN", "ORIGIN_ID", "ORIGIN_ID_DN", "DEF_SRC", "CREAT_USR_ID_X", "LST_UPD_USR_ID_X", "ITEM_NM_CURATED", "ITEM_NM_ID_VER", "ITEM_RPT_URL", "ITEM_DEEP_LINK", "RVWR_CMNTS", "MTCH_TERM_ADV", "MTCH_TERM")

  AS SELECT "ADMIN_ITEM"."DATA_ID_STR" "DATA_ID_STR","ADMIN_ITEM"."ITEM_ID" "ITEM_ID","ADMIN_ITEM"."VER_NR" "VER_NR","ADMIN_ITEM"."CLSFCTN_SCHM_ID" "CLSFCTN_SCHM_ID","ADMIN_ITEM"."ITEM_DESC" "ITEM_DESC","ADMIN_ITEM"."CNTXT_ITEM_ID" "CNTXT_ITEM_ID","ADMIN_ITEM"."CNTXT_VER_NR" "CNTXT_VER_NR","ADMIN_ITEM"."ITEM_LONG_NM" "ITEM_LONG_NM","ADMIN_ITEM"."ITEM_NM" "ITEM_NM","ADMIN_ITEM"."ADMIN_NOTES" "ADMIN_NOTES","ADMIN_ITEM"."CHNG_DESC_TXT" "CHNG_DESC_TXT","ADMIN_ITEM"."CREATION_DT" "CREATION_DT","ADMIN_ITEM"."EFF_DT" "EFF_DT","ADMIN_ITEM"."ORIGIN" "ORIGIN","ADMIN_ITEM"."UNRSLVD_ISSUE" "UNRSLVD_ISSUE","ADMIN_ITEM"."UNTL_DT" "UNTL_DT","ADMIN_ITEM"."CLSFCTN_SCHM_VER_NR" "CLSFCTN_SCHM_VER_NR","ADMIN_ITEM"."ADMIN_ITEM_TYP_ID" "ADMIN_ITEM_TYP_ID","ADMIN_ITEM"."CURRNT_VER_IND" "CURRNT_VER_IND","ADMIN_ITEM"."ADMIN_STUS_ID" "ADMIN_STUS_ID","ADMIN_ITEM"."REGSTR_STUS_ID" "REGSTR_STUS_ID","ADMIN_ITEM"."REGISTRR_CNTCT_ID" "REGISTRR_CNTCT_ID","ADMIN_ITEM"."SUBMT_CNTCT_ID" "SUBMT_CNTCT_ID","ADMIN_ITEM"."STEWRD_CNTCT_ID" "STEWRD_CNTCT_ID","ADMIN_ITEM"."SUBMT_ORG_ID" "SUBMT_ORG_ID","ADMIN_ITEM"."STEWRD_ORG_ID" "STEWRD_ORG_ID","ADMIN_ITEM"."CREAT_DT" "CREAT_DT","ADMIN_ITEM"."CREAT_USR_ID" "CREAT_USR_ID","ADMIN_ITEM"."LST_UPD_USR_ID" "LST_UPD_USR_ID","ADMIN_ITEM"."FLD_DELETE" "FLD_DELETE","ADMIN_ITEM"."LST_DEL_DT" "LST_DEL_DT","ADMIN_ITEM"."S2P_TRN_DT" "S2P_TRN_DT","ADMIN_ITEM"."LST_UPD_DT" "LST_UPD_DT","ADMIN_ITEM"."LEGCY_CD" "LEGCY_CD","ADMIN_ITEM"."CASE_FILE_ID" "CASE_FILE_ID","ADMIN_ITEM"."REGSTR_AUTH_ID" "REGSTR_AUTH_ID","ADMIN_ITEM"."BTCH_NR" "BTCH_NR","ADMIN_ITEM"."ALT_KEY" "ALT_KEY","ADMIN_ITEM"."ABAC_ATTR" "ABAC_ATTR","ADMIN_ITEM"."NCI_IDSEQ" "NCI_IDSEQ","ADMIN_ITEM"."ADMIN_STUS_NM_DN" "ADMIN_STUS_NM_DN","ADMIN_ITEM"."CNTXT_NM_DN" "CNTXT_NM_DN","ADMIN_ITEM"."REGSTR_STUS_NM_DN" "REGSTR_STUS_NM_DN","ADMIN_ITEM"."ORIGIN_ID" "ORIGIN_ID","ADMIN_ITEM"."ORIGIN_ID_DN" "ORIGIN_ID_DN","ADMIN_ITEM"."DEF_SRC" "DEF_SRC","ADMIN_ITEM"."CREAT_USR_ID_X" "CREAT_USR_ID_X","ADMIN_ITEM"."LST_UPD_USR_ID_X" "LST_UPD_USR_ID_X","ADMIN_ITEM"."ITEM_NM_CURATED" "ITEM_NM_CURATED","ADMIN_ITEM"."ITEM_NM_ID_VER" "ITEM_NM_ID_VER","ADMIN_ITEM"."ITEM_RPT_URL" "ITEM_RPT_URL","ADMIN_ITEM"."ITEM_DEEP_LINK" "ITEM_DEEP_LINK","ADMIN_ITEM"."RVWR_CMNTS" "RVWR_CMNTS","ADMIN_ITEM"."MTCH_TERM_ADV" "MTCH_TERM_ADV","ADMIN_ITEM"."MTCH_TERM" "MTCH_TERM" FROM "ADMIN_ITEM" "ADMIN_ITEM" WHERE "ADMIN_ITEM"."ADMIN_ITEM_TYP_ID"=53;

