
  CREATE TABLE NCI_STG_PV_VM_BULK 
   (	"STG_AI_ID" NUMBER NOT NULL ENABLE, 
	"CTL_VAL_MSG" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CNCPT_CONCAT_STR_1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CNCPT_CONCAT_STR_2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONC_DOM_ITEM_ID" NUMBER, 
	"CONC_DOM_VER_NR" NUMBER(4,2), 
    	 VAL_DOM_ITEM_ID  number,
         VAL_DOM_VER_NR number(4,2),
	"CNTXT_ITEM_ID" NUMBER, 
	"CNTXT_VER_NR" NUMBER(4,2), 
	"ADMIN_STUS_ID" NUMBER(*,0), 
	"REGSTR_STUS_ID" NUMBER(*,0), 
	"CNCPT_1_ITEM_ID_1" NUMBER, 
	"CNCPT_1_VER_NR_1" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_2" NUMBER, 
	"CNCPT_1_VER_NR_2" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_3" NUMBER, 
	"CNCPT_1_VER_NR_3" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_4" NUMBER, 
	"CNCPT_1_VER_NR_4" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_5" NUMBER, 
	"CNCPT_1_VER_NR_5" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_6" NUMBER, 
	"CNCPT_1_VER_NR_6" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_7" NUMBER, 
	"CNCPT_1_VER_NR_7" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_8" NUMBER, 
	"CNCPT_1_VER_NR_8" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_9" NUMBER, 
	"CNCPT_1_VER_NR_9" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_10" NUMBER, 
	"CNCPT_1_VER_NR_10" NUMBER(4,2), 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	"GEN_STR" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_ID" NUMBER, 
	"ITEM_1_VER_NR" NUMBER(4,2), 
	"ITEM_2_ID" NUMBER, 
	"ITEM_2_VER_NR" NUMBER(4,2), 
	"ITEM_1_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_LONG_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_DEF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_2_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_2_LONG_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_2_DEF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DTTYPE_ID" NUMBER, 
	"VAL_DOM_MAX_CHAR" NUMBER, 
	"VAL_DOM_TYP_ID" NUMBER, 
	"UOM_ID" NUMBER, 
	"VD_CONC_DOM_VER_NR" NUMBER(4,2), 
	"VD_CONC_DOM_ITEM_ID" NUMBER, 
	"REP_CLS_VER_NR" NUMBER(4,2), 
	"REP_CLS_ITEM_ID" NUMBER, 
	"VAL_DOM_MIN_CHAR" NUMBER, 
	"VAL_DOM_FMT_ID" NUMBER, 
	"CHAR_SET_ID" NUMBER, 
	"VAL_DOM_HIGH_VAL_NUM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"VAL_DOM_LOW_VAL_NUM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NCI_DEC_PREC" NUMBER(2,0), 
	"PERM_VAL_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_1" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_2" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_3" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_4" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_5" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_6" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_7" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_8" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_9" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PV_10" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
  "STR_1" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_2" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_3" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_4" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_5" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_6" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_7" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_8" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_9" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STR_10" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"NCI_STD_DTTYPE_ID" NUMBER, 
	"ITEM_LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"BTCH_USR_NM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BTCH_NM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CTL_VAL_STUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("STG_AI_ID"));



  CREATE OR REPLACE  VIEW VW_CLSFCTN_SCHM_ITEM AS
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM,  ADMIN_ITEM.ITEM_DESC,
ADMIN_ITEM.CNTXT_NM_DN, ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, ADMIN_ITEM.CREAT_DT,
ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT,
ADMIN_ITEM.LST_UPD_DT, ADMIN_ITEM.NCI_IDSEQ, CSI.P_ITEM_ID, CSI.P_ITEM_VER_NR, CSI.CS_ITEM_ID, CSI.CS_ITEM_VER_NR
FROM ADMIN_ITEM, NCI_CLSFCTN_SCHM_ITEM csi
       WHERE ADMIN_ITEM_TYP_ID = 51 and ADMIN_ITEM.ITEM_ID = CSI.ITEM_ID and ADMIN_ITEM.VER_NR = CSI.VER_NR;

alter table ADMIN_ITEM modify (EFF_DT date default sysdate);



  CREATE OR REPLACE  VIEW "VW_NCI_USED_BY" ("ITEM_ID", "VER_NR", "CNTXT_ITEM_ID", "CNTXT_VER_NR", "CREAT_DT", "CREAT_USR_ID", "LST_UPD_USR_ID", "FLD_DELETE", "LST_DEL_DE", "S2P_TRN_DT", "LST_UPD_DT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select distinct ITEM_ID, VER_NR , CNTXT_ITEM_ID, CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, 0 FLD_DELETE, sysdate LST_DEL_DE, sysdate S2P_TRN_DT, sysdate LST_UPD_DT
from (
  SELECT distinct DE.ITEM_ID, DE.VER_NR, a.CNTXT_ITEM_ID, a.CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, a.FLD_DELETE, a.LST_DEL_DT, sysdate S2P_TRN_DT, sysdate LST_UPD_DT
       FROM DE, ALT_NMS a
       WHERE DE.ITEM_ID = a.ITEM_ID and DE.VER_NR = a.VER_NR
       and nvl(a.fld_delete,0) = 0
       and nvl(de.fld_delete,0) = 0
      and a.CNTXT_ITEM_ID is not null
union
  SELECT distinct DE.ITEM_ID, DE.VER_NR, a.NCI_CNTXT_ITEM_ID, a.NCI_CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, a.FLD_DELETE, a.LST_DEL_DT, sysdate S2P_TRN_DT, sysdate LST_UPD_DT
       FROM DE, REF a
       WHERE DE.ITEM_ID = a.ITEM_ID and DE.VER_NR = a.VER_NR
       and nvl(a.fld_delete,0) = 0
       and nvl(de.fld_delete,0) = 0
      and a.NCI_CNTXT_ITEM_ID is not null
union
  SELECT distinct DE.C_ITEM_ID, DE.C_ITEM_VER_NR, cs.CNTXT_ITEM_ID, cs.CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, cscsi.FLD_DELETE, cscsi.LST_DEL_DT, sysdate S2P_TRN_DT,
  sysdate LST_UPD_DT
       FROM NCI_ALT_KEY_ADMIN_ITEM_REL de, NCI_ADMIN_ITEM_REL_ALT_KEY cscsi, admin_item cs
       WHERE DE.NCI_PUB_ID = cscsi.NCI_PUB_ID and de.NCI_VER_NR = cscsi.NCI_VER_NR
       and nvl(cscsi.fld_delete,0) = 0
       and nvl(de.fld_delete,0) = 0
       and nvl(cs.fld_delete,0) = 0
       and cscsi.CNTXT_CS_ITEM_ID = cs.item_id and
       cscsi.CNTXT_CS_VER_NR = cs.ver_nr and
       cs.admin_item_typ_id = 9       and cs.CNTXT_ITEM_ID is not null
union
  SELECT distinct quest.C_ITEM_ID, quest.C_ITEM_VER_NR, ai.CNTXT_ITEM_ID, ai.CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, quest.FLD_DELETE, quest.LST_DEL_DT, sysdate S2P_TRN_DT, sysdate LST_UPD_DT
       FROM NCI_ADMIN_ITEM_REL_ALT_KEY quest, ADMIN_ITEM ai, NCI_ADMIN_ITEM_REL rel
       WHERE AI.ITEM_ID = rel.P_ITEM_ID and AI.VER_NR = rel.P_ITEM_VER_NR
       and nvl(ai.fld_delete,0) = 0
       and nvl(rel.fld_delete,0) = 0
       and nvl(quest.fld_delete,0) = 0
       and rel.C_ITEM_ID = quest.P_ITEM_ID
       and rel.C_ITEM_VER_NR = quest.P_ITEM_VER_NR
       and ai.admin_stus_id = 75 -- only for released forms.
union
  SELECT distinct quest.C_ITEM_ID, quest.C_ITEM_VER_NR, cs.CNTXT_ITEM_ID, cs.CNTXT_VER_NR, sysdate CREAT_DT, 'ONEDATA' CREAT_USR_ID, 'ONEDATA' LST_UPD_USR_ID, quest.FLD_DELETE, quest.LST_DEL_DT, sysdate S2P_TRN_DT, sysdate LST_UPD_DT
       FROM NCI_ADMIN_ITEM_REL quest, ADMIN_ITEM cs, NCI_CLSFCTN_SCHM_ITEM csi
       WHERE cs.ITEM_ID = csi.cs_ITEM_ID and cs.VER_NR = csi.CS_ITEM_VER_NR
       and nvl(cs.fld_delete,0) = 0
       and nvl(csi.fld_delete,0) = 0
       and nvl(quest.fld_delete,0) = 0
       and csi.ITEM_ID = quest.P_ITEM_ID
       and cs.VER_NR = quest.P_ITEM_VER_NR
      );



  CREATE OR REPLACE  VIEW VW_NCI_DE_VM_ALT_NMS AS
  SELECT   DE.ITEM_ID  DE_ITEM_ID, 
		DE.VER_NR DE_VER_NR, PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		PV.CREAT_DT, PV.CREAT_USR_ID, PV.LST_UPD_USR_ID, PV.FLD_DELETE, PV.LST_DEL_DT, PV.S2P_TRN_DT, PV.LST_UPD_DT,
         an.NM_DESC,  an.nm_typ_id, an.CNTXT_NM_DN VM_CNTXT_NM_DN  ,
         an.LANG_ID, an.nm_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT
       FROM  DE, PERM_VAL PV, ALT_NMS an, ADMIN_ITEM vm where 
	PV.VAL_DOM_ITEM_ID = DE.VAL_DOM_ITEM_ID and
	PV.VAL_DOM_VER_NR = DE.VAL_DOM_VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
	
	

  CREATE OR REPLACE  VIEW VW_NCI_DE_VM_ALT_DEF AS
  SELECT   DE.ITEM_ID  DE_ITEM_ID, 
		DE.VER_NR DE_VER_NR, PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		PV.CREAT_DT, PV.CREAT_USR_ID, PV.LST_UPD_USR_ID, PV.FLD_DELETE, PV.LST_DEL_DT, PV.S2P_TRN_DT, PV.LST_UPD_DT,
         an.DEF_DESC,  an.NCI_DEF_TYP_ID, 
         an.LANG_ID, an.def_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT,
	 an.CNTXT_ITEM_ID, an.CNTXT_VER_NR
       FROM  DE, PERM_VAL PV, ALT_DEF an, ADMIN_ITEM vm where 
	PV.VAL_DOM_ITEM_ID = DE.VAL_DOM_ITEM_ID and
	PV.VAL_DOM_VER_NR = DE.VAL_DOM_VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;



  CREATE OR REPLACE  VIEW VW_NCI_VD_VM_ALT_NMS AS
  SELECT   PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		PV.CREAT_DT, PV.CREAT_USR_ID, PV.LST_UPD_USR_ID, PV.FLD_DELETE, PV.LST_DEL_DT, PV.S2P_TRN_DT, PV.LST_UPD_DT,
         an.NM_DESC,  an.nm_typ_id, an.CNTXT_NM_DN VM_CNTXT_NM_DN  ,
         an.LANG_ID, an.nm_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT
       FROM   PERM_VAL PV, ALT_NMS an, ADMIN_ITEM vm where 
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
	
	

  CREATE OR REPLACE  VIEW VW_NCI_VD_VM_ALT_DEF AS
  SELECT  PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		PV.CREAT_DT, PV.CREAT_USR_ID, PV.LST_UPD_USR_ID, PV.FLD_DELETE, PV.LST_DEL_DT, PV.S2P_TRN_DT, PV.LST_UPD_DT,
         an.DEF_DESC,  an.NCI_DEF_TYP_ID, 
         an.LANG_ID, an.def_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT,
	 an.CNTXT_ITEM_ID, an.CNTXT_VER_NR
       FROM   PERM_VAL PV, ALT_DEF an, ADMIN_ITEM vm where 
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
	
  
  CREATE OR REPLACE  VIEW VW_NCI_MODULE_QUEST  AS
  select  rel.p_item_id frm_item_id, rel.p_item_ver_nr frm_ver_nr,
air.p_item_id mod_item_id, air.p_item_ver_nr mod_ver_nr,
 air.c_item_id de_item_id, air.c_item_ver_nr de_ver_nr, air.disp_ord,
 air.nci_pub_id,air.nci_ver_nr, 
de.CNTXT_NM_DN,
air.CREAT_DT, air.CREAT_USR_ID, air.LST_UPD_USR_ID, air.FLD_DELETE, air.LST_DEL_DT, air.S2P_TRN_DT, air.LST_UPD_DT, air.item_long_nm QUEST_LONG_TXT, air.item_nm QUEST_TXT, 63 REL_TYP_ID
from  nci_admin_item_rel_alt_key air,nci_admin_item_rel rel,
 admin_item de
where  air.rel_typ_id = 63
and air.c_item_id = de.item_id
and air.c_item_ver_nr = de.ver_nr
and air.p_item_id = rel.c_item_id
and air.p_item_ver_nr = rel.c_item_ver_nr
and rel.rel_typ_id in (61,62);

CREATE OR REPLACE FORCE VIEW VW_NCI_DE_HORT
(
    ITEM_ID,
    VER_NR,
    ITEM_NM,
    ITEM_LONG_NM,
    ITEM_DESC,
    CNTXT_NM_DN, 
    ORIGIN_ID,
    ORIGIN,   
    ORIGIN_ID_DN,
    UNTL_DT,
    CURRNT_VER_IND,
    REGISTRR_CNTCT_ID,
    SUBMT_CNTCT_ID,
    STEWRD_CNTCT_ID,
    SUBMT_ORG_ID,
    STEWRD_ORG_ID,
    REGSTR_AUTH_ID,
    DE_PREC,
    DE_CONC_ITEM_ID,
    DE_CONC_VER_NR,
    VAL_DOM_VER_NR,
    VAL_DOM_ITEM_ID,
    REP_CLS_VER_NR,
    REP_CLS_ITEM_ID,
    DERV_DE_IND,
    DERV_MTHD,
    DERV_RUL,
    DERV_TYP_ID,
    CONCAT_CHAR,
    CREAT_USR_ID,
    LST_UPD_USR_ID,
    FLD_DELETE,
    LST_DEL_DT,
    S2P_TRN_DT,
    LST_UPD_DT,
    CREAT_DT,
    CREAT_USR_ID_API,
    LST_UPD_USR_ID_API,
    CREAT_DT_API,
    LST_UPD_DT_API,
    CONC_DOM_VER_NR,
    CONC_DOM_ITEM_ID,
    NON_ENUM_VAL_DOM_DESC,
    UOM_ID,
    VAL_DOM_TYP_ID,
    VAL_DOM_MIN_CHAR,
    VAL_DOM_MAX_CHAR,
    VAL_DOM_HIGH_VAL_NUM,
    VAL_DOM_LOW_VAL_NUM,
    VAL_DOM_FMT_ID,
    CHAR_SET_ID,
    VALUE_DOM_CREAT_DT,
    VALUE_DOM_USR_ID,
    VALUE_DOM_LST_UPD_USR_ID,
    VALUE_DOM_LST_UPD_DT,
    VALUE_DOM_ITEM_NM,
    VALUE_DOM_ITEM_LONG_NM,
    VALUE_DOM_ITEM_DESC,
    VALUE_DOM_CNTXT_NM,
    VALUE_DOM_CURRNT_VER_IND,
    VALUE_DOM_REGSTR_STUS_NM,
    VALUE_DOM_ADMIN_STUS_NM,
    NCI_STD_DTTYPE_ID,
    DTTYPE_ID,
    DEC_ITEM_NM,
    DEC_ITEM_LONG_NM,
    DEC_ITEM_DESC,
    DEC_CNTXT_NM,
    DEC_CURRNT_VER_IND,
    DEC_REGSTR_STUS_NM,
    DEC_ADMIN_STUS_NM,
    DEC_CREAT_DT,
    DEC_USR_ID,
    DEC_LST_UPD_USR_ID,
    DEC_LST_UPD_DT,
    OBJ_CLS_ITEM_ID,
    OBJ_CLS_VER_NR,
    OBJ_CLS_ITEM_NM,
    OBJ_CLS_ITEM_LONG_NM,
    PROP_ITEM_NM,
    PROP_ITEM_LONG_NM,
    PROP_ITEM_ID,
    PROP_VER_NR,
    DEC_CD_ITEM_ID,
    DEC_CD_VER_NR,
    DEC_CD_ITEM_NM,
    DEC_CD_ITEM_LONG_NM,
    DEC_CD_ITEM_DESC,
    DEC_CD_CNTXT_NM,
    DEC_CD_CURRNT_VER_IND,
    DEC_CD_REGSTR_STUS_NM,
    DEC_CD_ADMIN_STUS_NM,
    CD_ITEM_NM,
    CD_ITEM_LONG_NM,
    CD_ITEM_DESC,
    CD_CNTXT_NM,
    CD_CURRNT_VER_IND,
    CD_REGSTR_STUS_NM,
    CD_ADMIN_STUS_NM,
    ADMIN_ITEM_TYP_ID,
    CNTXT_AGG,
    LST_UPD_CHG_DAYS
)
BEQUEATH DEFINER
AS
    SELECT ADMIN_ITEM.ITEM_ID                ITEM_ID,
           ADMIN_ITEM.VER_NR,
           ADMIN_ITEM.ITEM_NM,
           ADMIN_ITEM.ITEM_LONG_NM,
           ADMIN_ITEM.ITEM_DESC,
           ADMIN_ITEM.CNTXT_NM_DN,
           ADMIN_ITEM.ORIGIN_ID,
           ADMIN_ITEM.ORIGIN,
           ADMIN_ITEM.ORIGIN_ID_DN,
           ADMIN_ITEM.UNTL_DT,
           ADMIN_ITEM.CURRNT_VER_IND,
           ADMIN_ITEM.REGISTRR_CNTCT_ID,
           ADMIN_ITEM.SUBMT_CNTCT_ID,
           ADMIN_ITEM.STEWRD_CNTCT_ID,
           ADMIN_ITEM.SUBMT_ORG_ID,
           ADMIN_ITEM.STEWRD_ORG_ID,
           ADMIN_ITEM.REGSTR_AUTH_ID,
           DE.DE_PREC,
           DE.DE_CONC_ITEM_ID,
           DE.DE_CONC_VER_NR,
           DE.VAL_DOM_VER_NR,
           DE.VAL_DOM_ITEM_ID,
           DE.REP_CLS_VER_NR,
           DE.REP_CLS_ITEM_ID,
           DE.DERV_DE_IND,
           DE.DERV_MTHD,
           DE.DERV_RUL,
           DE.DERV_TYP_ID,
           DE.CONCAT_CHAR,
           DE.CREAT_USR_ID,
           DE.LST_UPD_USR_ID,
           DE.FLD_DELETE,
           DE.LST_DEL_DT,
           DE.S2P_TRN_DT,
           DE.LST_UPD_DT,
           DE.CREAT_DT,
           DE.CREAT_USR_ID                   CREAT_USR_ID_API,
           DE.LST_UPD_USR_ID                 LST_UPD_USR_ID_API,
           DE.CREAT_DT                       CREAT_DT_API,
           DE.LST_UPD_DT                     LST_UPD_DT_API,
           VALUE_DOM.CONC_DOM_VER_NR,
           VALUE_DOM.CONC_DOM_ITEM_ID,
           VALUE_DOM.NON_ENUM_VAL_DOM_DESC,
           VALUE_DOM.UOM_ID,
           VALUE_DOM.VAL_DOM_TYP_ID          VAL_DOM_TYP_ID,
           VALUE_DOM.VAL_DOM_MIN_CHAR,
           VALUE_DOM.VAL_DOM_MAX_CHAR,
           VALUE_DOM.VAL_DOM_HIGH_VAL_NUM,
           VALUE_DOM.VAL_DOM_LOW_VAL_NUM,
           VALUE_DOM.VAL_DOM_FMT_ID,
           VALUE_DOM.CHAR_SET_ID,
           VALUE_DOM.CREAT_DT                VALUE_DOM_CREAT_DT,
           VALUE_DOM.CREAT_USR_ID            VALUE_DOM_USR_ID,
           VALUE_DOM.LST_UPD_USR_ID          VALUE_DOM_LST_UPD_USR_ID,
           VALUE_DOM.LST_UPD_DT              VALUE_DOM_LST_UPD_DT,
           VALUE_DOM_AI.ITEM_NM              VALUE_DOM_ITEM_NM,
           VALUE_DOM_AI.ITEM_LONG_NM         VALUE_DOM_ITEM_LONG_NM,
           VALUE_DOM_AI.ITEM_DESC            VALUE_DOM_ITEM_DESC,
           VALUE_DOM_AI.CNTXT_NM_DN          VALUE_DOM_CNTXT_NM,
           VALUE_DOM_AI.CURRNT_VER_IND       VALUE_DOM_CURRNT_VER_IND,
           VALUE_DOM_AI.REGSTR_STUS_NM_DN    VALUE_DOM_REGSTR_STUS_NM,
           VALUE_DOM_AI.ADMIN_STUS_NM_DN     VALUE_DOM_ADMIN_STUS_NM,
           VALUE_DOM.NCI_STD_DTTYPE_ID,
           VALUE_DOM.DTTYPE_ID,
           DEC_AI.ITEM_NM                    DEC_ITEM_NM,
           DEC_AI.ITEM_LONG_NM               DEC_ITEM_LONG_NM,
           DEC_AI.ITEM_DESC                  DEC_ITEM_DESC,
           DEC_AI.CNTXT_NM_DN                DEC_CNTXT_NM,
           DEC_AI.CURRNT_VER_IND             DEC_CURRNT_VER_IND,
           DEC_AI.REGSTR_STUS_NM_DN          DEC_REGSTR_STUS_NM,
           DEC_AI.ADMIN_STUS_NM_DN           DEC_ADMIN_STUS_NM,
           DEC_AI.CREAT_DT                   DEC_CREAT_DT,
           DEC_AI.CREAT_USR_ID               DEC_USR_ID,
           DEC_AI.LST_UPD_USR_ID             DEC_LST_UPD_USR_ID,
           DEC_AI.LST_UPD_DT                 DEC_LST_UPD_DT,
           DE_CONC.OBJ_CLS_ITEM_ID,
           DE_CONC.OBJ_CLS_VER_NR,
           OC.ITEM_NM                        OBJ_CLS_ITEM_NM,
           OC.ITEM_LONG_NM                   OBJ_CLS_ITEM_LONG_NM,
           PROP.ITEM_NM                      PROP_ITEM_NM,
           PROP.ITEM_LONG_NM                 PROP_ITEM_LONG_NM,
           DE_CONC.PROP_ITEM_ID,
           DE_CONC.PROP_VER_NR,
           DE_CONC.CONC_DOM_ITEM_ID          DEC_CD_ITEM_ID,
           DE_CONC.CONC_DOM_VER_NR           DEC_CD_VER_NR,
           DEC_CD.ITEM_NM                    DEC_CD_ITEM_NM,
           DEC_CD.ITEM_LONG_NM               DEC_CD_ITEM_LONG_NM,
           DEC_CD.ITEM_DESC                  DEC_CD_ITEM_DESC,
           DEC_CD.CNTXT_NM_DN                DEC_CD_CNTXT_NM,
           DEC_CD.CURRNT_VER_IND             DEC_CD_CURRNT_VER_IND,
           DEC_CD.REGSTR_STUS_NM_DN          DEC_CD_REGSTR_STUS_NM,
           DEC_CD.ADMIN_STUS_NM_DN           DEC_CD_ADMIN_STUS_NM,
           CD_AI.ITEM_NM                     CD_ITEM_NM,
           CD_AI.ITEM_LONG_NM                CD_ITEM_LONG_NM,
           CD_AI.ITEM_DESC                   CD_ITEM_DESC,
           CD_AI.CNTXT_NM_DN                 CD_CNTXT_NM,
           CD_AI.CURRNT_VER_IND              CD_CURRNT_VER_IND,
           CD_AI.REGSTR_STUS_NM_DN           CD_REGSTR_STUS_NM,
           CD_AI.ADMIN_STUS_NM_DN            CD_ADMIN_STUS_NM,
           ADMIN_ITEM.ADMIN_ITEM_TYP_ID,
           ''                                CNTXT_AGG,
             SYSDATE
           - GREATEST (DE.LST_UPD_DT,
                       admin_item.lst_upd_dt,
                       Value_dom.LST_UPD_DT,
                       dec_ai.LST_UPD_DT)    LST_UPD_CHG_DAYS
      FROM ADMIN_ITEM,
           DE,
           VALUE_DOM,
           ADMIN_ITEM   VALUE_DOM_AI,
           ADMIN_ITEM   DEC_AI,
           DE_CONC,
           VW_CONC_DOM  DEC_CD,
           VW_CONC_DOM  CD_AI,
           ADMIN_ITEM   OC,
           ADMIN_ITEM   PROP
     WHERE     ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 4
           AND DE.ITEM_ID = ADMIN_ITEM.ITEM_ID
           AND DE.VER_NR = ADMIN_ITEM.VER_NR
           AND DE.VAL_DOM_ITEM_ID = VALUE_DOM_AI.ITEM_ID
           AND DE.VAL_DOM_VER_NR = VALUE_DOM_AI.VER_NR
           AND DE.VAL_DOM_ITEM_ID = VALUE_DOM.ITEM_ID
           AND DE.VAL_DOM_VER_NR = VALUE_DOM.VER_NR
           AND DE.DE_CONC_ITEM_ID = DEC_AI.ITEM_ID
           AND DE.DE_CONC_VER_NR = DEC_AI.VER_NR
           AND DE.DE_CONC_ITEM_ID = DE_CONC.ITEM_ID
           AND DE_CONC.OBJ_CLS_ITEM_ID = OC.ITEM_ID
           AND DE_CONC.OBJ_CLS_VER_NR = OC.VER_NR
           AND DE_CONC.PROP_ITEM_ID = PROP.ITEM_ID
           AND DE_CONC.PROP_VER_NR = PROP.VER_NR
           AND DE.DE_CONC_VER_NR = DE_CONC.VER_NR
           AND DE_CONC.CONC_DOM_ITEM_ID = DEC_CD.ITEM_ID
           AND DE_CONC.CONC_DOM_VER_NR = DEC_CD.VER_NR
           AND VALUE_DOM.CONC_DOM_ITEM_ID = CD_AI.ITEM_ID
           AND VALUE_DOM.CONC_DOM_VER_NR = CD_AI.VER_NR;

/* Formatted on 6/7/2021 11:47:28 AM (QP5 v5.354) */
CREATE OR REPLACE FORCE VIEW VW_NCI_AI
(
    ITEM_ID,
    VER_NR,
    ITEM_ID_STR,
    CREAT_USR_ID,
    LST_UPD_USR_ID,
    FLD_DELETE,
    LST_DEL_DT,
    S2P_TRN_DT,
    LST_UPD_DT,
    CREAT_DT,
    SEARCH_STR
)
BEQUEATH DEFINER
AS
    SELECT ADMIN_ITEM.ITEM_ID,
           ADMIN_ITEM.VER_NR,
           '.' || ADMIN_ITEM.ITEM_ID || '.'    ITEM_ID_STR,
           ADMIN_ITEM.CREAT_USR_ID,
           ADMIN_ITEM.LST_UPD_USR_ID,
           ADMIN_ITEM.FLD_DELETE,
           ADMIN_ITEM.LST_DEL_DT,
           ADMIN_ITEM.S2P_TRN_DT,
           ADMIN_ITEM.LST_UPD_DT,
           ADMIN_ITEM.CREAT_DT,
         trim(SUBSTR (
                 trim(ADMIN_ITEM.ITEM_LONG_NM)
              || '||'
              || trim(ADMIN_ITEM.ITEM_NM)
              || '||'
              || trim(ADMIN_ITEM.ITEM_DESC),1,
              4290))
              || '||'
              || 
              SUBSTR ( trim(REF_DESC),
             1,
              30000)                          SEARCH_STR
      FROM ADMIN_ITEM  ADMIN_ITEM,
           (  SELECT item_id,
                     ver_nr,
                     LISTAGG (trim(ref_desc),
                              '||'
                              ON OVERFLOW TRUNCATE )
                     WITHIN GROUP (ORDER BY ref_desc DESC)    ref_desc
                FROM REF, OBJ_KEY
               WHERE     REF_TYP_ID = OBJ_KEY.OBJ_KEY_ID
                     AND LOWER (OBJ_KEY_DESC) LIKE '%question%'
            GROUP BY item_id, ver_nr) REF                                   --
     WHERE     ADMIN_ITEM.ITEM_ID = REF.ITEM_ID(+)
           AND ADMIN_ITEM.VER_NR = REF.VER_NR(+);


