-- Monthly CDE Metric Queries
-- List of Contexts
SELECT CONTEXTS_VIEW.CONTE_IDSEQ, CONTEXTS_VIEW.NAME, CONTEXTS_VIEW.LL_NAME, CONTEXTS_VIEW.PAL_NAME, CONTEXTS_VIEW.DESCRIPTION, CONTEXTS_VIEW.LANGUAGE, CONTEXTS_VIEW.CREATED_BY, CONTEXTS_VIEW.DATE_CREATED, CONTEXTS_VIEW.MODIFIED_BY, CONTEXTS_VIEW.DATE_MODIFIED, SUM(CONTEXTS_VIEW.VERSION)
FROM SBR.CONTEXTS CONTEXTS_VIEW
GROUP BY CONTEXTS_VIEW.CONTE_IDSEQ, CONTEXTS_VIEW.NAME, CONTEXTS_VIEW.LL_NAME, CONTEXTS_VIEW.PAL_NAME, CONTEXTS_VIEW.DESCRIPTION, CONTEXTS_VIEW.LANGUAGE, CONTEXTS_VIEW.CREATED_BY, CONTEXTS_VIEW.DATE_CREATED, CONTEXTS_VIEW.MODIFIED_BY, CONTEXTS_VIEW.DATE_MODIFIED
;
-- CDE Standards
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('STANDARD') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- CDE Draft Mod
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(DATA_ELEMENTS_VIEW.ASL_NAME) = UPPER('DRAFT MOD') )
;
-- CDE Draft New
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(DATA_ELEMENTS_VIEW.ASL_NAME) = UPPER('DRAFT NEW') )
;
-- CDE Released
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DELETED_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(DATA_ELEMENTS_VIEW.ASL_NAME) LIKE UPPER('RELEASED') )
;
-- CDE Retired
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( DATA_ELEMENTS_VIEW.ASL_NAME LIKE 'RETIR%' )
;
-- CDE RELEASED-NON-CMPLNT (new May 2018)
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( DATA_ELEMENTS_VIEW.ASL_NAME LIKE 'RELEASED-NON-CMPLNT' )
;
-- Model CDE Draft New
SELECT DATA_ELEMENTS_VIEW.DE_IDSEQ, DATA_ELEMENTS_VIEW.PREFERRED_NAME, DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.VD_IDSEQ, DATA_ELEMENTS_VIEW.DEC_IDSEQ, DATA_ELEMENTS_VIEW.PREFERRED_DEFINITION, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DELETED_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DECODE(DATA_ELEMENTS_VIEW.DATE_MODIFIED,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DATA_ELEMENTS_VIEW.DATE_MODIFIED,'MM'),'MM')||'1900','MMYYYY')), DECODE(DATA_ELEMENTS_VIEW.DATE_MODIFIED,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DATA_ELEMENTS_VIEW.DATE_MODIFIED,'DD'),'DD')||'190001','DDYYYYMM')), DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.QUESTION, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( DATA_ELEMENTS_VIEW.CREATED_BY LIKE 'UML%' ) AND ( DATA_ELEMENTS_VIEW.ASL_NAME LIKE 'DRAFT%' )
;
-- Model CDE Released
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DELETED_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.CREATED_BY) LIKE UPPER('UML%') ) AND ( UPPER(DATA_ELEMENTS_VIEW.ASL_NAME) LIKE UPPER('Released') )
ORDER BY DATA_ELEMENTS_VIEW.CREATED_BY ASC
;
-- Model CDE Retired
SELECT DATA_ELEMENTS_VIEW.CONTE_IDSEQ, DATA_ELEMENTS_VIEW.ASL_NAME, DATA_ELEMENTS_VIEW.LONG_NAME, DATA_ELEMENTS_VIEW.LATEST_VERSION_IND, DATA_ELEMENTS_VIEW.DELETED_IND, DATA_ELEMENTS_VIEW.DATE_CREATED, DATA_ELEMENTS_VIEW.CREATED_BY, DATA_ELEMENTS_VIEW.DATE_MODIFIED, DATA_ELEMENTS_VIEW.MODIFIED_BY, DATA_ELEMENTS_VIEW.BEGIN_DATE, DATA_ELEMENTS_VIEW.END_DATE, DATA_ELEMENTS_VIEW.CHANGE_NOTE, DATA_ELEMENTS_VIEW.ORIGIN, DATA_ELEMENTS_VIEW.VERSION, DATA_ELEMENTS_VIEW.CDE_ID
FROM SBR.DATA_ELEMENTS_VIEW DATA_ELEMENTS_VIEW
WHERE ( UPPER(DATA_ELEMENTS_VIEW.CREATED_BY) LIKE UPPER('UML%') ) AND ( UPPER(DATA_ELEMENTS_VIEW.ASL_NAME) LIKE UPPER('Retired%') )
ORDER BY DATA_ELEMENTS_VIEW.CREATED_BY ASC
;
-- All CDEs created for current POP - without or with Registration Status
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE (BEGIN_DATE > ('30-SEP-18'))
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
---
-- All Released CDEs created for current POP - without or with Registration Status
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ((UPPER(DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS) LIKE UPPER('RELEASED')) AND (BEGIN_DATE > ('30-SEP-18')))
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
---
-- Released POP CDEs with no registration status
---
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ((UPPER(DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS) LIKE UPPER('RELEASED')) AND (BEGIN_DATE > ('30-SEP-18'))  AND(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS is Null ))
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
---
-- Released POP CDEs with registration status
---
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ((UPPER(DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS) LIKE UPPER('RELEASED')) AND (BEGIN_DATE > ('30-SEP-18'))  AND(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS is not Null ))
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- RELEASED-NON-CMPLNT POP CDEs with registration status (new May 2018)
---
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM SBREXT.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ((UPPER(DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS) LIKE UPPER('RELEASED-NON-CMPLNT')) AND (BEGIN_DATE > ('30-SEP-18'))  AND(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS is not Null ))
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;