-- Monthly VD Metric Queries
-- VD Draft New
SELECT VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN, SUM(VALUE_DOMAINS_VIEW.VD_ID), SUM(VALUE_DOMAINS_VIEW.VERSION)
FROM SBR.VALUE_DOMAINS_VIEW VALUE_DOMAINS_VIEW
WHERE ( UPPER(VALUE_DOMAINS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(VALUE_DOMAINS_VIEW.ASL_NAME) LIKE UPPER('DRAFT NEW') )
GROUP BY VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN
;
-- VD Released
SELECT VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN, SUM(VALUE_DOMAINS_VIEW.VD_ID), SUM(VALUE_DOMAINS_VIEW.VERSION)
FROM SBR.VALUE_DOMAINS_VIEW VALUE_DOMAINS_VIEW
WHERE ( UPPER(VALUE_DOMAINS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(VALUE_DOMAINS_VIEW.ASL_NAME) LIKE UPPER('RELEASED') )
GROUP BY VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN
;
-- VD RELEASED-NON-CMPLNT (new May 2018)
SELECT VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN, SUM(VALUE_DOMAINS_VIEW.VD_ID), SUM(VALUE_DOMAINS_VIEW.VERSION)
FROM SBR.VALUE_DOMAINS_VIEW VALUE_DOMAINS_VIEW
WHERE ( UPPER(VALUE_DOMAINS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(VALUE_DOMAINS_VIEW.ASL_NAME) LIKE UPPER('RELEASED-NON-CMPLNT') )
GROUP BY VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN
;
-- VD Retired
SELECT VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN, SUM(VALUE_DOMAINS_VIEW.VD_ID), SUM(VALUE_DOMAINS_VIEW.VERSION)
FROM SBR.VALUE_DOMAINS_VIEW VALUE_DOMAINS_VIEW
WHERE ( UPPER(VALUE_DOMAINS_VIEW.LATEST_VERSION_IND) LIKE UPPER('YES') ) AND ( UPPER(VALUE_DOMAINS_VIEW.ASL_NAME) LIKE UPPER('RETIR%') )
GROUP BY VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN
;
-- POP - All VDs
SELECT VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN, SUM(VALUE_DOMAINS_VIEW.VD_ID), SUM(VALUE_DOMAINS_VIEW.VERSION)
FROM SBR.VALUE_DOMAINS_VIEW VALUE_DOMAINS_VIEW
WHERE (BEGIN_DATE > ('30-SEP-18'))
GROUP BY VALUE_DOMAINS_VIEW.CONTE_IDSEQ, VALUE_DOMAINS_VIEW.BEGIN_DATE, VALUE_DOMAINS_VIEW.END_DATE, VALUE_DOMAINS_VIEW.VD_TYPE_FLAG, VALUE_DOMAINS_VIEW.ASL_NAME, VALUE_DOMAINS_VIEW.CHANGE_NOTE, VALUE_DOMAINS_VIEW.LONG_NAME, VALUE_DOMAINS_VIEW.LATEST_VERSION_IND, VALUE_DOMAINS_VIEW.DATE_CREATED, VALUE_DOMAINS_VIEW.CREATED_BY, VALUE_DOMAINS_VIEW.DATE_MODIFIED, VALUE_DOMAINS_VIEW.MODIFIED_BY, VALUE_DOMAINS_VIEW.ORIGIN
;