--DSRMWS-2587
GRANT READ ON ONEDATA_WA.NCI_CNCPT_REL TO ONEDATA_RO; 
GRANT READ ON ONEDATA_WA.NCI_PROC_EXEC TO ONEDATA_RO;
GRANT READ ON ONEDATA_WA.NCI_CHANGE_HISTORY TO ONEDATA_RO;
GRANT READ ON ONEDATA_WA.NCI_CLSFCTN_SCHM_ITEM TO ONEDATA_RO;
GRANT READ ON ONEDATA_WA.NCI_CSI_ALT_DEFNMS TO ONEDATA_RO;