CREATE OR REPLACE FUNCTION MAP_DATA_TYPE
(cadsr_data_type VARCHAR2 )
RETURN VARCHAR2 IS
mapped_type varchar2(20);
BEGIN
	mapped_type :=
	CASE cadsr_data_type
		WHEN 'ALPHANUMERIC' THEN 'Character'
		WHEN 'Alpha DVG' THEN 'Character'
		WHEN 'BINARY OBJECT' THEN cadsr_data_type
		WHEN 'BOOLEAN' THEN 'Boolean'
		WHEN 'BRIDG_SET_v2.1' THEN cadsr_data_type
		WHEN 'CHARACTER' THEN 'Character'
		WHEN 'CLOB' THEN 'Character'
		WHEN 'DATE' THEN 'Time >> Date'
		WHEN 'DATE/TIME' THEN 'Date-and-Time'
		WHEN 'DATETIME' THEN 'Date-and-Time'
		WHEN 'Date Alpha DVG' THEN 'Character'
		WHEN 'Derived' THEN 'Class'
		WHEN 'HL7ADv3' THEN cadsr_data_type
		WHEN 'HL7ANYv3' THEN cadsr_data_type
		WHEN 'HL7BAGADv3' THEN cadsr_data_type
		WHEN 'HL7BAGTELv3' THEN cadsr_data_type
		WHEN 'HL7BLv3' THEN cadsr_data_type
		WHEN 'HL7CDv3' THEN 'Class'
		WHEN 'HL7DSETCDv3' THEN cadsr_data_type
		WHEN 'HL7DSETCRv3' THEN cadsr_data_type
		WHEN 'HL7DSETENv3' THEN cadsr_data_type
		WHEN 'HL7DSETIDv3' THEN cadsr_data_type
		WHEN 'HL7DSETOIDv3' THEN cadsr_data_type
		WHEN 'HL7DSETONv3' THEN cadsr_data_type
		WHEN 'HL7DSETSCv3' THEN cadsr_data_type
		WHEN 'HL7DSETSTv3' THEN cadsr_data_type
		WHEN 'HL7DSETTELURLv3' THEN cadsr_data_type
		WHEN 'HL7EDv3' THEN 'Character'
		WHEN 'HL7EXPRPQv3' THEN cadsr_data_type
		WHEN 'HL7IDv3' THEN cadsr_data_type
		WHEN 'HL7IIv3' THEN cadsr_data_type
		WHEN 'HL7INTNONNEGv3' THEN cadsr_data_type
		WHEN 'HL7INTPOSv3' THEN cadsr_data_type
		WHEN 'HL7INTv3' THEN 'Integer'
		WHEN 'HL7IVLEXPRTSDATETIME' THEN cadsr_data_type
		WHEN 'HL7IVLINTv3' THEN cadsr_data_type
		WHEN 'HL7IVLPQv3' THEN cadsr_data_type
		WHEN 'HL7IVLTSDATEFULLv3' THEN cadsr_data_type
		WHEN 'HL7IVLTSDATETIMEv3' THEN cadsr_data_type
		WHEN 'HL7IVLTSDATEv3' THEN cadsr_data_type
		WHEN 'HL7OIDv3' THEN cadsr_data_type
		WHEN 'HL7PNv3' THEN 'Character'
		WHEN 'HL7PPDv3.0' THEN cadsr_data_type
		WHEN 'HL7PQTIMEv3' THEN cadsr_data_type
		WHEN 'HL7PQv3' THEN cadsr_data_type
		WHEN 'HL7REALv3' THEN 'Real'
		WHEN 'HL7RTOINTNONNEGINTPO' THEN cadsr_data_type
		WHEN 'HL7RTOINTNONNEGPQTIM' THEN cadsr_data_type
		WHEN 'HL7RTOPQPQTIMEv3' THEN cadsr_data_type
		WHEN 'HL7RTOPQPQv3' THEN cadsr_data_type
		WHEN 'HL7SCv3' THEN cadsr_data_type
		WHEN 'HL7STSIMPLEv3' THEN cadsr_data_type
		WHEN 'HL7STv3' THEN 'Character'
		WHEN 'HL7TELURLv3' THEN cadsr_data_type
		WHEN 'HL7TELv3' THEN 'Character'
		WHEN 'HL7TNv3' THEN cadsr_data_type
		WHEN 'HL7TSDATEFULLv3' THEN cadsr_data_type
		WHEN 'HL7TSDATETIMEv3' THEN cadsr_data_type
		WHEN 'HL7TSv3' THEN 'Time'
		WHEN 'HL7URGINTNONNEGv3' THEN cadsr_data_type
		WHEN 'HL7URGINTPOSv3' THEN cadsr_data_type
		WHEN 'HL7URGPQTIMEv3' THEN cadsr_data_type
		WHEN 'HL7URGPQv3' THEN cadsr_data_type
		WHEN 'ISO21090ADPartv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPALv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPBNNv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPBNRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPBNSv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPBRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPCARv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPCENv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPCNTv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPCPAv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPCTYv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPDALv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPDIAAv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPDIQv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPDIRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPDISTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPDMDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPDMIDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPINTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPPOBv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPPREv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPSALv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPSTAv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPSTBv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPSTRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPSTTPv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPUNIDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPUNTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ADXPZIPv1.0' THEN 'Character'
		WHEN 'ISO21090ADXPv1.0' THEN 'Character'
		WHEN 'ISO21090ADv1.0' THEN 'Character'
		WHEN 'ISO21090ANYv1.0' THEN 'Character'
		WHEN 'ISO21090BAGv1.0' THEN 'Character'
		WHEN 'ISO21090BLNTNULv1.0' THEN cadsr_data_type
		WHEN 'ISO21090BLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090CDBasev1.0' THEN cadsr_data_type
		WHEN 'ISO21090CDCVv1.0' THEN cadsr_data_type
		WHEN 'ISO21090CDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090COLLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090COv1.0' THEN cadsr_data_type
		WHEN 'ISO21090CSv1.0' THEN cadsr_data_type
		WHEN 'ISO21090DSETv1.0' THEN 'Character'
		WHEN 'ISO21090EDDCINLINv1.' THEN cadsr_data_type
		WHEN 'ISO21090EDDCREFv1.0' THEN cadsr_data_type
		WHEN 'ISO21090EDIMAGEv1.0' THEN cadsr_data_type
		WHEN 'ISO21090EDSIGNAT1.0' THEN cadsr_data_type
		WHEN 'ISO21090EDSTRTITv1.0' THEN cadsr_data_type
		WHEN 'ISO21090EDSTRTXv1.0' THEN cadsr_data_type
		WHEN 'ISO21090EDTEXTv1.0' THEN 'Character'
		WHEN 'ISO21090EDv1.0' THEN 'Character'
		WHEN 'ISO21090EIVLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090ENONv1.0' THEN 'Character'
		WHEN 'ISO21090ENPNv1.0' THEN 'Character'
		WHEN 'ISO21090ENTNv1.0' THEN 'Character'
		WHEN 'ISO21090ENV1.0' THEN cadsr_data_type
		WHEN 'ISO21090ENXPv1.0' THEN 'Character'
		WHEN 'ISO21090GLISTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090GTSBPIVLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090HISTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090HXITv1.0' THEN cadsr_data_type
		WHEN 'ISO21090IIv1.0' THEN 'Character'
		WHEN 'ISO21090INTNTNEGv1.0' THEN 'Integer'
		WHEN 'ISO21090INTPOSv1.0' THEN 'Integer'
		WHEN 'ISO21090INTv1.0' THEN 'Integer'
		WHEN 'ISO21090IVLHIGHv1.0' THEN cadsr_data_type
		WHEN 'ISO21090IVLLOWv1.0' THEN cadsr_data_type
		WHEN 'ISO21090IVLWIDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090IVLv1.0' THEN 'Character'
		WHEN 'ISO21090LISTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090MOv1.0' THEN cadsr_data_type
		WHEN 'ISO21090NPPDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090PIVLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090PQRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090PQTIMEv1.0' THEN 'Time'
		WHEN 'ISO21090PQv1.0' THEN 'Real'
		WHEN 'ISO21090QSCv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSDv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSETv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSIv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSPv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSSv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QSUv1.0' THEN cadsr_data_type
		WHEN 'ISO21090QTYv1.0' THEN 'Real'
		WHEN 'ISO21090REALv1.0' THEN 'Real'
		WHEN 'ISO21090RTOv1.0' THEN 'Real'
		WHEN 'ISO21090SCNTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090SCv1.0' THEN cadsr_data_type
		WHEN 'ISO21090SLISTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090STNTv1.0' THEN cadsr_data_type
		WHEN 'ISO21090STSIMv1.0' THEN 'Character'
		WHEN 'ISO21090STv1.0' THEN 'Character'
		WHEN 'ISO21090StrDcCMCtv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcCMFtntv' THEN cadsr_data_type
		WHEN 'ISO21090StrDcCMGv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDcCMInlv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcCMTitv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcClGpv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcContv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcFtnRfv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcFtnv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDcItemv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcLHtmlv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcLenv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDcListv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcPargv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcRdMMv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcSubv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTCelv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTRGrpv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTRPtv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTRv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTbleIt1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTblev1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTcellv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDcTitFtv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDocBav1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDocBrv1.0' THEN cadsr_data_type
		WHEN 'ISO21090StrDocCapv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDocClItv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDocColv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDocSupv1.' THEN cadsr_data_type
		WHEN 'ISO21090StrDocTextv1' THEN cadsr_data_type
		WHEN 'ISO21090StrDocTitv1.' THEN cadsr_data_type
		WHEN 'ISO21090TELEMAILv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TELPERSv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TELPHONv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TELURLv1.0' THEN 'Character'
		WHEN 'ISO21090TELv1.0' THEN 'Character'
		WHEN 'ISO21090TSBIRTHv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TSDATEv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TSDATFLv1.0' THEN 'Date-and-Time'
		WHEN 'ISO21090TSDTTIFLv1.0' THEN cadsr_data_type
		WHEN 'ISO21090TSDTTIv1.0' THEN 'Date-and-Time'
		WHEN 'ISO21090TSv1.0' THEN 'Time'
		WHEN 'ISO21090Tv1.0' THEN 'Integer'
		WHEN 'ISO21090URGHIGHv1.0' THEN cadsr_data_type
		WHEN 'ISO21090URGLOWv1.0' THEN cadsr_data_type
		WHEN 'ISO21090URGv1.0' THEN 'Real'
		WHEN 'ISO21090UVPv1.0' THEN cadsr_data_type
		WHEN 'Integer' THEN 'Integer'
		WHEN 'MutableTreeNote' THEN cadsr_data_type
		WHEN 'NUMBER' THEN 'Real'
		WHEN 'Numeric Alpha DVG' THEN 'Character'
		WHEN 'OBJECT' THEN 'Bit String'
		WHEN 'SAS Date' THEN 'Integer'
		WHEN 'SAS Time' THEN 'Integer'
		WHEN 'SVG' THEN cadsr_data_type
		WHEN 'String Array' THEN cadsr_data_type
		WHEN 'TABLE' THEN cadsr_data_type
		WHEN 'TIME' THEN 'Time'
		WHEN 'UMLBinaryv1.0' THEN 'Bit String'
		WHEN 'UMLCodev1.0' THEN 'Character'
		WHEN 'UMLOctetv1.0' THEN 'Octet'
		WHEN 'UMLUidv1.0' THEN 'Character'
		WHEN 'UMLUriv1.0' THEN cadsr_data_type
		WHEN 'UMLXMLv1.0' THEN 'Character'
		WHEN 'anyClass' THEN 'Class'
		WHEN 'binary' THEN 'Bit String'
		WHEN 'evs.domain.Property' THEN cadsr_data_type
		WHEN 'evs.domain.Role' THEN cadsr_data_type
		WHEN 'evs.domain.Source' THEN cadsr_data_type
		WHEN 'evs.domain.TreeNode' THEN cadsr_data_type
		WHEN 'java.lang.Boolean' THEN cadsr_data_type
		WHEN 'java.lang.Byte' THEN 'Character'
		WHEN 'java.lang.Character' THEN 'Character'
		WHEN 'java.lang.Double' THEN 'Real'
		WHEN 'java.lang.Float' THEN 'Floating-point'
		WHEN 'java.lang.Integer' THEN 'Integer'
		WHEN 'java.lang.Integer[]' THEN 'Integer'
		WHEN 'java.lang.Long' THEN 'Integer'
		WHEN 'java.lang.Object' THEN 'Bit String'
		WHEN 'java.lang.Short' THEN 'Integer'
		WHEN 'java.lang.String' THEN 'Character'
		WHEN 'java.lang.String[]' THEN 'Character'
		WHEN 'java.lang.String[][]' THEN cadsr_data_type
		WHEN 'java.lang.Void' THEN cadsr_data_type
		WHEN 'java.math.BigDecimal' THEN cadsr_data_type
		WHEN 'java.sql.Blob' THEN cadsr_data_type
		WHEN 'java.sql.Clob' THEN cadsr_data_type
		WHEN 'java.sql.Timestamp' THEN 'Date-and-Time'
		WHEN 'java.util.ArrayList' THEN cadsr_data_type
		WHEN 'java.util.Collection' THEN 'Character'
		WHEN 'java.util.Date' THEN 'Date-and-Time'
		WHEN 'java.util.HashSet' THEN cadsr_data_type
		WHEN 'java.util.Hashtable' THEN cadsr_data_type
		WHEN 'java.util.Map' THEN 'Character'
		WHEN 'java.util.Set' THEN cadsr_data_type
		WHEN 'java.util.Vector' THEN cadsr_data_type
		WHEN 'varchar' THEN 'Character'
		WHEN 'xsd:ID' THEN 'xsd:ID'
		WHEN 'xsd:IDREF' THEN 'xsd:IDREF'
		WHEN 'xsd:base64Binary' THEN 'xsd:base64Binary'
		WHEN 'xsd:boolean' THEN 'xsd:boolean'
		WHEN 'xsd:byte' THEN 'xsd:byte'
		WHEN 'xsd:date' THEN 'xsd:date'
		WHEN 'xsd:dateTime' THEN 'xsd:dateTime'
		WHEN 'xsd:decimal' THEN 'xsd:decimal'
		WHEN 'xsd:double' THEN 'xsd:double'
		WHEN 'xsd:float' THEN 'xsd:float'
		WHEN 'xsd:int' THEN 'xsd:int'
		WHEN 'xsd:integer' THEN 'xsd:integer'
		WHEN 'xsd:long' THEN 'xsd:long'
		WHEN 'xsd:short' THEN 'xsd:short'
		WHEN 'xsd:string' THEN 'xsd:string'
		WHEN 'xsd:time' THEN 'xsd:time'
		ELSE cadsr_data_type
	END;
	RETURN (mapped_type);
END MAP_DATA_TYPE;
/
