CREATE SEQUENCE ERR_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;
CREATE TABLE ONEDATA_MIGRATION_ERROR
(
  ERR_ID          NUMBER,
  IDSEQ           VARCHAR2(50 BYTE),
  PUBLIC_ID       NUMBER,
  VERSION         NUMBER(4,2),
  ACTL_NAME       VARCHAR2(50 BYTE),
  PREFERRED_NAME  VARCHAR2(400 BYTE),
  ERROR_DESC      VARCHAR2(50 BYTE),
  DATE_CREATED    DATE                          DEFAULT Sysdate,
  CREATED_BY      VARCHAR2(50 BYTE)             DEFAULT User,
  DESTINATION     VARCHAR2(50 BYTE),
  TIER            VARCHAR2(50 BYTE)
);
GRANT ALL ON ONEDATA_MIGRATION_ERROR to PUBLIC;
CREATE SEQUENCE SAG_MIGR_ERR_SEQ  MINVALUE 100 MAXVALUE 999999999999999999999999999 INCREMENT BY 5 
START WITH 100 CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE TABLE SAG_MIGR_LOV_ERR
(
  ERR_ID        NUMBER                          DEFAULT SAG_MIGR_ERR_SEQ.NEXTVAL,
  LOV_VALUE     VARCHAR2(500 BYTE)              NOT NULL,
  LOV_NAME      VARCHAR2(50 BYTE)               NOT NULL,
  ERROR_TEXT    VARCHAR2(2000 BYTE)             NOT NULL,
  DATE_CREATED  DATE                            DEFAULT sysdate,
  CREATED_BY    VARCHAR2(30 BYTE)               DEFAULT user
);
GRANT ALL ON SAG_MIGR_LOV_ERR to PUBLIC;