select 
DE.ITEM_ID "CDE ID",
DE.VER_NR "CDE VERSION",
CDE.ITEM_NM "CDE Long Name",
ref.ref_desc"Preferred Question Text",
VD.ITEM_NM "VD Long Name",
VALUE_DOM.ITEM_ID "VD ID",
VALUE_DOM.VER_NR "VD VERSION",
VALUE_DOM.VAL_DOM_MAX_CHAR ,
VALUE_DOM.VAL_DOM_HIGH_VAL_NUM "VD Maximum Length",
FMT.FMT_NM "VD Display Format",
PERM_VAL.PERM_VAL_NM "Permissible Value Value",
VM.ITEM_NM "Value Meaning Long Name" ,  
PERM_VAL.NCI_VAL_MEAN_ITEM_ID "Value Meaning ID" ,
PERM_VAL.NCI_VAL_MEAN_VER_NR  "Value Meaning Version"                                  
from  
de DE,ADMIN_ITEM CDE,
VALUE_DOM ,ADMIN_ITEM VD,
ADMIN_ITEM VM, PERM_VAL ,FMT ,
(SELECT item_id, ver_nr, ref_desc
 FROM REF WHERE ref_typ_id = 80) REF
where VD.ADMIN_ITEM_TYP_ID=3
AND CDE.ADMIN_ITEM_TYP_ID=4
and VM.ADMIN_ITEM_TYP_ID=53 --(Value Meaning)
and CDE.ITEM_ID=DE.ITEM_ID
and CDE.VER_NR=DE.VER_NR
and de.VAL_DOM_ITEM_ID=VALUE_DOM.ITEM_ID
and de.VAL_DOM_VER_NR =VALUE_DOM.VER_NR
and VD.ITEM_ID=VALUE_DOM.ITEM_ID
and VD.VER_NR =VALUE_DOM.VER_NR
and VD.ITEM_ID=PERM_VAL.VAL_DOM_ITEM_ID
and VD.VER_NR=PERM_VAL.VAL_DOM_VER_NR
and VM.ITEM_ID=PERM_VAL.NCI_VAL_MEAN_ITEM_ID(+)
and VM.VER_NR=PERM_VAL.NCI_VAL_MEAN_VER_NR(+)
AND CDE.ITEM_ID = REF.ITEM_ID(+)
AND CDE.VER_NR = REF.VER_NR(+)
AND VALUE_DOM.VAL_DOM_FMT_ID=FMT.FMT_ID(+)
and CDE.ITEM_ID=6343385
and CDE.VER_NR=1
order by PERM_VAL.PERM_VAL_NM


select*from PERM_VAL where VAL_DOM_ITEM_ID=6343354