select 
DE.ITEM_ID CDE_ID,
DE.VER_NR CDE_VERSION,
CDE.ITEM_NM CDE Long Name,
ref.ref_desc Preferred_Question,
VD.ITEM_NM VD_Long_Name,
VALUE_DOM.ITEM_ID VD_ID,
VALUE_DOM.VER_NR VD_VERSION,
VALUE_DOM.VAL_DOM_MAX_CHAR ,
VALUE_DOM.VAL_DOM_HIGH_VAL_NUM VD_Maximum_Length,
FMT.FMT_NM VD_Display_Format,
PERM_VAL.PERM_VAL_NM PV_Value,
VM.ITEM_NM VM_Long_Name ,  
PERM_VAL.NCI_VAL_MEAN_ITEM_ID VM_ID ,
PERM_VAL.NCI_VAL_MEAN_VER_NR  VM_Version 
DECODE (VAL_DOM_TYP_ID,  17, 'E',  18, 'N')     VAL_DOM_TYP_ID,                                 
from  
de DE,ADMIN_ITEM CDE,
VALUE_DOM ,ADMIN_ITEM VD,
ADMIN_ITEM VM, PERM_VAL ,FMT ,
(SELECT item_id, ver_nr, ref_desc
 FROM REF WHERE ref_typ_id = 80) REF
where VD.ADMIN_ITEM_TYP_ID=3
AND CDE.ADMIN_ITEM_TYP_ID=4
and VM.ADMIN_ITEM_TYP_ID=53 --(Value Meaning)
and CDE.ITEM_ID=DE.ITEM_ID
and CDE.VER_NR=DE.VER_NR
and de.VAL_DOM_ITEM_ID=VALUE_DOM.ITEM_ID
and de.VAL_DOM_VER_NR =VALUE_DOM.VER_NR
and VD.ITEM_ID=VALUE_DOM.ITEM_ID
and VD.VER_NR =VALUE_DOM.VER_NR
and VD.ITEM_ID=PERM_VAL.VAL_DOM_ITEM_ID
and VD.VER_NR=PERM_VAL.VAL_DOM_VER_NR
and VM.ITEM_ID=PERM_VAL.NCI_VAL_MEAN_ITEM_ID(+)
and VM.VER_NR=PERM_VAL.NCI_VAL_MEAN_VER_NR(+)
AND CDE.ITEM_ID = REF.ITEM_ID(+)
AND CDE.VER_NR = REF.VER_NR(+)
AND VALUE_DOM.VAL_DOM_FMT_ID=FMT.FMT_ID(+)
and CDE.ITEM_ID=6343385
and CDE.VER_NR=1
order by PERM_VAL.PERM_VAL_NM