
EXEC DBMS_STATS.GATHER_TABLE_STATS ('SBREXT', 'QUEST_CONTENTS_EXT');

EXEC DBMS_STATS.GATHER_TABLE_STATS ('SBREXT', 'QC_RECS_EXT');

EXEC DBMS_STATS.GATHER_TABLE_STATS ('SBREXT', 'VALID_VALUES_ATT_EXT');

EXEC DBMS_STATS.GATHER_TABLE_STATS ('SBR', 'ADMINISTERED_COMPONENTS');
