-- Monthly CDE Metric Queries
-- CDE 1-Preferred Standards
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('PREFERRED STANDARD') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- CDE 2-Standard
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('STANDARD') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 3-Qualified CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('QUALIFIED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 4-Recorded CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('RECORDED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 5-Candidate CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('CANDIDATE') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 6-Incomplete CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('INCOMPLETE') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 7-Retired CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('RETIRED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 8-Superceded CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('SUPERCEDED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 9-Historical CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('HISTORICAL') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 10-Application CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('APPLICATION') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- Non-ISO Status CDEs
--
-- 11-Proposed CDEs
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('PROPOSED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 12-Suspended CDEs - retired status Feb 2017
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('SUSPENDED') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
-- 13-Standardized Elsewhere CDEs - retired status Feb 2017
SELECT DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM')), SUM(DE_EXCEL_GENERATOR_VIEW.VERSION), SUM(DE_EXCEL_GENERATOR_VIEW.CDE_ID)
FROM ONEDATA_WA.DE_EXCEL_GENERATOR_VIEW DE_EXCEL_GENERATOR_VIEW
WHERE ( UPPER(DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS) = UPPER('STANDARDIZED ELSEWHERE') AND 1 = 1 )
GROUP BY DE_EXCEL_GENERATOR_VIEW.LONG_NAME, DE_EXCEL_GENERATOR_VIEW.ORIGIN, DE_EXCEL_GENERATOR_VIEW.DE_CONTE_NAME, DE_EXCEL_GENERATOR_VIEW.DE_WK_FLOW_STATUS, DE_EXCEL_GENERATOR_VIEW.REGISTRATION_STATUS, DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'YYYY'),'YYYY')||'01','YYYYMM')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'MM'),'MM')||'1900','MMYYYY')), DECODE(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,NULL,TO_DATE(NULL,'MMDDYYYY'),TO_DATE(TO_CHAR(TRUNC(DE_EXCEL_GENERATOR_VIEW.BEGIN_DATE,'DD'),'DD')||'190001','DDYYYYMM'))
;
--
-- DEC with registration status  (1-11-17 did not include registration status)
--
 select de.CONTEXTS_NAME con_name,dec.version,de.cde_id ,dec.DEC_ID,de.long_name DE_long_name,
 dec.long_name DEC_long_name,dec.PREFERRED_NAME,dec.PROPL_NAME,
dec.OCL_NAME,dec.PREFERRED_DEFINITION,dec.Asl_name,dec.begin_date,
dec.End_date,dec.CHANGE_NOTE,dec.date_created, dec.created_by, dec.date_modified, dec.modified_by ,
dv.Asl_name,dv.long_name,dv.PREFERRED_NAME,dv.vd_id,dv.version,dv.begin_date,dv.End_date,
dv.CHANGE_NOTE,dv.LATEST_VERSION_IND,dv.date_created,dv.created_by, dv.date_modified, dv.modified_by
from   ONEDATA_WA.DATA_ELEMENT_CONCEPTS_VIEW dec ,ONEDATA_WA.DATA_ELEMENTS_VIEW de,ONEDATA_WA.VALUE_DOMAINS_VIEW dv
where de.DEC_IDSEQ=dec.DEC_IDSEQ
and de.VD_IDSEQ=dv.VD_IDSEQ
and UPPER(dv.ASL_NAME)  like 'DRAFT%'
order by de.CONTEXTS_NAME,de.long_name; 
--
-- DEC with "Released" registration status  (1-11-17 did not include registration status)
--
select de.CONTEXTS_NAME con_name,dec.version,de.cde_id ,dec.DEC_ID,de.long_name DE_long_name,dec.long_name DEC_long_name,dec.PREFERRED_NAME,dec.PROPL_NAME,
dec.OCL_NAME,
dec.PREFERRED_DEFINITION,dec.Asl_name,dec.begin_date,
dec.End_date,dec.CHANGE_NOTE,dec.date_created, dec.created_by, dec.date_modified, dec.modified_by ,
dv.Asl_name,dv.long_name,dv.PREFERRED_NAME,dv.vd_id,dv.version,dv.begin_date,dv.End_date,
dv.CHANGE_NOTE,dv.LATEST_VERSION_IND,dv.date_created,dv.created_by, dv.date_modified, dv.modified_by
from  ONEDATA_WA.DATA_ELEMENT_CONCEPTS_VIEW dec ,ONEDATA_WA.DATA_ELEMENTS_VIEW de,ONEDATA_WA.VALUE_DOMAINS_VIEW dv
where de.DEC_IDSEQ=dec.DEC_IDSEQ
and de.VD_IDSEQ=dv.VD_IDSEQ
and UPPER(dv.ASL_NAME)  like 'RELEASED'
order by de.CONTEXTS_NAME,de.long_name; 
--
-- DEC with "Retired" registration status  (1-11-17 did not include registration status)
--
select de.CONTEXTS_NAME,dec.version,de.cde_id ,dec.DEC_ID,de.long_name DE_long_name,dec.long_name DEC_long_name,dec.PREFERRED_NAME,dec.PROPL_NAME,
dec.OCL_NAME,
dec.PREFERRED_DEFINITION,dec.Asl_name,dec.begin_date,
dec.End_date,dec.CHANGE_NOTE,dec.date_created, dec.created_by, dec.date_modified, dec.modified_by ,
dv.Asl_name,dv.long_name,dv.PREFERRED_NAME,dv.vd_id,dv.version,dv.begin_date,dv.End_date,
dv.CHANGE_NOTE,dv.LATEST_VERSION_IND,dv.date_created,dv.created_by, dv.date_modified, dv.modified_by
from  ONEDATA_WA.DATA_ELEMENT_CONCEPTS_VIEW dec ,ONEDATA_WA.DATA_ELEMENTS_VIEW de,ONEDATA_WA.VALUE_DOMAINS_VIEW dv
where de.DEC_IDSEQ=dec.DEC_IDSEQ
and de.VD_IDSEQ=dv.VD_IDSEQ
and UPPER(dv.ASL_NAME)  like 'RETIRED'
order by de.CONTEXTS_NAME,de.long_name; 
