

   CREATE SEQUENCE  NCI_SEQ_DATA_AUDT  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TRIGGER NCI_TR_DATA_AUDT  BEFORE INSERT  on NCI_DATA_AUDT  for each row
       Begin  select NCI_SEQ_DATA_AUDT.nextval
    into :new.DA_ID  from  dual ;    END ;
    /
    

  create table TMP_DATA_AUDT
  (	"OBJ_ID" NUMBER, 
	"CHNGREQ_NR" NUMBER NOT NULL ENABLE, 
	"UPD_COL_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UPD_COL_OLD_VAL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"UPD_COL_NEW_VAL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRNS_TYP" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CNCPTL_OBJ_ID" NUMBER, 
	"CREAT_DT" DATE DEFAULT SYSDATE, 
	"CREAT_USR_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"AUDT_DESC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDT_DETL" CLOB COLLATE "USING_NLS_COMP", 
	"PK_REF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TBL_NM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDT_CMNTS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
   	ITEM_ID number,
   	VER_NR number(4,2),
   	C_ITEM_ID number,
   	C_ITEM_VER_NR number(4,2),
   	P_ITEM_ID number,
        P_ITEM_VER_NR number(4,2),
        REL_TYP_ID integer);
	

insert into NCI_MDR_CNTRL (ID,PARAM_NM, PARAM_VAL)
values (10, 'DOWNLOAD_HOST', 'http://ncias-d2289-c:5555');
commit;

alter table admin_item disable all trigggers;

update ADMIN_ITEM set ITEM_RPT_URL = (select PARAM_VAL || '/invoke/FormDownload/printerFriendly?item_id=' || item_id ||  chr(38) || 'version=' || ver_nr || '\Click_To_Download'
from NCI_MDR_CNTRL where PARAM_NM = 'DOWNLOAD_HOST') where ADMIN_ITEM_TYP_ID = 54;
commit;

alter table admin_item enable all trigggers;

