DROP TABLE CDE_19_GENERATED_XML
/
DROP TABLE CDE_19_REPORTS_ERR_LOG
/
DROP VIEW VW_CNCPT_19
/
DROP VIEW DE_CDE1_XML_GENERATOR_749VW
/
DROP VIEW CDEBROWSER_COMPLEX_DE_VIEW_N
/
DROP VIEW CDEBROWSER_CS_VIEW_N
/
DROP VIEW CDEBROWSER_DE_DEC_VIEW
/
DROP INDEX INX_CNCPT_AI_VR
/
DROP TYPE CDEBROWSER_VD_T749     
/
DROP TYPE CDEBROWSER_DEC_T  
/
DROP TYPE DERIVED_DATA_ELEMENT_T  
/
DROP TYPE DATA_ELEMENT_DERIVATION_LIST_T 
/
DROP TYPE DATA_ELEMENT_DERIVATION_T
/
DROP TYPE CDEBROWSER_RD_LIST_T  
/
DROP TYPE CDEBROWSER_RD_T 
/
DROP TYPE CDEBROWSER_CSI_LIST_T   
/
DROP TYPE CDEBROWSER_CSI_T   
/
DROP TYPE DE_VALID_VALUE_LIST_T      
/
DROP TYPE DE_VALID_VALUE_T    
/
DROP TYPE MDSR_749_PV_VD_LIST_T 
/
DROP  TYPE MDSR_749_PV_VD_ITEM_T            
/
DROP TYPE MDSR_749_ALTERNATENAM_LIST_T  
/
DROP TYPE MDSR_749_ALTERNATENAME_ITEM_T   
/
DROP TYPE CDEBROWSER_ALTNAME_LIST_T   
/
DROP TYPE CDEBROWSER_ALTNAME_T2     
/
DROP TYPE ADMIN_COMPONENT_WITH_CON_T        
/
DROP TYPE ADMIN_COMPONENT_WITH_ID_LN_T       
/
DROP TYPE ADMIN_COMPONENT_WITH_ID_T    
/
DROP TYPE CONCEPTS_LIST_T    
/
DROP TYPE CONCEPT_DETAIL_T  
/
