CREATE OR REPLACE TRIGGER OD_TR_FORM_IMPORT
BEFORE INSERT OR UPDATE ON NCI_STG_FORM_IMPORT
for each row
BEGIN
:new.LST_UPD_DT_CHAR := TO_CHAR(SYSDATE, 'MM/DD/YY HH24:MI:SS');
:new.LST_UPD_DT := sysdate;
END;
/
