truncate table NCI_STG_FORM_IMPORT;
truncate table NCI_STG_FORM_QUEST_IMPORT;
truncate table NCI_STG_FORM_VV_IMPORT;

alter table NCI_STG_FORM_IMPORT
add (BTCH_USR_NM varchar2(100) not null, BTCH_NM varchar2(100) not null, CREATED_FORM_ITEM_ID number);

alter table NCI_STG_FORM_IMPORT
add (LST_UPD_DT_CHAR varchar2(20));


alter table NCI_STG_FORM_QUEST_IMPORT
add (BTCH_SEQ_NBR number not null);


alter table NCI_STG_FORM_QUEST_IMPORT
add (SRC_REQ_IND varchar2(10));

  CREATE OR REPLACE VIEW VW_NCI_USR_CART AS
  SELECT AI.ITEM_ID, AI.VER_NR, AI.ITEM_LONG_NM, AI.CNTXT_NM_DN, AI.ITEM_NM, AI.REGSTR_STUS_NM_DN, AI.ADMIN_STUS_NM_DN,
  AI.ADMIN_ITEM_TYP_ID,
  ok.OBJ_KEY_DESC ADMIN_ITEM_TYP_NM,
UC.CNTCT_SECU_ID, UC.CREAT_DT, UC.CREAT_USR_ID, UC.LST_UPD_USR_ID,
UC.FLD_DELETE, UC.LST_DEL_DT, UC.S2P_TRN_DT, UC.LST_UPD_DT, UC.GUEST_USR_NM, UC.CART_NM
FROM NCI_USR_CART UC, ADMIN_ITEM AI , OBJ_KEY ok WHERE AI.ITEM_ID = UC.ITEM_ID AND AI.VER_NR = UC.VER_NR and ai.admin_item_typ_id = ok.obj_key_id and ok.obj_typ_id = 4
and admin_item_typ_id in (4,52,54,2,3);
