 CREATE TABLE "SAG_LOAD_MT" 
   (	"NCI_META_CUI" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NCI_META_CONCEPT_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NCI_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"NCI_PT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ATOM_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SOURCE_ATOM_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"PREF_IND" NUMBER(1,0) DEFAULT 0, 
	"TERM_TYP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate
   ) ;

insert into obj_Key select * from onedata_wa.obj_key where obj_typ_id = 54;
 commit;
 
grant all on obj_key to onedata_wa;
