
  CREATE OR REPLACE VIEW VW_NCI_VD_VM_ALT_NMS AS
  SELECT   PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		an.CREAT_DT, an.CREAT_USR_ID, an.LST_UPD_USR_ID, greatest(nvl(PV.FLD_DELETE,0), nvl(an.fld_Delete,0)) FLD_DELETE, an.LST_DEL_DT, an.S2P_TRN_DT, an.LST_UPD_DT,
         an.NM_DESC,  an.nm_typ_id, an.CNTXT_NM_DN VM_CNTXT_NM_DN  ,
         an.LANG_ID, an.nm_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT
       FROM   PERM_VAL PV, ALT_NMS an, ADMIN_ITEM vm where 
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
/
CREATE OR REPLACE  VIEWVW_NCI_VD_VM_ALT_DEF AS
  SELECT  PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		an.CREAT_DT, an.CREAT_USR_ID, an.LST_UPD_USR_ID, greatest(nvl(PV.FLD_DELETE,0), nvl(an.fld_Delete,0)) FLD_DELETE, an.LST_DEL_DT, an.S2P_TRN_DT, an.LST_UPD_DT,
         an.DEF_DESC,  an.NCI_DEF_TYP_ID, 
         an.LANG_ID, an.def_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT,
	 an.CNTXT_ITEM_ID, an.CNTXT_VER_NR
       FROM   PERM_VAL PV, ALT_DEF an, ADMIN_ITEM vm where 
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
/

  CREATE OR REPLACE VIEW VW_NCI_DE_VM_ALT_DEF AS
  SELECT   DE.ITEM_ID  DE_ITEM_ID, 
		DE.VER_NR DE_VER_NR, PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		an.CREAT_DT, an.CREAT_USR_ID, an.LST_UPD_USR_ID, greatest(nvl(PV.FLD_DELETE,0), nvl(an.fld_Delete,0)) FLD_DELETE,
		an.LST_DEL_DT, an.S2P_TRN_DT, an.LST_UPD_DT,
         an.DEF_DESC,  an.NCI_DEF_TYP_ID, 
         an.LANG_ID, an.def_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT,
	 an.CNTXT_ITEM_ID, an.CNTXT_VER_NR
       FROM  DE, PERM_VAL PV, ALT_DEF an, ADMIN_ITEM vm where 
	PV.VAL_DOM_ITEM_ID = DE.VAL_DOM_ITEM_ID and
	PV.VAL_DOM_VER_NR = DE.VAL_DOM_VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;

/
  CREATE OR REPLACE  VIEW VW_NCI_DE_VM_ALT_NMS AS
  SELECT   DE.ITEM_ID  DE_ITEM_ID, 
		DE.VER_NR DE_VER_NR, PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		an.CREAT_DT, AN.CREAT_USR_ID, AN.LST_UPD_USR_ID, greatest(nvl(AN.FLD_DELETE,0),nvl(pv.fld_delete,0)) fld_delete, 
		an.LST_DEL_DT, an.S2P_TRN_DT, AN.LST_UPD_DT,
         an.NM_DESC,  an.nm_typ_id, an.CNTXT_NM_DN VM_CNTXT_NM_DN  ,
         an.LANG_ID, an.nm_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT
       FROM  DE, PERM_VAL PV, ALT_NMS an, ADMIN_ITEM vm where 
	PV.VAL_DOM_ITEM_ID = DE.VAL_DOM_ITEM_ID and
	PV.VAL_DOM_VER_NR = DE.VAL_DOM_VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR;
/
