CREATE OR REPLACE PROCEDURE SP_TEST_ALL_NEW
AS
V_CNT INTEGER;
BEGIN

DELETE FROM OD_CADSR_TABLES_TEST_RESULTS;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DE', 
(SELECT COUNT(*) FROM ONEDATA_WA.DE WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DATA_ELEMENTS WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DE Concept', 
(SELECT COUNT(*) FROM ONEDATA_WA.DE_CONC  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DATA_ELEMENT_CONCEPTS  WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Format', 
(SELECT COUNT(*) FROM ONEDATA_WA.FMT) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.FORMATS_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Data type', 
(SELECT COUNT(*) FROM ONEDATA_WA.DATA_TYP WHERE NCI_DTTYPE_TYP_ID = 1) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DATATYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Registration Status', 
(SELECT COUNT(*) FROM ONEDATA_WA.STUS_MSTR WHERE STUS_TYP_ID = 1 AND FLD_DELETE=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.REG_STATUS_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Workflow Status', 
(SELECT COUNT(*) FROM ONEDATA_WA.STUS_MSTR WHERE STUS_TYP_ID = 2 AND FLD_DELETE=0) WA_CNT,
NULL  DIFF_CNT,
(SELECT COUNT(*) FROM SBR.AC_STATUS_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'UOM', 
(SELECT COUNT(*) FROM ONEDATA_WA.UOM) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.UNIT_OF_MEASURES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Conceptual Domain', 
(SELECT COUNT(*) FROM ONEDATA_WA.CONC_DOM  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CONCEPTUAL_DOMAINS WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Object Class', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_CLS  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.OBJECT_CLASSES_EXT WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Property', 
(SELECT COUNT(*) FROM ONEDATA_WA.PROP  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.PROPERTIES_EXT WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Value Domain', 
(SELECT COUNT(*) FROM ONEDATA_WA.VALUE_DOM WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.VALUE_DOMAINS WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Concept', 
(SELECT COUNT(*) FROM ONEDATA_WA.CNCPT WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.CONCEPTS_EXT  WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CSI', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_CLSFCTN_SCHM_ITEM  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CS_ITEMS WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Classification Scheme', 
(SELECT COUNT(*) FROM ONEDATA_WA.CLSFCTN_SCHM WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CLASSIFICATION_SCHEMES WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Representation Class', 
(SELECT COUNT(*) FROM ONEDATA_WA.REP_CLS WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.REPRESENTATIONS_EXT WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Value Meaning', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_VAL_MEAN WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.VALUE_MEANINGS WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Protocol', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_PROTCL  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.PROTOCOLS_EXT WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'OC Recs', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_OC_RECS  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.OC_RECS_EXT WHERE NVL(DELETED_IND,'No') ='No') CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Context', 
(SELECT COUNT(*) FROM ONEDATA_WA.CNTXT WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CONTEXTS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CD-VM', 
(SELECT COUNT(*) FROM ONEDATA_WA.CONC_DOM_VAL_MEAN WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CD_VMS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'PV', 
(SELECT COUNT(*) FROM ONEDATA_WA.PERM_VAL WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.VD_PVS) CADSR_CNT,NULL
FROM DUAL;
COMMIT;



INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Concept - AI',  
(SELECT COUNT(*) FROM ONEDATA_WA.CNCPT_ADMIN_ITEM WHERE NVL(FLD_DELETE,0)=0)  WA_CNT,
NULL DIFF_CNT,
( SELECT COUNT(*)
FROM SBREXT.COMPONENT_CONCEPTS_EXT  CC,
               SBR.CONCEPTS_EXT CON ,
               (SELECT OC_IDSEQ NCI_IDSEQ,CONDR_IDSEQ FROM SBREXT.OBJECT_CLASSES_EXT
               UNION 
               SELECT PROP_IDSEQ,CONDR_IDSEQ FROM SBREXT.PROPERTIES_EXT 
                UNION 
               SELECT REP_IDSEQ,CONDR_IDSEQ FROM SBREXT.REPRESENTATIONS_EXT
               UNION
               SELECT VD_IDSEQ,CONDR_IDSEQ FROM SBR.VALUE_DOMAINS
               UNION
               SELECT VM_IDSEQ,CONDR_IDSEQ FROM SBR.VALUE_MEANINGS
               UNION 
               SELECT CD_IDSEQ,CONDR_IDSEQ FROM SBR.CONCEPTUAL_DOMAINS 
               )AI
         WHERE    CC.CON_IDSEQ = CON.CON_IDSEQ
         AND AI.CONDR_IDSEQ= CC.CONDR_IDSEQ) CADSR_CNT,NULL 
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Designations', 
(SELECT COUNT(*) FROM ONEDATA_WA.ALT_NMS WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DESIGNATIONS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;



INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Definitions', 
(SELECT COUNT(*) FROM ONEDATA_WA.ALT_DEF WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DEFINITIONS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;



INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Reference Documents', 
(SELECT COUNT(*) FROM ONEDATA_WA.REF WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.REFERENCE_DOCUMENTS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Trigger Actions', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_FORM_TA WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.TRIGGERED_ACTIONS_EXT ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Trigger Actions Protocol/CSI', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_FORM_TA_REL WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.TA_PROTO_CSI_EXT ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Organization', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ORG WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.ORGANIZATIONS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Person', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_PRSN WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.PERSONS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Addresses', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ENTTY_ADDR  WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CONTACT_ADDRESSES ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Communications', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ENTTY_COMM WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CONTACT_COMMS ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Form', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_FORM WHERE NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.QUEST_CONTENTS_EXT WHERE QTL_NAME IN ( 'CRF','TEMPLATE') ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Module', 
(SELECT COUNT(*) FROM ONEDATA_WA.ADMIN_ITEM AI, ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE ADMIN_ITEM_TYP_ID = 52 AND  NVL(AI.FLD_DELETE,0) = 0 AND AI.ITEM_ID = R.C_ITEM_ID 
AND NVL(R.FLD_DELETE,0) = 0 AND AI.VER_NR = R.C_ITEM_VER_NR 
AND R.REL_TYP_ID = 61 ) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.QUEST_CONTENTS_EXT M,SBREXT.QUEST_CONTENTS_EXT F
WHERE M.QTL_NAME = 'MODULE' AND NVL(M.DELETED_IND,'No' )='No' AND NVL(F.DELETED_IND,'No' )='No' AND M.DN_CRF_IDSEQ =F.QC_IDSEQ )  CADSR_CNT,NULL
FROM DUAL
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Question', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ADMIN_ITEM_REL_ALT_KEY A ,ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE A.REL_TYP_ID = 63 AND NVL(A.FLD_DELETE,0)=0
AND NVL(R.FLD_DELETE,0)=0 AND A.P_ITEM_ID=R.C_ITEM_ID
AND A.P_ITEM_VER_NR= R.C_ITEM_VER_NR) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM  SBREXT.QUEST_CONTENTS_EXT Q ,
SBREXT.QUEST_CONTENTS_EXT M,
SBREXT.QUEST_CONTENTS_EXT F WHERE Q.QTL_NAME = 'QUESTION' 
AND NVL(Q.DELETED_IND,'No') ='No'AND Q.P_MOD_IDSEQ =M.QC_IDSEQ
AND M.DN_CRF_IDSEQ=F.QC_IDSEQ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Question VV', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_QUEST_VALID_VALUE V ,ONEDATA_WA.NCI_ADMIN_ITEM_REL_ALT_KEY A ,ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE A.REL_TYP_ID = 63 AND NVL(A.FLD_DELETE,0)=0
AND NVL(R.FLD_DELETE,0)=0 AND A.P_ITEM_ID=R.C_ITEM_ID
AND A.P_ITEM_VER_NR= R.C_ITEM_VER_NR 
AND V.Q_PUB_ID=A.NCI_PUB_ID
AND V.Q_VER_NR=A.NCI_VER_NR
AND NVL(V.FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.QUEST_CONTENTS_EXT VV ,SBREXT.QUEST_CONTENTS_EXT Q ,
SBREXT.QUEST_CONTENTS_EXT M,SBREXT.QUEST_CONTENTS_EXT F
WHERE VV.P_QST_IDSEQ =Q.QC_IDSEQ AND Q.P_MOD_IDSEQ =M.QC_IDSEQ
AND M.DN_CRF_IDSEQ=F.QC_IDSEQ  AND Q.QTL_NAME = 'QUESTION' AND NVL(Q.DELETED_IND,'No') ='No'
AND VV.QTL_NAME = 'VALID_VALUE' AND NVL(VV.DELETED_IND,'No') ='No'  ) CADSR_CNT, NULL 
FROM DUAL
COMMIT;

/****added NCI_INSTR****/
INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'From HDR Instruction', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_FORM WHERE HDR_INSTR IS NOT NULL  AND NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM(
SELECT MIN(QC_ID) QC_ID,MIN(VERSION) VERSION ,DN_CRF_IDSEQ FROM SBREXT.QUEST_CONTENTS_EXT QC1 
WHERE QC1.QTL_NAME = 'FORM_INSTR'AND PREFERRED_DEFINITION !=' ' AND NVL(DELETED_IND,'No') ='No' GROUP BY DN_CRF_IDSEQ))
 CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'From FOOTER Instruction', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_FORM WHERE FTR_INSTR IS NOT NULL  AND NVL(FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM(
SELECT MIN(QC_ID) QC_ID,MIN(VERSION) VERSION ,DN_CRF_IDSEQ FROM SBREXT.QUEST_CONTENTS_EXT QC1 
WHERE QC1.QTL_NAME LIKE'FOOTER%'AND PREFERRED_DEFINITION !=' ' AND NVL(DELETED_IND,'No') ='No' GROUP BY DN_CRF_IDSEQ))
 CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Module Instruction', 
(SELECT COUNT(*) FROM ONEDATA_WA.ADMIN_ITEM AI, ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE ADMIN_ITEM_TYP_ID = 52 AND  NVL(AI.FLD_DELETE,0) = 0 AND AI.ITEM_ID = R.C_ITEM_ID 
AND NVL(R.FLD_DELETE,0) = 0 AND AI.VER_NR = R.C_ITEM_VER_NR 
AND R.REL_TYP_ID = 61  AND R.INSTR IS NOT NULL) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM(
SELECT MIN(QCI.QC_ID) QC_ID,MIN(QCI.VERSION) VERSION ,QCI.P_MOD_IDSEQ FROM SBREXT.QUEST_CONTENTS_EXT QCI ,
SBREXT.QUEST_CONTENTS_EXT M,SBREXT.QUEST_CONTENTS_EXT F
WHERE M.QTL_NAME = 'MODULE' AND NVL(M.DELETED_IND,'No' )='No' AND NVL(F.DELETED_IND,'No' )='No' AND M.DN_CRF_IDSEQ =F.QC_IDSEQ
AND QCI.P_MOD_IDSEQ=M.QC_IDSEQ
AND QCI.QTL_NAME = 'MODULE_INSTR'AND QCI.PREFERRED_DEFINITION !=' ' AND NVL(QCI.DELETED_IND,'No') ='No' GROUP BY QCI.P_MOD_IDSEQ))
 CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'Question Instruction', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ADMIN_ITEM_REL_ALT_KEY Q ,ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE Q.REL_TYP_ID = 63 AND NVL(Q.FLD_DELETE,0)=0
AND NVL(R.FLD_DELETE,0)=0 AND Q.P_ITEM_ID=R.C_ITEM_ID
AND Q.P_ITEM_VER_NR= R.C_ITEM_VER_NR
AND Q.REL_TYP_ID=63 AND Q.INSTR IS NOT NULL  AND NVL(Q.FLD_DELETE,0)=0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM(
SELECT MIN(I.QC_ID) QC_ID,MIN(I.VERSION) VERSION ,I.P_QST_IDSEQ FROM SBREXT.QUEST_CONTENTS_EXT I ,SBREXT.QUEST_CONTENTS_EXT Q ,
SBREXT.QUEST_CONTENTS_EXT M,
SBREXT.QUEST_CONTENTS_EXT F WHERE Q.QTL_NAME = 'QUESTION' 
AND NVL(Q.DELETED_IND,'No') ='No'AND Q.P_MOD_IDSEQ =M.QC_IDSEQ
AND M.DN_CRF_IDSEQ=F.QC_IDSEQ AND I.P_QST_IDSEQ = Q.P_QST_IDSEQ
AND I.QTL_NAME = 'QUESTION_INSTR'AND I.PREFERRED_DEFINITION !=' ' AND NVL(I.DELETED_IND,'No') ='No' GROUP BY I.P_QST_IDSEQ))
 CADSR_CNT,NULL
FROM DUAL
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'VV Instruction', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_QUEST_VALID_VALUE V ,ONEDATA_WA.NCI_ADMIN_ITEM_REL_ALT_KEY A ,ONEDATA_WA.NCI_ADMIN_ITEM_REL R 
WHERE A.REL_TYP_ID = 63 AND NVL(A.FLD_DELETE,0)=0
AND NVL(R.FLD_DELETE,0)=0 AND A.P_ITEM_ID=R.C_ITEM_ID
AND A.P_ITEM_VER_NR= R.C_ITEM_VER_NR 
AND V.Q_PUB_ID=A.NCI_PUB_ID
AND V.Q_VER_NR=A.NCI_VER_NR
AND NVL(V.FLD_DELETE,0)=0
and V.INSTR IS NOT NULL ) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM(
SELECT MIN(i.QC_ID) QC_ID,MIN(i.VERSION) VERSION ,i.P_VAL_IDSEQ FROM SBREXT.QUEST_CONTENTS_EXT i,SBREXT.QUEST_CONTENTS_EXT VV ,SBREXT.QUEST_CONTENTS_EXT Q ,
SBREXT.QUEST_CONTENTS_EXT M,SBREXT.QUEST_CONTENTS_EXT F
WHERE VV.P_QST_IDSEQ =Q.QC_IDSEQ AND Q.P_MOD_IDSEQ =M.QC_IDSEQ
AND M.DN_CRF_IDSEQ=F.QC_IDSEQ  AND Q.QTL_NAME = 'QUESTION' AND NVL(Q.DELETED_IND,'No') ='No'
AND VV.QTL_NAME = 'VALID_VALUE' AND NVL(VV.DELETED_IND,'No') ='No' 
AND i.QTL_NAME = 'VALUE_INSTR'AND i.PREFERRED_DEFINITION !=' ' AND NVL(i.DELETED_IND,'No') ='No'
AND i.P_VAL_IDSEQ=vv.QC_IDSEQ GROUP BY i.P_VAL_IDSEQ))
 CADSR_CNT,NULL
FROM DUAL;
COMMIT;

 /***table NCI_ALT_KEY_ADMIN_ITEM_REL is replaced  by NCI_CLSFCTN_SCHM_ITEM*/
INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CS CSI', 
((SELECT COUNT(*) FROM ONEDATA_WA.ADMIN_ITEM CSIAI, ONEDATA_WA.NCI_CLSFCTN_SCHM_ITEM CSI, ONEDATA_WA.ADMIN_ITEM CS WHERE
 CSI.CS_ITEM_ID = CS.ITEM_ID AND CSI.CS_ITEM_VER_NR = CS.VER_NR
 AND CSI.ITEM_ID = CSIAI.ITEM_ID AND CSI.VER_NR = CSIAI.VER_NR  AND NVL(CSI.FLD_DELETE,0) = 0)) WA_CNT,
NULL DIFF_CNT,
((SELECT COUNT(*) FROM SBR.CS_CSI )-(SELECT COUNT(*)FROM SBR.ADMINISTERED_COMPONENTS A WHERE ASL_NAME LIKE 'RETIRED%'
AND A.MODIFIED_BY= 'GDEEN' AND ACTL_NAME='CS_ITEM')) CADSR_CNT,NULL
FROM DUAL;

/***table NCI_ALT_KEY_ADMIN_ITEM_REL is replaced by NCI_ADMIN_ITEM_REL***/
INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CS CSI DE Relationship', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ADMIN_ITEM_REL WHERE REL_TYP_ID = 65 AND NVL(FLD_DELETE,0) = 0) WA_CNT,
NULL DIFF_CNT,
((SELECT COUNT(*) FROM SBR.AC_CSI )-(
SELECT COUNT(*) FROM SBREXT.QUEST_CONTENTS_EXT Q,SBR.AC_CSI
WHERE Q.QTL_NAME IN ('QUESTION','VALID_VALUE')AND QC_IDSEQ=AC_IDSEQ
)) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


/********  ADDED**********/
INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'COMPLEX DE Relationship', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_ADMIN_ITEM_REL WHERE REL_TYP_ID = 66 AND NVL(FLD_DELETE,0) = 0) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.COMPLEX_DE_RELATIONSHIPS) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'PROGRAM AREA', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 14) WA_CNT,
((SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 14 )-
(SELECT COUNT(*) FROM SBR.PROGRAM_AREAS_LOV )) DIFF_CNT,
(SELECT COUNT(*) FROM SBR.PROGRAM_AREAS_LOV ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DESIGNATION TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 11) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DESIGNATION_TYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'ADDRESS TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 25) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.ADDR_TYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'COMMUNICATION TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 26) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.COMM_TYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'STATUS-ADMIN TYPE RELATIONSHIP', 
(SELECT COUNT(*) FROM ONEDATA_WA.NCI_AI_TYP_VALID_STUS ) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.ASL_ACTL_EXT)CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DERIVATION TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 21) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.COMPLEX_REP_TYPE_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DOCUMENT TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 1) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.DOCUMENT_TYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CLASSIFICATION SCHEME TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 3) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CS_TYPES_LOV) CADSR_CNT,NULL
FROM DUAL;
COMMIT;


INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'CSI TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 20) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBR.CSI_TYPES_LOV ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'DEFINITION TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 15) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.DEFINITION_TYPES_LOV_EXT) CADSR_CNT,NULL
FROM DUAL;
COMMIT;



INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'ORIGIN', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 18) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.SOURCES_EXT) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'PROTOCOL TYPE', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 19) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM (SELECT DISTINCT 19, TYPE, TYPE FROM SBREXT.PROTOCOLS_EXT WHERE TYPE IS NOT NULL AND NVL(DELETED_IND,'No') ='No') ) CADSR_CNT,NULL
FROM DUAL;
COMMIT;
-- FORM CATEGORY WHERE OBJ_TYP_ID = 22;
INSERT INTO OD_CADSR_TABLES_TEST_RESULTS (TABLE_NAME, WA_CNT, DIFF_CNT, CADSR_CNT,COMMENTS)
SELECT 'FORM CATEGORY', 
(SELECT COUNT(*) FROM ONEDATA_WA.OBJ_KEY WHERE OBJ_TYP_ID = 22) WA_CNT,
NULL DIFF_CNT,
(SELECT COUNT(*) FROM SBREXT.QC_DISPLAY_LOV_EXT) CADSR_CNT,NULL
FROM DUAL;
COMMIT;

UPDATE OD_CADSR_TABLES_TEST_RESULTS SET DIFF_CNT=WA_CNT- CADSR_CNT;
COMMIT;
UPDATE OD_CADSR_TABLES_TEST_RESULTS SET COMMENTS =
CASE 
    WHEN DIFF_CNT>0
    THEN 'THE TABLE '||TABLE_NAME||' HAS FOR '||DIFF_CNT||' RECORS MORE IN OD'
    WHEN DIFF_CNT<0
    THEN 'THE TABLE '||TABLE_NAME||' HAS FOR '||-1*(DIFF_CNT)||' RECORS MORE IN CADSR'
    END 
    WHERE DIFF_CNT<>0;
    COMMIT;
END;
/
CREATE OR REPLACE procedure spLoadCounts AS 
begin
SP_TEST_ALL_NEW;
end;
/
