
  CREATE OR REPLACE  VIEW VW_NCI_CRDC_DE AS
  SELECT ADMIN_ITEM.ITEM_ID,
           ADMIN_ITEM.VER_NR,
          CAST('.' || ADMIN_ITEM.ITEM_ID || '.' AS VARCHAR2(4000))    ITEM_ID_STR,
           ADMIN_ITEM.ITEM_NM,
           ADMIN_ITEM.ITEM_LONG_NM,
           ADMIN_ITEM.ITEM_DESC,
           ADMIN_ITEM.ADMIN_NOTES,
           ADMIN_ITEM.CHNG_DESC_TXT,
           ADMIN_ITEM.CREATION_DT,
           ADMIN_ITEM.EFF_DT,
           ADMIN_ITEM.ORIGIN,
           ADMIN_ITEM.ORIGIN_ID,
           ADMIN_ITEM.ORIGIN_ID_DN,
           ADMIN_ITEM.UNRSLVD_ISSUE,
           ADMIN_ITEM.UNTL_DT,
           ADMIN_ITEM.CURRNT_VER_IND,
           ADMIN_ITEM.REGSTR_STUS_ID,
           ADMIN_ITEM.ADMIN_STUS_ID,
           ADMIN_ITEM.CNTXT_NM_DN,
           ADMIN_ITEM.CNTXT_ITEM_ID,
           ADMIN_ITEM.CNTXT_VER_NR,
           ADMIN_ITEM.CREAT_USR_ID,
           ADMIN_ITEM.CREAT_USR_ID             CREAT_USR_ID_X,
           ADMIN_ITEM.LST_UPD_USR_ID,
           ADMIN_ITEM.LST_UPD_USR_ID           LST_UPD_USR_ID_X,
           ADMIN_ITEM.FLD_DELETE,
           ADMIN_ITEM.LST_DEL_DT,
           ADMIN_ITEM.S2P_TRN_DT,
           ADMIN_ITEM.LST_UPD_DT,
           ADMIN_ITEM.CREAT_DT,
           ADMIN_ITEM.NCI_IDSEQ,
	   ext.csi_concat,
           ADMIN_ITEM.ADMIN_ITEM_TYP_ID,
	   ADMIN_ITEM.ITEM_DEEP_LINK,
           ext.USED_BY                         CNTXT_AGG,
           CRDC_NM.NM_DESC                        CRDC_NM,
           CRDC_DEF.DEF_DESC                        CRDC_DEF,
           CODE_INSTR.REF_DESC                        CRDC_CODE_INSTR,
            EXMPL.REF_DESC                        CRDC_EXMPL,
	   vd.VAL_DOM_TYP_ID	  FROM ADMIN_ITEM,
           NCI_ADMIN_ITEM_EXT  ext,
	      de, VALUE_DOM vd,
           (  SELECT item_id, ver_nr, max(ref_desc)  FROM REF, OBJ_KEY WHERE REF_TYP_ID = OBJ_KEY.OBJ_KEY_ID   AND UPPER(OBJ_KEY_DESC)='EXAMPLE' group by item_id, ver_nr)  EXMPL,
           (  SELECT item_id, ver_nr, max(ref_desc)  FROM REF, OBJ_KEY WHERE REF_TYP_ID = OBJ_KEY.OBJ_KEY_ID   AND UPPER(OBJ_KEY_DESC)='CODING INSTRUCTIONS' group by item_id ,ver_nr)  CODE_INSTR,
           (  SELECT item_id,ver_nr, max(nm_desc)  FROM ALT_NMS, OBJ_KEY WHERE NM_TYP_ID = OBJ_KEY.OBJ_KEY_ID   AND UPPER(OBJ_KEY_DESC)='CRDC ALT NAME' group by item_id, ver_nr)  CRDC_NM,
           (  SELECT item_id, ver_nr, max(def_desc)  FROM ALT_DEF, OBJ_KEY WHERE NCI_DEF_TYP_ID = OBJ_KEY.OBJ_KEY_ID   AND UPPER(OBJ_KEY_DESC)='CRDC DEFINITION' group by item_id, ver_nr)  CRDC_DEF        
     WHERE     ADMIN_ITEM_TYP_ID = 4
           and ADMIN_ITEM.ITEM_Id = de.item_id
           and ADMIN_ITEM.VER_NR = DE.VER_NR
           and de.VAL_DOM_ITEM_ID = vd.ITEM_ID
	   and de.VAL_DOM_VER_NR = vd.VER_NR
	   AND ADMIN_ITEM.ITEM_ID = EXT.ITEM_ID
           AND ADMIN_ITEM.VER_NR = EXT.VER_NR
           AND ADMIN_ITEM.ITEM_ID = EXMPL.ITEM_ID(+)
           AND ADMIN_ITEM.VER_NR = EXMPL.VER_NR(+)
           AND ADMIN_ITEM.ITEM_ID = CRDC_NM.ITEM_ID(+)
           AND ADMIN_ITEM.VER_NR = CRDC_NM.VER_NR(+)
 AND ADMIN_ITEM.ITEM_ID = CRDC_DEF.ITEM_ID(+)
           AND ADMIN_ITEM.VER_NR = CRDC_DEF.VER_NR(+)
 AND ADMIN_ITEM.ITEM_ID = CODE_INSTR.ITEM_ID(+)
           AND ADMIN_ITEM.VER_NR = CODE_INSTR.VER_NR(+)
and ADMIN_ITEM.CNTXT_NM_DN = 'CRDC';



  CREATE OR REPLACE VIEW VW_NCI_DE_VM_ALT_NMS AS
  SELECT   DE.ITEM_ID  DE_ITEM_ID, 
		DE.VER_NR DE_VER_NR, PV.NCI_VAL_MEAN_ITEM_ID VAL_MEAN_ITEM_ID, PV.NCI_VAL_MEAN_VER_NR VAL_MEAN_VER_NR, vm.ITEM_NM VAL_MEAN_LONG_NM, 
	PV.VAL_DOM_ITEM_ID  VAL_DOM_ITEM_ID, PV.VAL_DOM_VER_NR VAL_DOM_VER_NR ,
		an.CREAT_DT, AN.CREAT_USR_ID, AN.LST_UPD_USR_ID, greatest(nvl(AN.FLD_DELETE,0),nvl(pv.fld_delete,0)) fld_delete, 
		an.LST_DEL_DT, an.S2P_TRN_DT, AN.LST_UPD_DT,
         an.NM_DESC,  an.nm_typ_id, an.CNTXT_NM_DN VM_CNTXT_NM_DN  ,
         an.LANG_ID, an.nm_id, PV.PERM_VAL_NM, PV.PERM_VAL_DESC_TXT,
	 e.CNCPT_CONCAT
       FROM  DE, PERM_VAL PV, ALT_NMS an, ADMIN_ITEM vm, NCI_ADMIN_ITEM_EXT e where 
	PV.VAL_DOM_ITEM_ID = DE.VAL_DOM_ITEM_ID and
	PV.VAL_DOM_VER_NR = DE.VAL_DOM_VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = an.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = an.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID = vm.ITEM_ID and
	PV.NCI_VAL_MEAN_VER_NR = vm.VER_NR and
	PV.NCI_VAL_MEAN_ITEM_ID =e.ITEM_ID
	and PV.NCI_VAL_MEAN_VER_NR= e.VER_NR;

