 CREATE INDEX IDX2_PERM_VAL_SUBSET on PERM_VAL_SUBSET ("VAL_DOM_ITEM_ID", "VAL_DOM_VER_NR", "NCI_VAL_MEAN_ITEM_ID", "NCI_VAL_MEAN_VER_NR") ;

CREATE UNIQUE INDEX UX_PERM_VAL_SUBSET ON PERM_VAL_SUBSET ("VAL_DOM_ITEM_ID", "VAL_DOM_VER_NR", "PERM_VAL_NM", "NCI_VAL_MEAN_ITEM_ID", "NCI_VAL_MEAN_VER_NR") ;

  CREATE OR REPLACE EDITIONABLE TRIGGER OD_TR_PERM_VAL_SUBSET BEFORE INSERT  on PERM_VAL_SUBSET  for each row
       BEGIN    IF (:NEW.VAL_ID<= 0  or :NEW.VAL_ID is null)  THEN 
       select od_seq_PERM_VAL.nextval
  into :new.VAL_ID  from  dual ;   END IF; END ;

/

