CREATE TABLE ONEDATA_WA.AI_INPUT_TAB
(	ITEMID_NAME VARCHAR2(50), 
	IDSEQ_NAME VARCHAR2(50), 
	TAB_NAME VARCHAR2(50), 
	ITEM_TYPE_CODE NUMBER, 
	CONDITION VARCHAR2(500), 
	ITEM_TYPE VARCHAR2(30)
);
REM INSERTING into ONEDATA_WA.AI_INPUT_TAB
SET DEFINE OFF;
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('CDE_ID','DE_IDSEQ','SBR.DATA_ELEMENTS',4,null,'DATA ELEMENT');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('DEC_ID','DEC_IDSEQ','SBR.DATA_ELEMENT_CONCEPTS',2,null,'DATA ELEMENT CONCEPT');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('VD_ID','VD_IDSEQ','SBR.VALUE_DOMAINS',3,null,'VALUE DOMAIN');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',56,'WHERE ACTL_NAME = ''OBJECTRECS''','OCRECS');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('OC_ID','OC_IDSEQ','SBREXT.OBJECT_CLASSES_EXT',5,null,'OBJECT CLASS');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PROP_ID','PROP_IDSEQ','SBREXT.PROPERTIES_EXT',6,null,'PROPERTY');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('CON_ID','CON_IDSEQ','SBREXT.CONCEPTS_EXT',49,null,'CONCEPT');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('CSI_ID','CSI_IDSEQ','SBR.CS_ITEMS',51,null,'CLASSIFICATION SCHEME ITEM');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',54,', SBREXT.QUEST_CONTENTS_EXT WHERE AC_IDSEQ = QC_IDSEQ AND ACTL_NAME = ''QUEST_CONTENT'' AND QTL_NAME IN (''TEMPLATE'', ''CRF'')','FORM');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',52,', SBREXT.QUEST_CONTENTS_EXT WHERE AC_IDSEQ = QC_IDSEQ AND ACTL_NAME = ''QUEST_CONTENT'' AND QTL_NAME IN (''MODULE'')','MODULE');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',50,'WHERE ACTL_NAME = ''PROTOCOL''','PROTOCOL');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('VM_ID','VM_IDSEQ','SBR.VALUE_MEANINGS',53,null,'VALUE MEANING');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',9,'WHERE ACTL_NAME = ''CLASSIFICATION''','CLASSIFICATION SCHEME');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',7,'WHERE ACTL_NAME = ''REPRESENTATION''','REPRESENTATION CLASS');
Insert into ONEDATA_WA.AI_INPUT_TAB (ITEMID_NAME,IDSEQ_NAME,TAB_NAME,ITEM_TYPE_CODE,CONDITION,ITEM_TYPE) values ('PUBLIC_ID','AC_IDSEQ','SBR.ADMINISTERED_COMPONENTS',1,'WHERE ACTL_NAME = ''CONCEPTUALDOMAIN''','CONCEPTUAL DOMAIN');
