DROP SEQUENCE SBREXT.ERR_SEQ;

CREATE SEQUENCE SBREXT.ERR_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE PUBLIC SYNONYM ERR_SEQ FOR SBREXT.ERR_SEQ;


GRANT ALTER, SELECT ON SBREXT.ERR_SEQ TO ONEDATA_RA;

GRANT ALTER, SELECT ON SBREXT.ERR_SEQ TO ONEDATA_WA;
