CREATE SEQUENCE SBREXT.SAG_MIGR_ERR_SEQ  MINVALUE 100 MAXVALUE 999999999999999999999999999 INCREMENT BY 5 
START WITH 100 CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE SBREXT.SAG_MIGR_LOV_ERR
(
  ERR_ID NUMBER DEFAULT SBREXT.SAG_MIGR_ERR_SEQ.NEXTVAL,
  LOV_VALUE VARCHAR2(500) NOT NULL ENABLE,
	LOV_NAME VARCHAR(50) NOT NULL ENABLE, 
	ERROR_TEXT VARCHAR2(2000) NOT NULL ENABLE, 
	DATE_CREATED DATE DEFAULT sysdate,
	CREATED_BY VARCHAR2(30) DEFAULT user
);
GRANT ALL ON SBREXT.SAG_MIGR_LOV_ERR to PUBLIC;
GRANT SELECT ON SBREXT.SAG_MIGR_ERR_SEQ TO ONEDATA_WA;
GRANT SELECT ON SBREXT.SAG_MIGR_ERR_SEQ TO ONEDATA_RA;