--schemas SBR, SBREXT are not used any more for data migration, _M schemas are used
DROP TABLE AI_INPUT_TAB_REV;
CREATE TABLE AI_INPUT_TAB_REV
(	ITEMID_NAME VARCHAR2(50), 
	IDSEQ_NAME VARCHAR2(50), 
	TAB_NAME VARCHAR2(50), 
	ITEM_TYPE_CODE NUMBER, 
	CONDITION VARCHAR2(500), 
	ITEM_TYPE VARCHAR2(30)
);
GRANT SELECT ON AI_INPUT_TAB_REV TO ONEDATA_RO;
SET DEFINE OFF;
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('CDE_ID', 'DE_IDSEQ', 'SBR.DATA_ELEMENTS', 4, 'DATA ELEMENT');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('DEC_ID', 'DEC_IDSEQ', 'SBR.DATA_ELEMENT_CONCEPTS', 2, 'DATA ELEMENT CONCEPT');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('VD_ID', 'VD_IDSEQ', 'SBR.VALUE_DOMAINS', 3, 'VALUE DOMAIN');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBR.ADMINISTERED_COMPONENTS', 56, ', SBREXT.OC_RECS_EXT SB WHERE AC.AC_IDSEQ=SB.OCR_IDSEQ AND ACTL_NAME = ''OBJECTRECS''', 
    'OCRECS');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('OC_ID', 'OC_IDSEQ', 'SBREXT.OBJECT_CLASSES_EXT', 5, 'OBJECT CLASS');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('PROP_ID', 'PROP_IDSEQ', 'SBREXT.PROPERTIES_EXT', 6, 'PROPERTY');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('CON_ID', 'CON_IDSEQ', 'SBREXT.CONCEPTS_EXT', 49, 'CONCEPT');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('CSI_ID', 'CSI_IDSEQ', 'SBR.CS_ITEMS', 51, 'CLASSIFICATION SCHEME ITEM');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBREXT.QUEST_CONTENTS_EXT', 54, ', SBR.ADMINISTERED_COMPONENTS SB WHERE AC_IDSEQ = QC_IDSEQ AND ACTL_NAME = ''QUEST_CONTENT'' AND QTL_NAME IN (''TEMPLATE'', ''CRF'')', 
    'FORM');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBREXT.QUEST_CONTENTS_EXT', 52, ', SBR.ADMINISTERED_COMPONENTS SB WHERE AC_IDSEQ = QC_IDSEQ AND ACTL_NAME = ''QUEST_CONTENT'' AND QTL_NAME IN (''MODULE'')', 
    'MODULE');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBREXT.PROTOCOLS_EXT', 50, ', SBR.ADMINISTERED_COMPONENTS  SB WHERE AC_IDSEQ = PROTO_IDSEQ AND ACTL_NAME = ''PROTOCOL''', 
    'PROTOCOL');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, ITEM_TYPE)
 Values
   ('VM_ID', 'VM_IDSEQ', 'SBR.VALUE_MEANINGS', 53, 'VALUE MEANING');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBR.ADMINISTERED_COMPONENTS', 9, ', SBR.CLASSIFICATION_SCHEMES SB WHERE AC.AC_IDSEQ=SB.CS_IDSEQ AND ACTL_NAME = ''CLASSIFICATION''', 
    'CLASSIFICATION SCHEME');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBR.ADMINISTERED_COMPONENTS', 7, ', SBREXT.REPRESENTATIONS_EXT SB WHERE AC.AC_IDSEQ=SB.REP_IDSEQ AND ACTL_NAME = ''REPRESENTATION''', 
    'REPRESENTATION CLASS');
Insert into AI_INPUT_TAB_REV
   (ITEMID_NAME, IDSEQ_NAME, TAB_NAME, ITEM_TYPE_CODE, CONDITION, 
    ITEM_TYPE)
 Values
   ('PUBLIC_ID', 'AC_IDSEQ', 'SBR.ADMINISTERED_COMPONENTS', 1, ', SBR.CONCEPTUAL_DOMAINS SB WHERE AC.AC_IDSEQ=SB.CD_IDSEQ AND ACTL_NAME = ''CONCEPTUALDOMAIN''', 
    'CONCEPTUAL DOMAIN');
COMMIT;
