--Test

alter table nci_ds_hdr add (CMNTS_DESC_TXT varchar2(4000));

alter table NCI_STG_AI_CNCPT_CREAT add (CMNTS_DESC_TXT varchar2(4000));

--drop view VW_CLSFCTN_SCHM;

drop view vw_clsfctn_schm;

drop materialized view vw_clsfctn_schm;

create materialized view  VW_CLSFCTN_SCHM
  BUILD IMMEDIATE
  REFRESH FORCE
  ON DEMAND AS  
SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN, ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, ADMIN_ITEM.CREAT_DT, 
ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, 
ADMIN_ITEM.LST_UPD_DT, CS.CLSFCTN_SCHM_TYP_ID, ADMIN_ITEM.NCI_IDSEQ, ADMIN_ITEM.CNTXT_ITEM_ID, ADMIN_ITEM.CNTXT_VER_NR
FROM ADMIN_ITEM, CLSFCTN_SCHM CS
       WHERE ADMIN_ITEM_TYP_ID = 9 and ADMIN_ITEM.ITEM_ID = CS.ITEM_ID and ADMIN_ITEM.VER_NR = CS.VER_NR; 



  CREATE TABLE NCI_STG_PV_VM_IMPORT 
   (	"STG_AI_ID" NUMBER NOT NULL ENABLE, 
	"CTL_VAL_MSG" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CNCPT_CONCAT_STR_1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONC_DOM_ITEM_ID" NUMBER, 
	"CONC_DOM_VER_NR" NUMBER(4,2), 
	"CNTXT_ITEM_ID" NUMBER, 
	"CNTXT_VER_NR" NUMBER(4,2), 
	"ADMIN_STUS_ID" NUMBER(*,0), 
	"REGSTR_STUS_ID" NUMBER(*,0), 
	"CNCPT_1_ITEM_ID_1" NUMBER, 
	"CNCPT_1_VER_NR_1" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_2" NUMBER, 
	"CNCPT_1_VER_NR_2" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_3" NUMBER, 
	"CNCPT_1_VER_NR_3" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_4" NUMBER, 
	"CNCPT_1_VER_NR_4" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_5" NUMBER, 
	"CNCPT_1_VER_NR_5" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_6" NUMBER, 
	"CNCPT_1_VER_NR_6" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_7" NUMBER, 
	"CNCPT_1_VER_NR_7" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_8" NUMBER, 
	"CNCPT_1_VER_NR_8" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_9" NUMBER, 
	"CNCPT_1_VER_NR_9" NUMBER(4,2), 
	"CNCPT_1_ITEM_ID_10" NUMBER, 
	"CNCPT_1_VER_NR_10" NUMBER(4,2), 
	"CREAT_DT" DATE DEFAULT sysdate, 
	"CREAT_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"LST_UPD_USR_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" DEFAULT user, 
	"FLD_DELETE" NUMBER(1,0) DEFAULT 0, 
	"LST_DEL_DT" DATE DEFAULT sysdate, 
	"S2P_TRN_DT" DATE DEFAULT sysdate, 
	"LST_UPD_DT" DATE DEFAULT sysdate, 
	"GEN_STR" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_ID" NUMBER, 
	"ITEM_1_VER_NR" NUMBER(4,2), 
	"ITEM_1_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_LONG_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_1_DEF" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PERM_VAL_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_LONG_NM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NM" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"BTCH_USR_NM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BTCH_NM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CTL_VAL_STUS" VARCHAR2(100 BYTE) default 'IMPORTED', 
	"BTCH_SEQ_NBR" NUMBER, 
	"CMNTS_DESC_TXT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
    	VAL_DOM_ITEM_ID  number,
        VAL_DOM_VER_NR number,
        VM_STR_TYP  varchar2(100),
        VM_ALT_NM  varchar2(255),
        VM_ALT_NM_TYP_ID  number,
	 PRIMARY KEY ("STG_AI_ID")
   );
   
  

