CREATE INDEX "ONEDATA_WA"."IDX_REF_MTCH_TERM_ADV" ON "ONEDATA_WA"."REF" ("MTCH_TERM_ADV")

  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "USERS" ;

commit work;

 

CREATE INDEX "ONEDATA_WA"."IDX_ALTNMS_MTCH_TERM_ADV" ON "ONEDATA_WA"."ALT_NMS" ("MTCH_TERM_ADV")

  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "USERS" ;

commit work;
