-- List of Contexts
SELECT CONTEXTS_VIEW.CONTE_IDSEQ, CONTEXTS_VIEW.NAME, CONTEXTS_VIEW.LL_NAME, CONTEXTS_VIEW.PAL_NAME, CONTEXTS_VIEW.DESCRIPTION, CONTEXTS_VIEW.LANGUAGE, CONTEXTS_VIEW.CREATED_BY, CONTEXTS_VIEW.DATE_CREATED, CONTEXTS_VIEW.MODIFIED_BY, CONTEXTS_VIEW.DATE_MODIFIED, SUM(CONTEXTS_VIEW.VERSION)
FROM  CONTEXTS_VIEW
GROUP BY CONTEXTS_VIEW.CONTE_IDSEQ, CONTEXTS_VIEW.NAME, CONTEXTS_VIEW.LL_NAME, CONTEXTS_VIEW.PAL_NAME, CONTEXTS_VIEW.DESCRIPTION, CONTEXTS_VIEW.LANGUAGE, CONTEXTS_VIEW.CREATED_BY, CONTEXTS_VIEW.DATE_CREATED, CONTEXTS_VIEW.MODIFIED_BY, CONTEXTS_VIEW.DATE_MODIFIED;
