/*SBR.DATA_ELEMENTS_VIEW
(
    DE_IDSEQ,
    VERSION,
    CONTE_IDSEQ,
    PREFERRED_NAME,
    VD_IDSEQ,
    DEC_IDSEQ,
    PREFERRED_DEFINITION,
    ASL_NAME,
    LONG_NAME,
    LATEST_VERSION_IND,
    DELETED_IND,
    DATE_CREATED,
    BEGIN_DATE,
    CREATED_BY,
    END_DATE,
    DATE_MODIFIED,
    MODIFIED_BY,
    CHANGE_NOTE,
    ORIGIN,
    CDE_ID,
    QUESTION*/
    
  CREATE OR REPLACE VIEW OD_DATA_ELEMENTS_VIEW  AS
    select 
    ADMIN_ITEM.NCI_IDSEQ DE_IDSEQ,
	ADMIN_ITEM.ITEM_ID CDE_ID, 
	ADMIN_ITEM.VER_NR  VERSION,     
	ADMIN_ITEM.ITEM_NM LONG_NAME,
	ADMIN_ITEM.ITEM_LONG_NM PREFERRED_NAME, 
	VD.NCI_IDSEQ VD_IDSEQ,
    DE_CONC.NCI_IDSEQ DEC_IDSEQ,
    CONTE.NCI_IDSEQ CONTE_IDSEQ,
	DE_CONC_ITEM_ID DEC_ID,
	DE_CONC_VER_NR  DEC_VERSION,
	VAL_DOM_ITEM_ID VD_ID,
	VAL_DOM_VER_NR VD_VERSION,
	ADMIN_ITEM.ITEM_DESC PREFERRED_DEFINITION, 
	ADMIN_ITEM.ADMIN_NOTES, 
	ADMIN_ITEM.CHNG_DESC_TXT CHANGE_NOTE,
	--ADMIN_ITEM.CREATION_DT DATE_CREATED,     
	ADMIN_ITEM.EFF_DT BEGIN_DATE, 
	NVL(ADMIN_ITEM.ORIGIN, ADMIN_ITEM.ORIGIN_ID_DN) ORIGIN,
	ADMIN_ITEM.UNRSLVD_ISSUE, 
	ADMIN_ITEM.UNTL_DT, 
	ADMIN_ITEM.CURRNT_VER_IND LATEST_VERSION_IND, 
	--ADMIN_ITEM.REGSTR_STUS_ID, 
	--ADMIN_ITEM.ADMIN_STUS_ID, 
	ADMIN_ITEM.REGSTR_STUS_NM_DN,
	ADMIN_ITEM.ADMIN_STUS_NM_DN,
	ADMIN_ITEM.CNTXT_NM_DN,
	ADMIN_ITEM.CNTXT_ITEM_ID,
	ADMIN_ITEM.CNTXT_VER_NR,
	ADMIN_ITEM.CREAT_USR_ID CREATED_BY, 
	ADMIN_ITEM.LST_UPD_USR_ID MODIFIED_BY, 
	ADMIN_ITEM.FLD_DELETE DELETED_IND, 	
	ADMIN_ITEM.LST_UPD_DT DATA_MODIFIED, 
	ADMIN_ITEM.CREAT_DT DATE_CREATED,
	ADMIN_ITEM.LST_DEL_DT END_DATE, 
	--ADMIN_ITEM.S2P_TRN_DT BEGIN_DATE, 
    ADMIN_ITEM.ADMIN_ITEM_TYP_ID
--SELECT*
from ADMIN_ITEM ,DE ,ADMIN_ITEM DE_CONC
,ADMIN_ITEM VD,ADMIN_ITEM CONTE
where ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 4
AND ADMIN_ITEM.ITEM_ID=DE.ITEM_ID
AND ADMIN_ITEM.VER_NR=DE.VER_NR
AND DE.VAL_DOM_ITEM_ID=VD.ITEM_ID
AND DE.VAL_DOM_VER_NR=VD.VER_NR
AND DE.DE_CONC_ITEM_ID=DE_CONC.ITEM_ID
AND DE.DE_CONC_VER_NR=DE_CONC.VER_NR
AND VD.ADMIN_ITEM_TYP_ID = 3
AND DE_CONC.ADMIN_ITEM_TYP_ID=2
AND ADMIN_ITEM.CNTXT_ITEM_ID=CONTE.ITEM_ID
AND ADMIN_ITEM.CNTXT_VER_NR=CONTE.VER_NR
AND CONTE.ADMIN_ITEM_TYP_ID=8;


--select *from obj_key where OBJ_KEY_ID<9