
  CREATE OR REPLACE  VIEW VW_NCI_CONC_DOM AS
  select ai.ITEM_ID, ai.VER_NR, ai.ITEM_DESC, ai.CNTXT_ITEM_ID, ai.CNTXT_VER_NR, ai.ITEM_LONG_NM, ai.ITEM_NM, 
ai.ADMIN_NOTES, ai.CHNG_DESC_TXT, ai.EFF_DT, ai.ORIGIN, ai.UNRSLVD_ISSUE, ai.UNTL_DT, 
ai.ADMIN_ITEM_TYP_ID, ai.CURRNT_VER_IND, ai.ADMIN_STUS_ID, ai.REGSTR_STUS_ID, 
ai.REGISTRR_CNTCT_ID, ai.SUBMT_CNTCT_ID, ai.STEWRD_CNTCT_ID, ai.SUBMT_ORG_ID, ai.STEWRD_ORG_ID, 
ai.CREAT_DT, ai.CREAT_USR_ID, ai.LST_UPD_USR_ID, ai.FLD_DELETE, ai.LST_DEL_DT, ai.S2P_TRN_DT, ai.LST_UPD_DT, 
ai.REGSTR_AUTH_ID,ai.NCI_IDSEQ, ai.ADMIN_STUS_NM_DN, ai.CNTXT_NM_DN, ai.REGSTR_STUS_NM_DN, ai.ORIGIN_ID, ai.ORIGIN_ID_DN, 
cd.DIMNSNLTY,cd.NON_ENUM_DESC, cd.CONC_DOM_TYP_ID
FROM ADMIN_ITEM ai,conc_dom cd
       WHERE ai.ADMIN_ITEM_TYP_ID = 1 and ai.item_id = cd.item_id and ai.ver_nr = cd.ver_nr;
