alter table NCI_STG_AI_CNCPT_CREAT
add (ITEM_LONG_NM  varchar2(30) null,  ITEM_NM varchar2(255) null);

drop materialized view  VW_CLSFCTN_SCHM;


CREATE OR REPLACE VIEW VW_CLSFCTN_SCHM AS
SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN, ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, ADMIN_ITEM.CREAT_DT, 
ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, 
ADMIN_ITEM.LST_UPD_DT, CS.CLSFCTN_SCHM_TYP_ID, ADMIN_ITEM.NCI_IDSEQ, ADMIN_ITEM.CNTXT_ITEM_ID, ADMIN_ITEM.CNTXT_VER_NR
FROM ADMIN_ITEM, CLSFCTN_SCHM CS
       WHERE ADMIN_ITEM_TYP_ID = 9 and ADMIN_ITEM.ITEM_ID = CS.ITEM_ID and ADMIN_ITEM.VER_NR = CS.VER_NR;


drop materialized view VW_CLSFCTN_SCHM_ITEM;

CREATE OR REPLACE VIEW VW_CLSFCTN_SCHM_ITEM
   AS
 SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM,  ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN, ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, ADMIN_ITEM.CREAT_DT, 
ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, 
ADMIN_ITEM.LST_UPD_DT, ADMIN_ITEM.NCI_IDSEQ, CSI.P_ITEM_ID, CSI.P_ITEM_VER_NR, CSI.CS_ITEM_ID, CSI.CS_ITEM_VER_NR
FROM ADMIN_ITEM, NCI_CLSFCTN_SCHM_ITEM csi
       WHERE ADMIN_ITEM_TYP_ID = 51 and ADMIN_ITEM.ITEM_ID = CSI.ITEM_ID and ADMIN_ITEM.VER_NR = CSI.VER_NR;



  CREATE TABLE NCI_STG_CDE_CREAT 
   (	STG_AI_ID NUMBER NOT NULL ENABLE, 
	CTL_VAL_MSG VARCHAR2(4000 BYTE), 
    	CTL_VAL_STUS  varchar2(100) DEFAULT 'CREATED',
	CNCPT_CONCAT_STR_1 VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	CNCPT_CONCAT_STR_2 VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	CNCPT_CONCAT_STR_3 VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	CONC_DOM_ITEM_ID NUMBER, 
	CONC_DOM_VER_NR NUMBER(4,2), 
	CNTXT_ITEM_ID NUMBER, 
	CNTXT_VER_NR NUMBER(4,2), 
	CNCPT_1_ITEM_ID_1 NUMBER, 
	CNCPT_1_VER_NR_1 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_2 NUMBER, 
	CNCPT_1_VER_NR_2 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_3 NUMBER, 
	CNCPT_1_VER_NR_3 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_4 NUMBER, 
	CNCPT_1_VER_NR_4 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_5 NUMBER, 
	CNCPT_1_VER_NR_5 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_6 NUMBER, 
	CNCPT_1_VER_NR_6 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_7 NUMBER, 
	CNCPT_1_VER_NR_7 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_8 NUMBER, 
	CNCPT_1_VER_NR_8 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_9 NUMBER, 
	CNCPT_1_VER_NR_9 NUMBER(4,2), 
	CNCPT_1_ITEM_ID_10 NUMBER, 
	CNCPT_1_VER_NR_10 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_1 NUMBER, 
	CNCPT_2_VER_NR_1 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_2 NUMBER, 
	CNCPT_2_VER_NR_2 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_3 NUMBER, 
	CNCPT_2_VER_NR_3 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_4 NUMBER, 
	CNCPT_2_VER_NR_4 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_5 NUMBER, 
	CNCPT_2_VER_NR_5 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_6 NUMBER, 
	CNCPT_2_VER_NR_6 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_7 NUMBER, 
	CNCPT_2_VER_NR_7 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_8 NUMBER, 
	CNCPT_2_VER_NR_8 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_9 NUMBER, 
	CNCPT_2_VER_NR_9 NUMBER(4,2), 
	CNCPT_2_ITEM_ID_10 NUMBER, 
	CNCPT_2_VER_NR_10 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_1 NUMBER, 
	CNCPT_3_VER_NR_1 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_2 NUMBER, 
	CNCPT_3_VER_NR_2 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_3 NUMBER, 
	CNCPT_3_VER_NR_3 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_4 NUMBER, 
	CNCPT_3_VER_NR_4 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_5 NUMBER, 
	CNCPT_3_VER_NR_5 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_6 NUMBER, 
	CNCPT_3_VER_NR_6 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_7 NUMBER, 
	CNCPT_3_VER_NR_7 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_8 NUMBER, 
	CNCPT_3_VER_NR_8 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_9 NUMBER, 
	CNCPT_3_VER_NR_9 NUMBER(4,2), 
	CNCPT_3_ITEM_ID_10 NUMBER, 
	CNCPT_3_VER_NR_10 NUMBER(4,2), 
	CREAT_DT DATE DEFAULT sysdate, 
	CREAT_USR_ID VARCHAR2(50 BYTE) COLLATE USING_NLS_COMP DEFAULT user, 
	LST_UPD_USR_ID VARCHAR2(50 BYTE) COLLATE USING_NLS_COMP DEFAULT user, 
	FLD_DELETE NUMBER(1,0) DEFAULT 0, 
	LST_DEL_DT DATE DEFAULT sysdate, 
	S2P_TRN_DT DATE DEFAULT sysdate, 
	LST_UPD_DT DATE DEFAULT sysdate, 
	GEN_DE_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	GEN_DE_CONC_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	DE_CONC_ITEM_ID_FND  number,
    	DE_CONC_VER_VR_FND  number(4,2),
    	VAL_DOM_ITEM_ID_CREAT  number,
    	DE_CONC_ITEM_ID_CREAT  number,
    	ITEM_1_ID NUMBER, 
	ITEM_1_VER_NR NUMBER(4,2), 
	ITEM_1_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_1_LONG_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_1_DEF VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_2_ID NUMBER, 
	ITEM_2_VER_NR NUMBER(4,2), 
	ITEM_2_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_2_LONG_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_2_DEF VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_3_ID NUMBER, 
	ITEM_3_VER_NR NUMBER(4,2), 
	ITEM_3_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_3_LONG_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
	ITEM_3_DEF VARCHAR2(4000 BYTE) COLLATE USING_NLS_COMP, 
	DTTYPE_ID NUMBER, 
	VAL_DOM_MAX_CHAR NUMBER, 
	VAL_DOM_TYP_ID NUMBER, 
	UOM_ID NUMBER, 
	VD_CONC_DOM_VER_NR NUMBER(4,2), 
	VD_CONC_DOM_ITEM_ID NUMBER, 
	REP_CLS_VER_NR NUMBER(4,2), 
	REP_CLS_ITEM_ID NUMBER, 
	VAL_DOM_MIN_CHAR NUMBER, 
	VAL_DOM_FMT_ID NUMBER, 
	CHAR_SET_ID NUMBER, 
	VAL_DOM_HIGH_VAL_NUM VARCHAR2(50 BYTE) COLLATE USING_NLS_COMP, 
	VAL_DOM_LOW_VAL_NUM VARCHAR2(50 BYTE) COLLATE USING_NLS_COMP, 
	NCI_DEC_PREC NUMBER(2,0), 
	NCI_STD_DTTYPE_ID NUMBER, 
	CDE_ITEM_LONG_NM VARCHAR2(30 BYTE) COLLATE USING_NLS_COMP, 
	CDE_ITEM_NM VARCHAR2(255 BYTE) COLLATE USING_NLS_COMP, 
       DE_CONC_ITEM_ID  number,
       DE_CONC_VER_NR number(4,2),
       VAL_DOM_ITEM_ID number,
       VAL_DOM_VER_NR number(4,2),
      VAL_DOM_ITEM_ID_FND number,
       VAL_DOM_VER_NR_FND number(4,2),
       FORM_ITEM_ID  number,
       FORM_VER_NR   number(4,2),
       MOD_NM varchar2(255),
       PREF_QUEST_TXT varchar2(255),
    	BTCH_USR_NM  varchar2(100) not null,
        BTCH_NM  varchar2(100) not null,
        BTCH_SEQ_NBR  integer not null,
    	VAL_DOM_NM  varchar2(255) null,
	 PRIMARY KEY (STG_AI_ID));
		      
		      create or replace view VW_CNCPT 
  AS
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM,  ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, ADMIN_ITEM.CREATION_DT, 
ADMIN_ITEM.EFF_DT, ADMIN_ITEM.ORIGIN,  ADMIN_ITEM.UNTL_DT,  ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, 
 ADMIN_ITEM.CREAT_DT, ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, ADMIN_ITEM.LST_UPD_DT, 
nvl(decode(ADMIN_ITEM.DEF_SRC, 'NCI', '1-NCI', ADMIN_ITEM.DEF_SRC), 'No Def Source') DEF_SRC,
		      decode(OBJ_KEY.OBJ_KEY_DESC, 'NCI_CONCEPT_CODE', '1-NCI_CONCEPT_CODE', 'NCI_META_CUI', '2-NCI_META_CUI', OBJ_KEY.OBJ_KEY_DESC) EVS_SRC
       FROM ADMIN_ITEM, CNCPT, OBJ_KEY
       WHERE ADMIN_ITEM_TYP_ID = 49 and ADMIN_ITEM.ITEM_ID = CNCPT.ITEM_ID and ADMIN_ITEM.VER_NR = CNCPT.VER_NR
	and cncpt.EVS_SRC_ID = OBJ_KEY.OBJ_KEY_ID (+) and admin_item.admin_stus_nm_dn = 'RELEASED';

		      
create or replace view VW_CNCPT_RT_PRMRY 
  AS
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM,  ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, ADMIN_ITEM.CREATION_DT, 
ADMIN_ITEM.EFF_DT, ADMIN_ITEM.ORIGIN,  ADMIN_ITEM.UNTL_DT,  ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, 
 ADMIN_ITEM.CREAT_DT, ADMIN_ITEM.CREAT_USR_ID, ADMIN_ITEM.LST_UPD_USR_ID, ADMIN_ITEM.FLD_DELETE, ADMIN_ITEM.LST_DEL_DT, ADMIN_ITEM.S2P_TRN_DT, ADMIN_ITEM.LST_UPD_DT, 
nvl(decode(ADMIN_ITEM.DEF_SRC, 'NCI', '1-NCI', ADMIN_ITEM.DEF_SRC), 'No Def Source') DEF_SRC,
		      decode(OBJ_KEY.OBJ_KEY_DESC, 'NCI_CONCEPT_CODE', '1-NCI_CONCEPT_CODE', 'NCI_META_CUI', '2-NCI_META_CUI', OBJ_KEY.OBJ_KEY_DESC) EVS_SRC
       FROM ADMIN_ITEM, CNCPT, OBJ_KEY
       WHERE ADMIN_ITEM_TYP_ID = 49 and ADMIN_ITEM.ITEM_ID = CNCPT.ITEM_ID and ADMIN_ITEM.VER_NR = CNCPT.VER_NR
	and cncpt.EVS_SRC_ID = OBJ_KEY.OBJ_KEY_ID (+) and admin_item.admin_stus_nm_dn = 'RELEASED' and		      
		      ADMIN_ITEM.ITEM_LONG_NM in (
'C13717',
'C25372',
'C25162',
'C25463',
'C25164',
'C37939',
'C25488',
'C25330',
'C48150',
'C25515',
'C48309',
'C25364',
'C25180',
'C45255',
'C25543',
'C25209',
'C42614',
'C25337',
'C20200',
'C38013',
'C25636',
'C25638',
'C25664',
'C25338',
'C25683',
'C25685',
'C16899',
'C25688',
'C25704',
'C25207',
'C25284',
'C25709',
'C25712') ;
		      
		      
alter table nci_dload_als modify (PV_VM_IND number default null);

alter table admin_item modify (CNTXT_VER_NR number default null);
		      

  CREATE OR REPLACE VIEW VW_DE_CONC AS
  SELECT DE_CONC.LST_UPD_DT, DE_CONC.S2P_TRN_DT, DE_CONC.LST_DEL_DT, DE_CONC.FLD_DELETE, DE_CONC.LST_UPD_USR_ID, DE_CONC.CREAT_USR_ID, DE_CONC.CREAT_DT, 
DE_CONC.OBJ_CLS_VER_NR, DE_CONC.OBJ_CLS_ITEM_ID, DE_CONC.PROP_ITEM_ID, DE_CONC.PROP_VER_NR, DE_CONC.CONC_DOM_ITEM_ID, DE_CONC.CONC_DOM_VER_NR, 
ADMIN_ITEM.ITEM_ID, 
ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, 
ADMIN_ITEM.ITEM_DESC, ADMIN_ITEM.CNTXT_ITEM_ID, ADMIN_ITEM.CNTXT_VER_NR, ADMIN_ITEM.ADMIN_NOTES,
 ADMIN_ITEM.CHNG_DESC_TXT, ADMIN_ITEM.CREATION_DT, ADMIN_ITEM.EFF_DT, ADMIN_ITEM.DATA_ID_STR, ADMIN_ITEM.ADMIN_ITEM_TYP_ID, 
ADMIN_ITEM.CURRNT_VER_IND, ADMIN_ITEM.REGSTR_STUS_ID, ADMIN_ITEM.ADMIN_STUS_ID, ADMIN_STUS_NM_DN, REGSTR_STUS_NM_DN
FROM ADMIN_ITEM, DE_CONC
       WHERE ADMIN_ITEM.ADMIN_ITEM_TYP_ID=2 
AND ADMIN_ITEM.ITEM_ID = DE_CONC.ITEM_ID
AND ADMIN_ITEM.VER_NR = DE_CONC.VER_NR;
		      
		      
		      
  CREATE OR REPLACE  VIEW VW_VALUE_DOM AS
  SELECT ADMIN_ITEM.ITEM_ID, ADMIN_ITEM.VER_NR, ADMIN_ITEM.ITEM_NM, ADMIN_ITEM.ITEM_LONG_NM, ADMIN_ITEM.ITEM_DESC, 
ADMIN_ITEM.CNTXT_NM_DN,  ADMIN_ITEM.REGSTR_STUS_NM_DN, ADMIN_ITEM.ADMIN_STUS_NM_DN, 
		      ADMIN_ITEM.CURRNT_VER_IND, VALUE_DOM.DTTYPE_ID, VALUE_DOM.VAL_DOM_MAX_CHAR, VALUE_DOM.CONC_DOM_VER_NR, VALUE_DOM.CONC_DOM_ITEM_ID, 
VALUE_DOM.NON_ENUM_VAL_DOM_DESC, VALUE_DOM.UOM_ID, VALUE_DOM.VAL_DOM_TYP_ID, VALUE_DOM.VAL_DOM_MIN_CHAR, VALUE_DOM.VAL_DOM_FMT_ID, 
VALUE_DOM.CHAR_SET_ID, VALUE_DOM.CREAT_DT, VALUE_DOM.CREAT_USR_ID, VALUE_DOM.LST_UPD_USR_ID, 
VALUE_DOM.FLD_DELETE, VALUE_DOM.LST_DEL_DT, VALUE_DOM.S2P_TRN_DT, VALUE_DOM.LST_UPD_DT , RC.ITEM_NM  REP_TERM_ITEM_NM
FROM ADMIN_ITEM, VALUE_DOM, VW_REP_CLS RC
       WHERE ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 3
AND ADMIN_ITEM.ITEM_ID = VALUE_DOM.ITEM_ID
AND ADMIN_ITEM.VER_NR=VALUE_DOM.VER_NR and
VALUE_DOM.REP_CLS_ITEM_ID = RC.ITEM_ID (+) and 
VALUE_DOM.REP_CLS_VER_NR = RC.VER_NR (+);


		     alter table NCI_STG_AI_CNCPT_CREAT add (BTCH_USR_NM  varchar2(100) not null,
        BTCH_NM  varchar2(100) not null);
		      
