
  CREATE OR REPLACE  VIEW VW_NCI_DE AS
  select 
	ADMIN_ITEM.ITEM_ID, 
	ADMIN_ITEM.VER_NR, 
        '.' || ADMIN_ITEM.ITEM_ID || '.' ITEM_ID_STR,
	ADMIN_ITEM.ITEM_NM, 
	ADMIN_ITEM.ITEM_LONG_NM, 
	ADMIN_ITEM.ITEM_DESC, 
	ADMIN_ITEM.ADMIN_NOTES, 
	ADMIN_ITEM.CHNG_DESC_TXT, 
	ADMIN_ITEM.CREATION_DT, 
	ADMIN_ITEM.EFF_DT, 
	ADMIN_ITEM.ORIGIN, 
        ADMIN_ITEM.ORIGIN_ID,
	ADMIN_ITEM.ORIGIN_ID_DN,
	ADMIN_ITEM.UNRSLVD_ISSUE, 
	ADMIN_ITEM.UNTL_DT, 
	ADMIN_ITEM.CURRNT_VER_IND, 
	ADMIN_ITEM.REGSTR_STUS_ID, 
	ADMIN_ITEM.ADMIN_STUS_ID, 
--	ADMIN_ITEM.REGSTR_STUS_NM_DN,
--	ADMIN_ITEM.ADMIN_STUS_NM_DN,
	ADMIN_ITEM.CNTXT_NM_DN,
	ADMIN_ITEM.CNTXT_ITEM_ID,
	ADMIN_ITEM.CNTXT_VER_NR,
	ADMIN_ITEM.CREAT_USR_ID, 
	ADMIN_ITEM.CREAT_USR_ID_X, 
	ADMIN_ITEM.LST_UPD_USR_ID, 
	ADMIN_ITEM.LST_UPD_USR_ID_X, 
        rs.DISP_ORD REGSTR_STUS_DISP_ORD,
        as.DISP_ORD ADMIN_STUS_DISP_ORD,
	ADMIN_ITEM.FLD_DELETE, 
	ADMIN_ITEM.LST_DEL_DT, 
	ADMIN_ITEM.S2P_TRN_DT, 
	ADMIN_ITEM.LST_UPD_DT, 
	ADMIN_ITEM.CREAT_DT,
ADMIN_ITEM.NCI_IDSEQ,
ADMIN_ITEM_TYP_ID,
  ext.USED_BY CNTXT_AGG,
	ref.ref_desc PREF_QUEST_TXT,
	    substr(ADMIN_ITEM.ITEM_LONG_NM || 	ADMIN_ITEM.ITEM_NM || nvl(ref.ref_desc, ''),1,4000)  SEARCH_STR 
from ADMIN_ITEM, 
NCI_ADMIN_ITEM_EXT ext,
 (select item_id, ver_nr, ref_desc from ref where ref_typ_id = 80) ref,
VW_REGSTR_STUS rs,
VW_ADMIN_STUS as
  where ADMIN_ITEM_TYP_ID = 4 
--and ADMIN_ITEM.ITEM_Id = de.item_id 
--and ADMIN_ITEM.VER_NR = DE.VER_NR
and ADMIN_ITEM.ITEM_ID = EXT.ITEM_ID
and ADMIN_ITEM.VER_NR = EXT.VER_NR
and ADMIN_ITEM.ITEM_ID = REF.ITEM_ID(+)
and ADMIN_ITEM.VER_NR = REF.VER_NR(+)
and ADMIN_ITEM.REGSTR_STUS_ID = rs.STUS_ID (+)
and ADMIN_ITEM.ADMIN_STUS_ID = as.STUS_ID (+);


  CREATE OR REPLACE  VIEW VW_NCI_CSI_NODE AS
  SELECT NODE.NCI_PUB_ID, NODE.NCI_VER_NR, CSI.ITEM_ID, CSI.VER_NR, CSI.ITEM_NM, CSI.ITEM_LONG_NM, CSI.ITEM_DESC, 
CSI.CNTXT_NM_DN, CSI.CURRNT_VER_IND, CSI.REGSTR_STUS_NM_DN, CSI.ADMIN_STUS_NM_DN, NODE.CREAT_DT, 
NODE.CREAT_USR_ID, NODE.LST_UPD_USR_ID, NODE.FLD_DELETE, NODE.LST_DEL_DT, NODE.S2P_TRN_DT, 
NODE.LST_UPD_DT,
cs.item_id cs_item_id, cs.ver_nr cs_ver_nr , cs.item_long_nm cs_long_nm, cs.item_nm cs_item_nm, cs.item_desc cs_item_desc,
pcsi.item_id pcsi_item_id, pcsi.ver_nr pcsi_ver_nr, pcsi.item_long_nm pcsi_long_nm, pcsi.item_nm pcsi_item_nm
FROM ADMIN_ITEM CSI, NCI_ADMIN_ITEM_REL_ALT_KEY NODE, ADMIN_ITEM CS, ADMIN_ITEM PCSI
       WHERE csi.ADMIN_ITEM_TYP_ID = 51 and node.c_item_id = csi.item_id and node.c_item_ver_nr = csi.ver_nr
       and node.cntxt_cs_item_id = cs.item_id and node.cntxt_cs_Ver_nr = cs.ver_nr
       and node.rel_typ_id = 64
       and node.p_item_id = pcsi.item_id (+)
       and node.p_item_ver_nr = pcsi.ver_nr (+)
       and pcsi.admin_item_typ_id (+) = 51
       and cs.admin_item_typ_id = 9;


alter table admin_item add (CREAT_USR_ID_X varchar2(50), LST_UPD_USR_ID_X varchar2(50));
alter table de add (PREF_QUEST_TXT  varchar2(4000));


drop trigger TR_AI_AUDIT_TAB_INS;



  CREATE OR REPLACE  VIEW VW_NCI_DE_HORT AS
  SELECT 
	ADMIN_ITEM.ITEM_ID ITEM_ID, 
	ADMIN_ITEM.VER_NR, 
	ADMIN_ITEM.ITEM_NM, 
	ADMIN_ITEM.ITEM_LONG_NM, 
	ADMIN_ITEM.ITEM_DESC, 
	ADMIN_ITEM.CNTXT_NM_DN, 
	ADMIN_ITEM.ORIGIN, 
	ADMIN_ITEM.UNTL_DT, 
	ADMIN_ITEM.CURRNT_VER_IND, 
	DE.DE_PREC,
	DE.DE_CONC_ITEM_ID,
	DE.DE_CONC_VER_NR, 
	DE.VAL_DOM_VER_NR, 
	DE.VAL_DOM_ITEM_ID,
	DE.REP_CLS_VER_NR, 
	DE.REP_CLS_ITEM_ID, 
DE.DERV_DE_IND,
DE.DERV_MTHD,
DE.DERV_RUL,
DE.DERV_TYP_ID,
	DE.CREAT_USR_ID, 
	DE.LST_UPD_USR_ID, 
	DE.FLD_DELETE, 
	DE.LST_DEL_DT, 
	DE.S2P_TRN_DT, 
	DE.LST_UPD_DT, 
	DE.CREAT_DT, 
	DE.CREAT_USR_ID CREAT_USR_ID_API, 
	DE.LST_UPD_USR_ID LST_UPD_USR_ID_API, 
	DE.CREAT_DT CREAT_DT_API, 
	DE.LST_UPD_DT LST_UPD_DT_API, 
	VALUE_DOM.CONC_DOM_VER_NR, 
	VALUE_DOM.CONC_DOM_ITEM_ID, 
	VALUE_DOM.NON_ENUM_VAL_DOM_DESC, 
	VALUE_DOM.UOM_ID, 
	VALUE_DOM.VAL_DOM_TYP_ID VAL_DOM_TYP_ID, 
	VALUE_DOM.VAL_DOM_MIN_CHAR, 
	VALUE_DOM.VAL_DOM_MAX_CHAR, 
	VALUE_DOM.VAL_DOM_FMT_ID, 
	VALUE_DOM.CHAR_SET_ID, 
	VALUE_DOM.CREAT_DT VALUE_DOM_CREAT_DT, 
	VALUE_DOM.CREAT_USR_ID VALUE_DOM_USR_ID, 
	VALUE_DOM.LST_UPD_USR_ID VALUE_DOM_LST_UPD_USR_ID, 
	VALUE_DOM.LST_UPD_DT VALUE_DOM_LST_UPD_DT,
	VALUE_DOM_AI.ITEM_NM VALUE_DOM_ITEM_NM, 
	VALUE_DOM_AI.ITEM_LONG_NM VALUE_DOM_ITEM_LONG_NM, 
	VALUE_DOM_AI.ITEM_DESC  VALUE_DOM_ITEM_DESC, 
	VALUE_DOM_AI.CNTXT_NM_DN VALUE_DOM_CNTXT_NM, 
	VALUE_DOM_AI.CURRNT_VER_IND VALUE_DOM_CURRNT_VER_IND, 
	VALUE_DOM_AI.REGSTR_STUS_NM_DN VALUE_DOM_REGSTR_STUS_NM, 
	VALUE_DOM_AI.ADMIN_STUS_NM_DN VALUE_DOM_ADMIN_STUS_NM, 
	VALUE_DOM.NCI_STD_DTTYPE_ID,
    VALUE_DOM.DTTYPE_ID,
	ADMIN_ITEM.REGSTR_AUTH_ID,
	DEC_AI.ITEM_NM DEC_ITEM_NM, 
	DEC_AI.ITEM_LONG_NM DEC_ITEM_LONG_NM, 
	DEC_AI.ITEM_DESC  DEC_ITEM_DESC, 
	DEC_AI.CNTXT_NM_DN DEC_CNTXT_NM, 
	DEC_AI.CURRNT_VER_IND DEC_CURRNT_VER_IND, 
	DEC_AI.REGSTR_STUS_NM_DN DEC_REGSTR_STUS_NM, 
	DEC_AI.ADMIN_STUS_NM_DN DEC_ADMIN_STUS_NM, 
	DEC_AI.CREAT_DT DEC_CREAT_DT, 
	DEC_AI.CREAT_USR_ID DEC_USR_ID, 
	DEC_AI.LST_UPD_USR_ID DEC_LST_UPD_USR_ID, 
	DEC_AI.LST_UPD_DT DEC_LST_UPD_DT,
	DE_CONC.OBJ_CLS_ITEM_ID,
	DE_CONC.OBJ_CLS_VER_NR,
        OC.ITEM_NM OBJ_CLS_ITEM_NM,
        OC.ITEM_LONG_NM OBJ_CLS_ITEM_LONG_NM,
        PROP.ITEM_NM PROP_ITEM_NM,
        PROP.ITEM_LONG_NM PROP_ITEM_LONG_NM,
	DE_CONC.PROP_ITEM_ID,
	DE_CONC.PROP_VER_NR,
	CD_AI.ITEM_NM CD_ITEM_NM, 
	CD_AI.ITEM_LONG_NM CD_ITEM_LONG_NM, 
	CD_AI.ITEM_DESC  CD_ITEM_DESC, 
	CD_AI.CNTXT_NM_DN CD_CNTXT_NM, 
	CD_AI.CURRNT_VER_IND CD_CURRNT_VER_IND, 
	CD_AI.REGSTR_STUS_NM_DN CD_REGSTR_STUS_NM, 
	CD_AI.ADMIN_STUS_NM_DN CD_ADMIN_STUS_NM, 
	       ADMIN_ITEM.ADMIN_ITEM_TYP_ID ,
        '' CNTXT_AGG,
        SYSDATE - greatest(DE.LST_UPD_DT, admin_item.lst_upd_dt, Value_dom.LST_UPD_DT, dec_ai.LST_UPD_DT) LST_UPD_CHG_DAYS
       FROM ADMIN_ITEM, DE,  VALUE_DOM, ADMIN_ITEM VALUE_DOM_AI, 
	ADMIN_ITEM DEC_AI, DE_CONC,
	ADMIN_ITEM CD_AI, ADMIN_ITEM OC, ADMIN_ITEM PROP
       WHERE ADMIN_ITEM.ADMIN_ITEM_TYP_ID = 4
AND DE.ITEM_ID = ADMIN_ITEM.ITEM_ID
and DE.VER_NR = ADMIN_ITEM.VER_NR
and DE.VAL_DOM_ITEM_ID = VALUE_DOM_AI.ITEM_ID
and DE.VAL_DOM_VER_NR = VALUE_DOM_AI.VER_NR
and DE.VAL_DOM_ITEM_ID = VALUE_DOM.ITEM_ID
and DE.VAL_DOM_VER_NR = VALUE_DOM.VER_NR
and DE.DE_CONC_ITEM_ID = DEC_AI.ITEM_ID
and DE.DE_CONC_VER_NR = DEC_AI.VER_NR
and DE.DE_CONC_ITEM_ID = DE_CONC.ITEM_ID
and DE_CONC.OBJ_CLS_ITEM_ID = OC.ITEM_ID
and DE_CONC.OBJ_CLS_VER_NR = OC.VER_NR
and DE_CONC.PROP_ITEM_ID = PROP.ITEM_ID
and DE_CONC.PROP_VER_NR = PROP.VER_NR
and DE.DE_CONC_VER_NR = DE_CONC.VER_NR
and DE_CONC.CONC_DOM_ITEM_ID = CD_AI.ITEM_ID
and DE_CONC.CONC_DOM_VER_NR = CD_AI.VER_NR;

alter table NCI_ADMIN_ITEM_REL_ALT_KEY modify (C_ITEM_ID number null, C_ITEM_VER_NR number(4,2) null);



  CREATE OR REPLACE  VIEW VW_NCI_ALT_NMS AS
  SELECT ALT_NMS.NM_ID, 'CDE' ALT_NMS_LVL, DE_AI.ITEM_ID  DE_ITEM_ID, 
		DE_AI.VER_NR DE_VER_NR,
		ALT_NMS.ITEM_ID, ALT_NMS.VER_NR, 
		ALT_NMS.CNTXT_ITEM_ID, ALT_NMS.CNTXT_VER_NR, 
		ALT_NMS.NM_DESC, 
        	ALT_NMS.PREF_NM_IND, ALT_NMS.LANG_ID, AGG.CSI_ALT_NMS,
		ALT_NMS.CREAT_DT, ALT_NMS.CREAT_USR_ID, ALT_NMS.LST_UPD_USR_ID, ALT_NMS.FLD_DELETE, ALT_NMS.LST_DEL_DT, ALT_NMS.S2P_TRN_DT, ALT_NMS.LST_UPD_DT, ALT_NMS.NM_TYP_ID
       FROM ALT_NMS, ADMIN_ITEM DE_AI,
       (select a.nm_id, listagg(cs.item_nm ||  '/' || ai.item_nm, chr(10)) within group (order by a.item_id) CSI_ALT_NMS
        from alt_nms a , NCI_CSI_ALT_DEFNMS n, nci_admin_item_rel_alt_key x, admin_item ai , admin_item cs, de
       where n.nmdef_id = a.nm_id and n.nci_pub_id = x.nci_pub_id and x.c_item_id = ai.item_id and a.item_id = de.item_id and a.ver_nr = de.ver_nr
       and x.c_item_ver_nr = ai.ver_nr and x.cntxt_cs_item_id = cs.item_id and x.cntxt_cs_ver_nr = cs.ver_nr
       group by a.nm_id) agg
 where DE_AI.ADMIN_ITEM_TYP_ID = 4 and
	ALT_NMS.ITEM_ID = DE_AI.ITEM_ID and
	ALT_NMS.VER_NR = DE_AI.VER_NR and upper(ALT_NMS.NM_DESC) <> upper(ALT_NMS.CNTXT_NM_DN) 
	and alt_nms.nm_id = agg.nm_id (+);


  CREATE OR REPLACE VIEW VW_NCI_ALT_DEF AS
  SELECT ALT_DEF.DEF_ID, 'CDE' ALT_DEF_LVL, DE_AI.ITEM_ID  DE_ITEM_ID, 
		DE_AI.VER_NR DE_VER_NR,
		ALT_DEF.ITEM_ID, ALT_DEF.VER_NR, 
		ALT_DEF.CNTXT_ITEM_ID, ALT_DEF.CNTXT_VER_NR, 
		ALT_DEF.DEF_DESC, ALT_DEF.NCI_DEF_TYP_ID,
        	ALT_DEF.PREF_DEF_IND, ALT_DEF.LANG_ID, AGG.CSI_ALT_DEFS,
		ALT_DEF.CREAT_DT, ALT_DEF.CREAT_USR_ID, ALT_DEF.LST_UPD_USR_ID, ALT_DEF.FLD_DELETE, 
        ALT_DEF.LST_DEL_DT, ALT_DEF.S2P_TRN_DT, ALT_DEF.LST_UPD_DT
       FROM ALT_DEF, ADMIN_ITEM DE_AI,
      (select a.def_id, listagg(cs.item_nm ||  '/' || ai.item_nm, chr(10)) within group (order by a.item_id) CSI_ALT_DEFS
        from alt_def a , NCI_CSI_ALT_DEFNMS n, nci_admin_item_rel_alt_key x, admin_item ai , admin_item cs, de
       where n.nmdef_id = a.def_id and n.nci_pub_id = x.nci_pub_id and x.c_item_id = ai.item_id  and a.item_id = de.item_id and a.ver_nr = de.ver_nr
       and x.c_item_ver_nr = ai.ver_nr and x.cntxt_cs_item_id = cs.item_id and x.cntxt_cs_ver_nr = cs.ver_nr
       group by a.def_id) agg
 where DE_AI.ADMIN_ITEM_TYP_ID = 4 and
	ALT_DEF.ITEM_ID = DE_AI.ITEM_ID and
	ALT_DEF.VER_NR = DE_AI.VER_NR and
	ALT_DEF.DEF_ID = AGG.DEF_ID (+);


