GRANT DELETE, ON COMMIT REFRESH, SELECT, READ, ALTER on nci_stg_alt_nms to onedata_wa;
GRANT DELETE, ON COMMIT REFRESH, SELECT, READ, ALTER on nci_stg_form_import to onedata_wa;
GRANT DELETE, ON COMMIT REFRESH, SELECT, READ, ALTER on NCI_STG_CDE_CREAT to onedata_wa;
GRANT DELETE, ON COMMIT REFRESH, SELECT, READ, ALTER on NCI_STG_PV_VM_IMPORT to onedata_wa;
