  CREATE OR REPLACE EDITIONABLE TRIGGER "ONEDATA_WA"."OD_TR_FORM_IMPORT" BEFORE INSERT  on NCI_STG_FORM_IMPORT  for each row
     BEGIN    IF (:NEW.FORM_IMP_ID = -1  or :NEW.FORM_IMP_ID is null)  THEN select od_seq_FORM_IMPORT.nextval
 into :new.FORM_IMP_ID  from  dual ;   END IF;
 END;

/
ALTER TRIGGER "ONEDATA_WA"."OD_TR_FORM_IMPORT" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ONEDATA_WA"."OD_TR_FORM_IMPORT_AUD" 
BEFORE INSERT OR UPDATE ON NCI_STG_FORM_IMPORT
for each row
BEGIN
:new.LST_UPD_DT_CHAR := TO_CHAR(SYSDATE, 'MM/DD/YY HH24:MI:SS');
:new.LST_UPD_DT := sysdate;
:new.DT_SORT := systimestamp();
END;
/
ALTER TRIGGER "ONEDATA_WA"."OD_TR_FORM_IMPORT_AUD" ENABLE;

