CREATE TABLE SAG_CONCEPT_MERGE_BY_DATE
(
  RETIRED_DT    DATE                            NOT NULL,
  CODE_RETIRED  VARCHAR2(120 BYTE)              NOT NULL,
  ACTION        VARCHAR2(50 BYTE),
  NAME_DESC     VARCHAR2(2000 BYTE),
  ACTIVE_CODE   VARCHAR2(120 BYTE)
);
CREATE TABLE SAG_CONCEPT_RETIRED_BY_DATE
(
  RETIRED_DT    DATE,
  CODE_RETIRED  VARCHAR2(50 BYTE),
  NAME_DESC     VARCHAR2(2000 BYTE),
  ACTION        VARCHAR2(50 BYTE),
  ACTIVE_CODE   VARCHAR2(120 BYTE)
);
GRANT SELECT ON SAG_CONCEPT_MERGE_BY_DATE TO ONEDATA_RO;
GRANT SELECT ON SAG_CONCEPT_RETIRED_BY_DATE TO ONEDATA_RO;