OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\JIRA-DSRMWS-701\QA_OBJECTS_TEMP.csv' "str '\r'" 
BADFILE 'C:\meta\JIRA-DSRMWS-701\QA_OBJECTS_TEMP.bad'
DISCARDFILE 'C:\meta\JIRA-DSRMWS-701\QA_OBJECTS_TEMP' 
INTO TABLE "ONEDATA_WA"."QA_OBJECTS_TEMP"
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS                 
   (OBJECT_TYPE    ,
  OBJECT_NAME     ,
  SUBOBJECT_NAME  ,
  STATUS)