OPTIONS ( ERRORS= 10000, SKIP=1)
LOAD DATA
INFILE 'C:\meta\JIRA-DSRMWS-701\QA_TABLE_MTVW_TEMP.csv' "str '\r'" 
BADFILE 'C:\meta\JIRA-DSRMWS-701\QA_TABLE_MTVW_TEMP.bad'
DISCARDFILE 'C:\meta\JIRA-DSRMWS-701\QA_TABLE_MTVW_TEMP' 
INTO TABLE "ONEDATA_WA"."QA_TABLE_MTVW_TEMP"
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS                 
   (table_name    ,
  column_name    ,
  DATA_LENGTH  ,
  DATA_TYPE,
  COLUMN_ID,
  NULLABLE)
  
